### ISSUE TITLE
not seeing map and list not initialized?

### ISSUE THREAD

**Issue by kostiag** [tolu360/react-native-google-places#1]
Running it in an iOS simulator. Location is set and coordinates are specified. However and picker is opened map is not displayed and list is not initialized to places near by. What am I doing wrong if anything?

**Comment by tolu360** [comment]
Hello @kostiag, do you have any build errors? Paste those errors here, if any. Is your app building with no issues in XCode? Hope you are opening your app with the `.xcworkspace` file and not the `.xcodeproj` file?

And what do you mean when you say `Location is set and coordinates are specified`? Do you mean you are getting a `Google Place` object returned from calling `RNGooglePlaces.openPlacePickerModal()`?

Lastly, what version of `RN` are you running? Answering these quick questions would help to figure out what you are doing wrong, if anything at all.

NB: The `PlacePickerModal` is initialized/centered around the user's/device's current location, you can test on a physical device or simulate that on the simulator by manually entering your desired coordinates in `Debug > Location > Custom Location` and then `Cmd+R` to reload your app.

**Comment by kostiag** [comment]
First, I really appreciate your prompt response!
I just figured out the issue, I apologize. I was using openAutocompleteModal because I could not get openPlacePickerModal to work at all at some point. It is working as expected right now. 
Feature:
One thing that would be nice is ability to filter out the list of returned places prior to displaying this list.

**Comment by kostiag** [comment]
Although I still do not see a map. 
![screen shot 2016-11-01 at 9 09 47 am](https://cloud.githubusercontent.com/assets/3508101/19890755/00c342b8-a013-11e6-8129-533064201750.png)

**Comment by tolu360** [comment]
HI @kostiag. Glad you have got it working somewhat. I have been in transit. I would definitely see if I can reproduce the issues you are having before the week is over. 

Ensure you have imported and initialized the map services properly in `AppDelegate.m` (See README - just to be sure). And use the search option to pick other places and see if the map shows up.

Then for the feature you mentioned above, this is not really possible with either the Google Place Autocomplete or PlacePicker modals. However, there's a third option the SDK allows that may do just what you want - if you do not mind crafting the UI yourself. It only allows you to post a search query and returns an array of suggestion, it leaves building the UI to you completely. Is this something you may find useful?

**Comment by kostiag** [comment]
Hi, yeah I figured as much. Which SDK do you speak of can you point me in
the right direction? I am using regular fetch for an API call, but perhaps
SDK would be nicer. Also in case you ran into this. I have created an iOS
key that works with your code of course, but trying to use that key as part
of URL in fetch does not work and the only thing I could get to work is
unrestricted API Key. Do you know what needs to be done to be able to make
fetch calls from react native app directly to google places api using
restricted key?
