### ISSUE TITLE
Only known places can be selected

### ISSUE THREAD

**Issue by diaraujo13** [tolu360/react-native-google-places#10]
My problem is the following:
When I select a place in map, a point in a street, the "SELECT" buttons goes disabled, and none information about that point (street, latitude, longitude) is returned:

![image](https://cloud.githubusercontent.com/assets/6627361/21657609/d72897fc-d2a1-11e6-8734-1854ef25ec7e.png)

How can I make any place in the map "selectable", instead of "only know places"?

I wish something like this:

![image](https://cloud.githubusercontent.com/assets/6627361/21657509/4f0467ac-d2a1-11e6-8268-94529c1c9700.png)

Is possible?

**Comment by tolu360** [comment]
Hello @diaraujo13, please ensure your API keys have permissions for `Places`, the `Select` button appearing disabled is usually a sign you don't have all the right permissions. Please also follow the steps in this thread https://github.com/tolu360/react-native-google-places/issues/7#issuecomment-267151189 and the recommendations afterwards.

Also test on a physical device as well. Cheers.

**Comment by diaraujo13** [comment]
Thank you for reply! 
But i'm still getting error
No info in adb-logcat
Apis activated in google console

The only problem solved was google place that was closing automatically. Now it opens, but returns error:
![image](https://cloud.githubusercontent.com/assets/6627361/21708856/2c28eb3e-d3bb-11e6-8739-a091ce78a3df.png)

Now, even selecting a place, it loads for a while and the 'disabled' select button appears.

![image](https://cloud.githubusercontent.com/assets/6627361/21708877/50b76d36-d3bb-11e6-84af-9dea51c97a2a.png)

The problem is only with key?

**Comment by diaraujo13** [comment]
I tried with tried with physical device, but no success =\

**Comment by tolu360** [comment]
From just the information you have shared, yes, it looks to me like this is just an issue with your API key - please add or ensure you have added `Google Map Android` and `Google Places` permissions to your key, restrict your key to android by adding your app ID in the developer console. Try every step this person took to resolve a similar issue as you have in this very comment - https://github.com/tolu360/react-native-google-places/issues/7#issuecomment-267397283

**Comment by she-dev** [comment]
@diaraujo13 Your problem looks a lot like mine and it looks like it's related to the key. Make sure to go through all the steps on the issue @tolu360 pointed.

**Comment by diaraujo13** [comment]
Thank you for all @she-dev  @tolu360 ! Your support was fundamental to keep going searching for a solution!

SOLUTION:

in build.gradle:

dependencies  {
   ....
     compile "com.google.android.gms:play-services-places:9.2.0"
}
