### ISSUE TITLE
undefined is not an object (evaluating 'RNGooglePlaces.getAutocompletePredictions') in Android

### ISSUE THREAD

**Issue by rahulkant13may** [tolu360/react-native-google-places#100]
![screenshot_2017-11-26-22-47-54](https://user-images.githubusercontent.com/17025088/33242534-7e4a8684-d2fc-11e7-937f-11cdee9a3c58.png)

**App.js**

```javascript
import React from 'react';
import { StyleSheet, Text, View, Button } from 'react-native';
import RNGooglePlaces from "react-native-google-places";

export default class App extends React.Component {

  render() {
      function clickme(){
        RNGooglePlaces.getAutocompletePredictions('facebook')
          .then((results) =>console.log(results))
          .catch((error) => console.log(error.message));    
      }
    return (
      <View style={styles.container}>
        <Text>App.js to start working on your app!</Text>
        <Text>Changes you make will automatically reload.</Text>
        <Text>Shake your phone to open the developer menu.</Text>
        <Button
          onPress={() => clickme()}
          title="Google Places"
          color="#841584"
          accessibilityLabel="Learn more about Google Places"
        />

      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

**Steps I followed**

1. npm i react-native-google-places --save
2. react-native link react-native-google-places
3. Added my API key and enabled it also on my Google API account
```java 	
<meta-data
		android:name="com.google.android.geo.API_KEY"
		android:value="YOUR_ANDROID_API_KEY_HERE"/>
```
How to resolve this issue ?

**Comment by tolu360** [comment]
Please move the call to `RNGooglePlaces.getAutocompletePredictions()` out of the `render` method to a separate method - there's a high chance of your native modules being `undefined` when your component first renders.

**Comment by rahulkant13may** [comment]
I have tried this also , same error is coming , Is I am missing something else ?
```javascript
import React from 'react';
import { StyleSheet, Text, View, Button } from 'react-native';
import RNGooglePlaces from "react-native-google-places";

export default class App extends React.Component {
     clickme(){
        RNGooglePlaces.getAutocompletePredictions('facebook')
          .then((results) =>console.log(results))
          .catch((error) => console.log(error.message));    
      }
  render() {

    return (
      <View style={styles.container}>
        <Text>App.js to start working on your app!</Text>
        <Text>Changes you make will automatically reload.</Text>
        <Text>Shake your phone to open the developer menu.</Text>
        <Button
          onPress={() => this.clickme()}
          title="Google Places"
          color="green"
          accessibilityLabel="Learn more about Google Places"
        />

      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});


```

**Comment by lakexyde** [comment]
Had the same problem but here's how I solved it...  Looks like ```react-native link react-native-google-places``` doesn't add it to the list of packages.  So you'll need to edit your MainApplication.java

```
import com.arttitude360.reactnative.rngoogleplaces.RNGooglePlacesPackage;```
Then add to the list of packages in the ```getPackages()``` method:
```
...
new RNGooglePlacesPackage()
```
Hope it helps...

**Comment by rahulkant13may** [comment]
@lakexyde I have checked my MainApplication.java , but the above two lines you have mentioned are already there , anyways thanks for the reply.

**Comment by rahulkant13may** [comment]
@tolu360 @lakexyde 

I have hosted my repo on which I am testing the RNGooglePlaces is:

https://github.com/rahulkant13may/RNGooglePlacesAPITest.git

[https://github.com/rahulkant13may/RNGooglePlacesAPITest](url)

Please add the API Key  in android > app > src > main > AndroidManifest.xml
I have removed mine from there :)
```java
<meta-data
		android:name="com.google.android.geo.API_KEY"
		android:value="YOUR_ANDROID_API_KEY_HERE"/>
``` 
If there is something which I am missing then please let me know to resolve this error.

**Comment by rahulkant13may** [comment]
how to solve this ?

**Comment by tktdw** [comment]
try editting code onPress={() => clickme()} to onPress={() => this.clickme()}

**Comment by SushilShrestha** [comment]
Had same error while using the lib first time. Following steps resolved my issue.

**Comment by rahulkant13may** [comment]
@SushilShrestha I have already installed it the same you have told , you can read my above comments for how I installed it, if there is any mistake then pls let me know, I am getting the same error. I have also hosted the the sample project on my github to test this library.
Anyways thanks for the help.

https://github.com/rahulkant13may/RNGooglePlacesAPITest.git

**Comment by tolu360** [comment]
Hi @rahulkant13may, have you figured things out now? If not, try to run the [sample app](https://github.com/tolu360/TestRNGP) on your machine, see if you can reproduce your issue
