### ISSUE TITLE
RNGooglePlaces.getCurrentPlace return Google Place API error

### ISSUE THREAD

**Issue by CrazzzyDev** [tolu360/react-native-google-places#102]
I am calling RNGooglePlaces.getCurrentPlace() and it returns below response

Error: The operation couldn’t be completed. An internal error occurred in the Places API library. If you believe this error represents a bug, please file a report using the instructions on our community and support page (https://developers.google.com/places/support).

Does current place really require place API?

**Comment by vladimir830** [comment]
I am also getting below error message.

"The operation couldn't be completed. The Places API could not find the user's location. This may be because the user has not allowed the application to access location information."

How to solve this?

**Comment by SidharthRaveendran** [comment]
I'm also facing the same issue, This stops the api from working.

**Comment by BigPun86** [comment]
+1

**Comment by tolu360** [comment]
Try the [sample app](https://github.com/tolu360/TestRNGP), see if you can reproduce issue. Feel free to re-open if this is still an issue. Cheers!

**Comment by cinder92** [comment]
same issue here

**Comment by NickLatin0** [comment]
I am also getting this issue

**Comment by krunal767** [comment]
same issue here. any one fix for this issues?
