### ISSUE TITLE
Cannot change language of the map

### ISSUE THREAD

**Issue by huyvohcmc** [tolu360/react-native-google-places#103]
I did just exactly like the suggests from #56 and #20 i.e. change my device's language to French but the language in the map stay English (for example "Select a location", "Back" button and "Updating nearby places"). Does anyone know how to fix this?
![screen shot 2017-12-13 at 6 10 43 pm](https://user-images.githubusercontent.com/17645203/33936121-fdb7e9e8-e030-11e7-8ff2-0860fd75b679.png)
![screen shot 2017-12-13 at 6 11 24 pm](https://user-images.githubusercontent.com/17645203/33936130-0bfaa96e-e031-11e7-8b3f-c6a0755832ce.png)

**Comment by notme1994** [comment]
I also had this problem. Solved it by adding the desired language to "Localizations" in build settings in Xcode.

![image](https://user-images.githubusercontent.com/30912018/36304756-7710bfac-1319-11e8-9dd6-56baa4dbaf83.png)
 
After that changing the system language works to localize the map ui.
