### ISSUE TITLE
App crash after installed on emulator or device.

### ISSUE THREAD

**Issue by tktdw** [tolu360/react-native-google-places#104]

**Comment by tktdw** [comment]
this is error come in while my app succesfully installed on device or emulator

E/AndroidRuntime( 9556): FATAL EXCEPTION: AsyncTask #3
E/AndroidRuntime( 9556): Process: com.taxiexpress, PID: 9556
E/AndroidRuntime( 9556): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime( 9556):        at android.os.AsyncTask$3.done(AsyncTask.java:300)
E/AndroidRuntime( 9556):        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime( 9556):        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime( 9556):        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime( 9556):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 9556):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 9556):        at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime( 9556): Caused by: java.lang.AbstractMethodError: abstract method "com.google.android.gms.common.api.Api$zze com.google.android.gms.common.api.Api$zza.zza(android.content.Context, android.os.Looper, com.google.android.gms.common.internal.zzq, java.lang.Object, com.google.android.gms.common.api.GoogleApiClient$ConnectionCallbacks, com.google.android.gms.common.api.GoogleApiClient$OnConnectionFailedListener)"
E/AndroidRuntime( 9556):        at com.google.android.gms.common.api.GoogleApiClient$Builder.build(Unknown Source)
E/AndroidRuntime( 9556):        at com.arttitude360.reactnative.rngoogleplaces.RNGooglePlacesModule.buildGoogleApiClient(RNGooglePlacesModule.java:76)
E/AndroidRuntime( 9556):        at com.arttitude360.reactnative.rngoogleplaces.RNGooglePlacesModule.<init>(RNGooglePlacesModule.java:59)
E/AndroidRuntime( 9556):        at com.arttitude360.reactnative.rngoogleplaces.RNGooglePlacesPackage.createNativeModules(RNGooglePlacesPackage.java:29)
E/AndroidRuntime( 9556):        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:107)
E/AndroidRuntime( 9556):        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1021)
E/AndroidRuntime( 9556):        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:959)
E/AndroidRuntime( 9556):        at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:108)
E/AndroidRuntime( 9556):        at com.facebook.react.ReactInstanceManager$ReactContextInitAsyncTask.doInBackground(ReactInstanceManager.java:225)
E/AndroidRuntime( 9556):        at com.facebook.react.ReactInstanceManager$ReactContextInitAsyncTask.doInBackground(ReactInstanceManager.java:203)
E/AndroidRuntime( 9556):        at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/AndroidRuntime( 9556):        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime( 9556):        ... 3 more.


and this is my setting in build.gradle 

dependencies {
    compile project(':react-native-google-places')
    compile project(':react-native-default-preference')
    compile project(':react-native-i18n')
    compile project(':react-native-vector-icons')
    compile project(':react-native-device-info')
    compile project(':react-native-maps')
    compile project(':react-native-web-image')
    compile project(':react-native-config')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"
    compile(project(':react-native-maps')) {
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    compile(project(':react-native-google-places')) {
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }

    compile 'com.google.android.gms:play-services-base:11.+'
    compile 'com.google.android.gms:play-services-maps:11.+'  // From node_modules
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

**Comment by tarheele** [comment]
You may be missing the places library in app/build.gradle

The troubleshooting section has guidance on this.

I have these related libraries in mine (may be more than is required):
```
   compile 'com.google.android.gms:play-services-base:+'
   compile 'com.google.android.gms:play-services-location:+'
   compile 'com.google.android.gms:play-services-places:+'  
   compile 'com.google.android.gms:play-services-maps:+'
   compile 'com.google.android.gms:play-services-gcm:+'
```

**Comment by tolu360** [comment]
Feel free to re-open if this is still an issue. Cheers!
