### ISSUE TITLE
Places details and photos ?

### ISSUE THREAD

**Issue by ebouJ** [tolu360/react-native-google-places#106]
@tolu360  
Thanks for this wonderful package brother. I need the places details and photos is it possible to get it with this package?

**Comment by ebouJ** [comment]
I used the web sdk and it works fine. I will go ahead and close this issue.

**Comment by shekharskamble** [comment]
@ebouJ - you used web sdk of google maps API?  can you share some example of how you got details? i need to show photos and rating as well...

**Comment by ebouJ** [comment]
const place = await RNGooglePlaces.openAutocompleteModal();
    let placeid = place.placeID;
    let placeDetails = await fetch(
      `https://maps.googleapis.com/maps/api/place/details/json?placeid=${placeid}&key=YOUR_API_KEY`
    );
    let json = JSON.parse(placeDetails._bodyText);
   console.log(json);

**Comment by tinashe96** [comment]
@ebouJ Hi I have used a similar approach and can get the photo object. How do you then display the returned photo?

**Comment by ebouJ** [comment]
Are you using redux or any state management library?

**Comment by tinashe96** [comment]
@ebouJ No I am using the regular state management.
My backend server returns the image returned by Google Place Photos. 
E.g. https://budgettrip.herokuapp.com/locationimage/-8.409518/115.188919

```
<Image
   style={{width: '100%', height: 300}}
   source={{uri: **not sure what to put here**}}
   resizeMode='cover'
/>
```

**Comment by ebouJ** [comment]
Well did you fetch the images object? Can you print it out let me see the object?

**Comment by tinashe96** [comment]
What is shown is what gets returned on success by Google. I assume it is the image in some sort of blob format perhaps, but I'm not very sure. How did you handle the returned image?

**Comment by ebouJ** [comment]
Share the part of your code that is responsible for fetching the photos.
Also after you get the photos object you need to loop on them and fetch them one by one. So it's very promise heavy. You need handle the async calls well.

**Comment by ebouJ** [comment]
that's the code I didnt have time to format it. I'm busy right now

`await Promise.all(
  json.result.photos.map(async (item, i) => {
    const photoRef = item.photo_reference;
    let Path =     `https://maps.googleapis.com/maps/api/place/photomaxwidth=400&photoreference=${photoRef}&            key='api_key'`;
    let res = await fetch(`${Path}`)
    obj.photo.push(res.url);
  })
);`

**Comment by tinashe96** [comment]
@ebouJ I have done this already and can fetch an image using its photoReference, Im just not sure how to handle the response and display it.

This is a snippet of my code which fetches the image.

```
var locationimage = {
        uri: 'https://maps.googleapis.com/maps/api/place/photo?photoreference=${photo_reference}&sensor=false&maxheight=1600&maxwidth=1600&key=${apiKEY}',
        headers: {
          'User-Agent': 'Request-Promise'
        }
      };

      rp(locationimage)
        .then(function(repos) {
          res.send(repos);
        })
        .catch(function(err) {
          // API call failed...
          res.send(JSON.stringify({ error: 'Could not get image' }));
        })

```

**Comment by tinashe96** [comment]
@farzd I believe RN supports blobs now. My problem was more related to [this](https://stackoverflow.com/questions/40051282/request-for-photo-on-google-places-api-returns-random-string-of-unicode-characte/40051372?noredirect=1#comment88660182_40051372)

Anyway, I've decided to use [Teleport's API](http://developers.teleport.org/api/getting_started/#photos_ua) instead. It has images for pretty much all major cities and also returns a web and mobile version of the images. Much more straight forward.
