### ISSUE TITLE
RNGooglePlaces.getCurrentPlace() hanging the app.

### ISSUE THREAD

**Issue by vishu-daffodil** [tolu360/react-native-google-places#108]
Hi,

I am using RNGooglePlace.getCurrentPlace() api to get current location in android. I am trying to show loader while get current places fetches the location. But the loader is not showing because The get get current places api is running on ui thread and the button is showing as being tapped while get current places is fetching data. Please help.

export function getCurrentPlace() {
    return dispatch => {
        dispatch(loadingStart());
        if (Platform.OS === 'android') {
            RNGooglePlaces.getCurrentPlace()
                .then((results) => {
                    dispatch(fetchCurrentLocation(results));
                })
                .catch((error) => {
                    dispatch(triggerGPSError());
                })
        } else {
            navigator.geolocation.getCurrentPosition(
                (position) => {
                    dispatch(fetchCurrentLocation({
                        latitude: position.coords.latitude,
                        longitude: position.coords.longitude
                    }));
                },
                (error) => {
                    dispatch(triggerGPSError());
                },
                { enableHighAccuracy: true, timeout: 20000, maximumAge: 1000 });
        }
    }
}

render() {
        console.log("this.props.state.loading", this.props.state.loading);
        return (
            <View style={styles.mainContainer}>
                {/* SearchView includes text input, header, title and hint of text input */}
                <SearchView
                    mainTitle={en.LOCATION}
                    bottomText={en.TEXT_INPUT_LOCATION_HINT}
                    textFieldPlaceholder={en.ENTER_A_LOCATION}
                    onHeaderLeftPress={this.closeScreen.bind(this)}
                    textFieldValue={this.state.searchValue}
                    onTextFieldChange={this.onTextFieldChange}
                    onClearPress={this.clearSearchValue}
                    leftIcon={ic_closeWhite}
                />
                <View style={{ flex: 1 }}>
                    {!this.props.state.noResult && this.renderSearchesView()}
                    {this.props.state.loading && <Spinner bgColor="transparent" />}
                    {this.props.state.noResult && <LocationSearchNoResult />}
                </View>
                <Toast ref={(ref) => this.toastRef = ref} />
            </View>
        );
    }

Console is showing correctly.

**Comment by pdruart** [comment]
Use RxJS for async call 👍

**Comment by hugows** [comment]
I agree with @vishu-daffodil : its kinda unusable like this, since there is no timeout option for getCurrentPlace.

This old "hack" works for me, but I'm not sure why:

```
        setTimeout(() => {
            RNGooglePlaces.getCurrentPlace()
                .then(results => this.setState({ loading: false, currentPlaceResults: results }))
                .catch(error => this.setState({ loading: false, error: error.message }));
        }, 0);
```

**Comment by hugows** [comment]
@pdruart How would RxJS help? Thanks.
