### ISSUE TITLE
Saved places

### ISSUE THREAD

**Issue by uditguru** [tolu360/react-native-google-places#111]
I have just a question, if this plugin allows us to have saved places of a user in the overlay?

**Comment by tolu360** [comment]
Need more clarifications about your question

**Comment by uditguru** [comment]
I want to know if we can fetch the saved places of the user that has been saved in google maps.
Eg. Home, Work etc

**Comment by tolu360** [comment]
Oh Ok, the underlying libraries do not provide such APIs. Have you considered own caching of frequently accessed places with `Redux` or something?

**Comment by uditguru** [comment]
I haven't tried it yet. I would check caching the data and revert  ASAP
