### ISSUE TITLE
react-native-google-places stops working and application crashes when upgrading to google play services v11.8.0

### ISSUE THREAD

**Issue by fidanoskimkd** [tolu360/react-native-google-places#116]
Hey, I just upgraded google play services version to 11.8.0 and the application crashes with error: 
/AndroidRuntime: FATAL EXCEPTION: Thread-4
Process: com.XXXX, PID: 32605
java.lang.AbstractMethodError: abstract method "com.google.android.gms.common.api.Api$zze com.google.android.gms.common.api.Api$zza.zza(android.content.Context, android.os.Looper, com.google.android.gms.common.internal.zzr, java.lang.Object, com.google.android.gms.common.api.GoogleApiClient$ConnectionCallbacks, com.google.android.gms.common.api.GoogleApiClient$OnConnectionFailedListener)"
at com.google.android.gms.common.api.GoogleApiClient$Builder.build(Unknown Source)
at 

How can we upgrade this library to use google play services v11.8.0 ?

**Comment by tlvenn** [comment]
@tolu360 any chance to update the lib with the latest GMS dependencies and bump the version ?

**Comment by tolu360** [comment]
Hi @tlvenn, got that on my todos for the week but first, got a couple PRs to work through before I get to it. See the [troubleshooting section](https://github.com/tolu360/react-native-google-places#on-android) of the README for a workaround to using **any version** of Google Play Services right away.

**Just replace**
```groovy
   compile project(':react-native-google-places')
```
**with**

```groovy
    compile(project(':react-native-google-places')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-places'
        exclude group: 'com.google.android.gms', module: 'play-services-location'
    }
    compile 'com.google.android.gms:play-services-base:11.8.0'
    compile 'com.google.android.gms:play-services-places:11.8.0'
    compile 'com.google.android.gms:play-services-location:11.8.0'
```
**in your `android/app/build.grade` file**. Then rebuild your project.

**Comment by tlvenn** [comment]
I assumed the API did change and it would require some modifications on your end...

**Comment by tolu360** [comment]
I know things work well till v 11.6.2, I have got a project currently using that, I haven't really tested against v 11.8.0. Try it out, report any issues, you can always degrade any time!
