### ISSUE TITLE
Cannot read property 'getAutocompletePredictions' of undefined

### ISSUE THREAD

**Issue by nikolas77380** [tolu360/react-native-google-places#118]
Hi. I need your help, I've tried all ways of install and linking library but every time I get the same error while trying to test getAutocompletePredictions outside of render method by the way) on Android it works but on IOS I'm stuck. Could you please help me with this issue?

**Comment by tolu360** [comment]
Feel free to re-open if you still have issues

**Comment by udayakanth1122** [comment]
This issue still exists. Can you please help in fixing this?
