### ISSUE TITLE
Invalid API key

### ISSUE THREAD

**Issue by wmonecke** [tolu360/react-native-google-places#120]
The package works fine for iOS but for android i get the error that the api key is invalid.
I have double-checked everything and I think I am doing something very stupid here.

In the instructions it says that I should put my API key here:

```
<meta-data
		android:name="com.google.android.geo.API_KEY"
		android:value="YOUR_ANDROID_API_KEY_HERE"/>
```

Should I put the API key in BOTH places: Where it says API_KEY and YOUR_ANDROID_API_KEY_HERE or ONLY in YOUR_ANDROID_API_KEY_HERE?

Sorry for the dumb question and thank you so much for making this package :)

**Comment by tolu360** [comment]
Hi Walter, just where it says YOUR_ANDROID_API_KEY_HERE and you should be good.
