### ISSUE TITLE
Cannot read property 'getCurrentPlace' of undefined

### ISSUE THREAD

**Issue by adityasonel** [tolu360/react-native-google-places#121]
I am getting this error 
`Cannot read property 'getCurrentPlace' of undefined`
while using
`RNGooglePlaces.getCurrentPlace()`
But when I am consoling `RNGooglePlaces.getCurrentPlace`, this is showing,

```
function getCurrentPlace() {
	return RNGooglePlacesNative.getCurrentPlace();
}
```

How to solve this error?

**Comment by tolu360** [comment]
Let me see how you are importing the library at the top of your file. Can it be that you imported `RNGooglePlaces` but you are trying to call `getCurrentPlace` off of `RNGooglePlacesNative` which is clearly not what you imported at the top of your file? `RNGooglePlacesNative` would be correctly `undefined` if that is the case.

You can show more code snippets from your component if you need more help.

**Comment by adityasonel** [comment]
I am importing as,
`import RNGooglePlaces from 'react-native-google-places';`

**Comment by adityasonel** [comment]
It's my whole code for this screen, actually I am trying to get a list of nearby places in `componentDidMount()` then showing it in a `FlatList`. But `RNGooglePlaces.getCurrentPlace()` is not working.

**Comment by tolu360** [comment]
The methods of this package all return promises, you should use them asynchronously. Try to do this:

```js
 async componentDidMount() {
        this.props.navigation.setParams({handleHeaderBack: () => this.onPressHeaderBack()});

await const currentPlace =  RNGooglePlaces.getCurrentPlace();    
console.log('rnplaces', currentPlace);
    }
```
Let me know if that works for you

**Comment by adityasonel** [comment]
Now, I am getting this error.

```
TypeError: Cannot read property 'getCurrentPlace' of undefined
    at RNGooglePlaces.getCurrentPlace (blob:file:///f2feeb41-47cf-4777-8c64-d340e19e5d82:113817:32)
    at SelectLocationScreen.componentDidMount$ (blob:file:///f2feeb41-47cf-4777-8c64-d340e19e5d82:111590:76)
    at tryCatch (blob:file:///f2feeb41-47cf-4777-8c64-d340e19e5d82:42095:19)
    at Generator.invoke [as _invoke] (blob:file:///f2feeb41-47cf-4777-8c64-d340e19e5d82:42268:24)
    at Generator.prototype.(anonymous function) [as next] (blob:file:///f2feeb41-47cf-4777-8c64-d340e19e5d82:42138:23)
    at tryCatch (blob:file:///f2feeb41-47cf-4777-8c64-d340e19e5d82:42095:19)
    at invoke (blob:file:///f2feeb41-47cf-4777-8c64-d340e19e5d82:42171:22)
    at blob:file:///f2feeb41-47cf-4777-8c64-d340e19e5d82:42199:13
    at tryCallTwo (blob:file:///f2feeb41-47cf-4777-8c64-d340e19e5d82:41433:7)
    at doResolve (blob:file:///f2feeb41-47cf-4777-8c64-d340e19e5d82:41597:15)
```

**Comment by tolu360** [comment]
It says `RNGooglePlaces` is `undefined`. What platforms are you working with and how did you create or start your project? 

Also note that projects created with `expo` or `crna` (this can be ejected though)  are currently not supported

**Comment by adityasonel** [comment]
Nope, I created project with `react-native init ProjectName`.

**Comment by tolu360** [comment]
Have you installed the Google libraries via CocoaPods?

Did you forget to run `react-native link react-native-google-places` or manually link the package with your project?

Does any other method in this package work in your project?

**Comment by adityasonel** [comment]
Nope, only `RNGooglePlaces.getCurrentPlace` syntax working. That give this on console,

```
function getCurrentPlace() {
				return RNGooglePlacesNative.getCurrentPlace();
			}
```

But I need that this work, `RNGooglePlaces.getCurrentPlace()`???

**Comment by tolu360** [comment]
First I need you to answer all the questions, then I'd update a sample app and send you the link so you can see if you can reproduce your issues on the sample app.

**Comment by adityasonel** [comment]
Ok, I am waiting.

**Comment by tolu360** [comment]
Find the sample app at https://github.com/tolu360/TestRNGP and follow the setup guides to run it on your machine

**Comment by adityasonel** [comment]
Yup, it's working. I will check again my project.
