### ISSUE TITLE
openAutocompleteModal didn't show any result

### ISSUE THREAD

**Issue by kriptonhaz** [tolu360/react-native-google-places#124]
I tried with place picker but the autocomplete modal didn't show any result, I've enable the api on google console and put it on the manifest. I tried with the example project and replace with my api key and it's work, but why it didn't work on mine? any hint? thanks

**Comment by tolu360** [comment]
Oh hi! Just compare and contrast the sample app with your own project, I cannot claim I know what is wrong with your project.
