### ISSUE TITLE
Remove place icons - point of interests

### ISSUE THREAD

**Issue by NikoMontana** [tolu360/react-native-google-places#125]
Hi,

I need this lib for determining a user location and let the user pick a new location. 
I dont need the place icons (little red once), is this possible?

I found this: https://developers.google.com/maps/documentation/ios-sdk/hiding-features

But unfortunately I cannot code iOS, so I dont know where to put the JSON file and where to call `GMSMapStyle`

**Comment by tolu360** [comment]
Hi @NikoMontana, you have referenced `map styling guides` and those apply to styling stand-alone Google Maps, not the Place Picker or Autocomplete Modal.

For fine-grained customisations, I would recommend you build your own maps/UIs using the `react-native-maps` library (lets you customize map styles) combined with an auto-complete search-bar/input using the `getAutocompletePredictions` API provided by this library. See [the section of the README dedicated to doing just this](https://github.com/tolu360/react-native-google-places/blob/master/README.md#using-your-own-custom-uiviews).

Also see the sample search input implemented in [sample app](https://github.com/tolu360/TestRNGP) for more contexts.
