### ISSUE TITLE
Troubleshooting tip - add to wiki

### ISSUE THREAD

**Issue by hugows** [tolu360/react-native-google-places#126]
Hello, thanks for the library - looks promising. 

I'm still installing the library, but noticed that my `android/build.gradle` missed something like:

```
        maven {
            url "https://maven.google.com" 
        }   

```
while the one in the sample project TestRNGP had it! 
I think because of this the play-services jar were not being downloaded, and I was getting a nasty error!

**Maybe this could go in the install instructions?** :sweat_smile:

**Comment by tolu360** [comment]
Good call, perhaps a quick PR would be great next time? Thanks!
