### ISSUE TITLE
Place-picker modal close immediately on IOS

### ISSUE THREAD

**Issue by VKGraphics** [tolu360/react-native-google-places#127]
![mapissue](https://user-images.githubusercontent.com/24429336/38867609-1a68ceb6-4262-11e8-8c1a-03bd331fdfb5.gif)

**Comment by SalmanTariq** [comment]
How did you solve it? Encountering the same issue.

**Comment by VKGraphics** [comment]
Place Api set Restrictions  
![screen shot 2018-04-18 at 9 08 20 pm](https://user-images.githubusercontent.com/24429336/38942524-a6eff4a0-434c-11e8-8445-ce028ff65ad7.png)

**Comment by RameshkrishnanV** [comment]
i added the restrictions but still i'm facing this issue. please help me

**Comment by VKGraphics** [comment]
please give me screenshot of fill details N Application Restriction .
