### ISSUE TITLE
Application crashes after linking the plugin

### ISSUE THREAD

**Issue by KirankumarDafda** [tolu360/react-native-google-places#128]
# Environment

OS : Window 7 (64)
react : 16.0.0-alpha.12
react-native : ^0.50.3

# Issue
Everything is working fine until I installed this plugin, after installing and linking the plugin application keeps crashing, if I again uninstall plugin everything works fine.

![screenshot_1524055687](https://user-images.githubusercontent.com/19833506/38933076-9f1721a2-4335-11e8-97e0-381791e39482.png)

**Comment by tolu360** [comment]
You most likely have other libraries importing other/conflicting versions of the Google Play Services in your project. What other libraries are using in your app?

To resolve this, what you need to do is ensure all libraries use the same version of the Google Play Services.

See [how to configure the version of the Google Play Services](https://github.com/tolu360/react-native-google-places/blob/master/README.md#configuring-versions-for-dependencies-optional-on-android-only) for your project in the README. Also try to run the [sample app](https://github.com/tolu360/TestRNGP) on your machine.

**Comment by hugows** [comment]
This also happened to me even on a "empty project" (didn't even use react-native-google-places yet, only installing everything):

I had already done this change:

```
android/app/bulid.gradle
    // compileSdkVersion 25
    // buildToolsVersion "25.0.1"
    // from placeslib
    compileSdkVersion 26
    buildToolsVersion "26.0.1"   
```

but was missing this other one:


```
android/bulid.gradle
ext {
    compileSdkVersion   = 25
    targetSdkVersion    = 25
    buildToolsVersion   = "25.0.2"
    supportLibVersion   = "25.0.2"
    googlePlayServicesVersion = "11.6.2"
    androidMapsUtilsVersion = "0.5+"
}
```

**Comment by tolu360** [comment]
Hi Again,

If you are not using custom versions for the dependencies, you do not need to add the optional version configurations as stated in the README, just use the default versions. You should be OK just adding the following in your `android/app/build.gradle` file:

```groovy
compile project(':react-native-google-places')
```
And make sure you have covered the setup guides under the [linking section](https://github.com/tolu360/react-native-google-places#manual-linking-with-your-project-android).

If your project builds correctly but still crashes on launch, then try to get the `stacktrace` from `logcat` either from running `adb logcat` or `react-native log-android` or just copying the content of the console in the Android Studio immediately before your app crashes.

**Comment by VinceBT** [comment]
Try removing the exclude rules and add this in your ```build.gradle```
```
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.getRequested().getGroup() == 'com.google.android.gms') {
            details.useVersion('12.0.1')
        }
    }
}
```
Replace ```12.0.1``` by the desired version
