### ISSUE TITLE
Seperate Address Component

### ISSUE THREAD

**Issue by nzrin** [tolu360/react-native-google-places#131]
How to get seperate response in Address without returning everything in 1 single string such as Street,Postal Code, Country.

Is there any method to only retrieve Postal Code?

**Comment by tolu360** [comment]
The `addressComponent`, from which you can get the `postal_code`, is already a property on the response you receive on `iOS`, e.g. 

```js
{ name: 'Twitter HQ',
  website: 'https://twitter.com/',
  longitude: -122.4166041,
  address: '1355 Market St #900, San Francisco, CA 94103, USA',
  addressComponents: 
   { locality: 'San Francisco',
     subpremise: '900',
     administrative_area_level_1: 'California',
     country: 'United States',
     postal_code: '94103',
     street_number: '1355',
     neighborhood: 'South of Market',
     administrative_area_level_2: 'San Francisco County',
     route: 'Market Street' },
  latitude: 37.776796399999995,
  placeID: 'ChIJWUSPbJyAhYARpQ8FtdnWDrE',
  phoneNumber: '+1 415-222-9670' }
```

On Android, the SDK do not provide that yet. A very [old issue is still open on Google Issue Tracker](https://issuetracker.google.com/issues/35828699) for it, you can check that up for context.

**Comment by nzrin** [comment]
`.then((place) => {
var matches = place.address.match(/\b\d{5}(-\d{4})?\b/);
if(matches == null){
//ZIPCODE NOT FOUND
}else{
//ZIPCODE FOUND
console.log('Zipcode :'+matches[0]);
}
})
.catch(error => console.log(error.message));
}`

**Comment by nzrin** [comment]
`.then((place) => {
var matches = place.address.match(/\b\d{5}(-\d{4})?\b/);
if(matches == null){
//ZIPCODE NOT FOUND
}else{
//ZIPCODE FOUND
console.log('Zipcode :'+matches[0]);
}
})
.catch(error => console.log(error.message));
}`

This is the sample.

**Comment by nzrin** [comment]
I would like to share the solution that works for me. Simple way to fetch zipcode from addresscomponent on Android. 

```ruby
.then((place) => {
  var matches = place.address.match(/\b\d{5}(-\d{4})?\b/);
  if(matches == null){
    //ZIPCODE NOT FOUND
  }else{
    //ZIPCODE FOUND
    console.log('Zipcode :'+matches[0]);
  }
  })
  .catch(error => console.log(error.message));
}
```

**Comment by dianazzz** [comment]
how to fetch current place city name in version 3 ? I got placeID, coordinates, address(Full address as string) from currentPlaces(). Now address component is not present in the response.

**Comment by ggdegreat** [comment]
> 
> 
> The `addressComponent`, from which you can get the `postal_code`, is already a property on the response you receive on `iOS`, e.g.
> 
> ```js
> { name: 'Twitter HQ',
>   website: 'https://twitter.com/',
>   longitude: -122.4166041,
>   address: '1355 Market St #900, San Francisco, CA 94103, USA',
>   addressComponents: 
>    { locality: 'San Francisco',
>      subpremise: '900',
>      administrative_area_level_1: 'California',
>      country: 'United States',
>      postal_code: '94103',
>      street_number: '1355',
>      neighborhood: 'South of Market',
>      administrative_area_level_2: 'San Francisco County',
>      route: 'Market Street' },
>   latitude: 37.776796399999995,
>   placeID: 'ChIJWUSPbJyAhYARpQ8FtdnWDrE',
>   phoneNumber: '+1 415-222-9670' }
> ```
> 
> On Android, the SDK do not provide that yet. A very [old issue is still open on Google Issue Tracker](https://issuetracker.google.com/issues/35828699) for it, you can check that up for context.

It's already release for Android since 1st April.

https://developers.google.com/places/android-sdk/releases#april_1_2019_-_v110
