### ISSUE TITLE
The "Select" text isn't capitalised

### ISSUE THREAD

**Issue by davidvuong** [tolu360/react-native-google-places#132]
![screenshot_20180507-094417_google play services](https://user-images.githubusercontent.com/1312550/39679383-03160a2a-51e0-11e8-9711-f208707b3c1c.jpg)

When I'm emulating on a Pixel 2, it shows as capitalised however, when I build an APK and install it onto my device (Samsung Galaxy S8) it doesn't show up as capitalised.

It's a minor issue and I'm not sure where this is caused.

**Comment by tolu360** [comment]
This is most likely a phone text setting.
