### ISSUE TITLE
openPlacePickerModal filter by establishment type.

### ISSUE THREAD

**Issue by vasilycrespo** [tolu360/react-native-google-places#133]
Hi, first of all thanks for the effort building this plugin. I'm am trying to figure out if it is possible to filter the results listed when using the openPlacePickerModal method. I would like to list for example only establishments of type "restaurants" or "cafe". Those categories are listed on the places documentation:

https://developers.google.com/places/supported_types

Not sure if this is implemented yet, I can find anything related to this on the documentation. 

I tried something like this with no success:

```
RNGooglePlaces.openPlacePickerModal({
        type: 'establishment',
        types: ['restaurant', 'cafe'],
        country: 'US',
        radius: 10,
        latitude,
        longitude
})
```

Also attempt to add the restaurant and cafe as string with no success. Thanks

**Comment by tolu360** [comment]
You are welcome and thanks for the kind words. The supported [place type filters are as stated in the README](https://github.com/tolu360/react-native-google-places#optional-parameters) - I am not sure you can pass an array of types to the underlying SDKs. See `Table 3` on the link you referenced.

Under the hood, the supported `type filter` on both `platforms` is an `**enum**`, not a list/array or dictionary where the value can **only** be one of `**geocode, address, establishment, regions**, and **cities**`. The other values you are trying to pass in, may have been categorised under these 5.

Please check the Google docs for [Android SDK](https://developers.google.com/places/android-sdk/supported_types#table3) & [iOS SDK](https://developers.google.com/places/ios-sdk/supported_types#table3) for more context. Cheers
