### ISSUE TITLE
Header search path when using Pods for React Native

### ISSUE THREAD

**Issue by jpapillon** [tolu360/react-native-google-places#136]
I'm using pods for the react-native library itself and I've faced the issue that some `#import <React/...>` files were not found from this project while building. Would it be possible to add this to the `Header Search Paths` to let it find the header files in the Pods?
`${SRCROOT}/../../../ios/Pods/Headers/Public` ---> Recursive

Thanks!

**Comment by tolu360** [comment]
I would take a look at it as soon as possible, a PR may be faster though. Cheers
