### ISSUE TITLE
Different data depending on OS that makes request?

### ISSUE THREAD

**Issue by wmonecke** [tolu360/react-native-google-places#137]
I can't debug on android because I have yet to install the debug cert for google places. 

However, I think that the request returns different data structures depending if the request is made by iOS or android.  Is this true? This has been causing a headache for a while.

**Comment by tolu360** [comment]
You can find sample responses in the README and they are consistent across both platforms. Also, you can play with the [sample app](https://github.com/tolu360/TestRNGP) to get a better feel of all use-cases.

Closing this now but feel free to re-open if necessary.

**Comment by nickbyte** [comment]
Addresscomponents is missing when you call from Android

**Comment by steven-mercatante** [comment]
Running into the same problem as @nickbyte -  the response is missing `addressComponents` on Android, but it's present on iOS.
