### ISSUE TITLE
Error when try to trigger openPlacePickerModal (iOS)

### ISSUE THREAD

**Issue by nzrin** [tolu360/react-native-google-places#138]
Got this error on iOS: 

<img width="462" alt="screen shot 2018-05-24 at 2 50 12 pm" src="https://user-images.githubusercontent.com/36392666/40469076-f35e2236-5f61-11e8-8986-08d627b5352a.png">

It works fine on Android though. 

Please help. Thank you!

**Comment by tolu360** [comment]
What params are you passing to the `openPlacePickerModal()` method? Can you show some code snippets here?

**Comment by nzrin** [comment]
Okay. Here's my code : 

```
openSearchModal() {

  RNGooglePlaces.openPlacePickerModal()
  .then((place) => {
  
    this.setState({
       locName: place.name,
       locLatitude: place.latitude,
       locLongitude: place.longitude
    });
    
  })

 .catch(error => console.log(error.message));
 
}
```

**Comment by BaderSerhan** [comment]
Any update on this issue? I'm using the sample code as it is from the `readme` and getting this.

**Comment by tolu360** [comment]
Please consider getting on the latest release, would only be supporting that now - please see #198
