### ISSUE TITLE
Modal instantly closes on Android

### ISSUE THREAD

**Issue by VinceBT** [tolu360/react-native-google-places#140]
Android version: 8
RN Version: 0.54.0-rc.3
RNGP Version : 2.5.0
Play Services Version: 12.0.1

Error:
```
Status{statusCode=ERROR, resolution=null}
```

The modal opens and instantly closes without any further information

**Comment by darkmantle** [comment]
I have the same today on iOS, with no errors showing.

**Comment by GoNishant** [comment]
@VinceBT facing the same issue as The modal opens and instantly closes without any further information.
Is there any solution do you get?
Thanks...

**Comment by darkmantle** [comment]
On iOS I fixed this by enabling the Google Places for iOS SDK, which it seems I had not yet done.

**Comment by VinceBT** [comment]
All APIs are enabled for me and still I get the bug

**Comment by tolu360** [comment]
@VinceBT, does the modal just close or does your app crash instantly when you launch the app?

**Comment by VinceBT** [comment]
The modal opens then closes and I get the error.

**Comment by tolu360** [comment]
The `error` is vague, cannot make anything of it. Is that what you get from logging `error.message`? Can you get the stack trace from Android? Either get `logCat` from the console on Android Studio or run `react-native log-android` on your terminal before you launch the modal and provide the output here.

I am also interested in seeing how you are setting up to use Play Services v12.

**Comment by VinceBT** [comment]
The error I get with android-log is the one and only line that I put as first message of this issue
I configure my packages with the method I explain in https://github.com/tolu360/react-native-google-places/issues/128#issuecomment-393527673

**Comment by tolu360** [comment]
Can you try [option 1 from dependencies config](https://github.com/tolu360/react-native-google-places#configuring-versions-for-dependencies-optional--for-android-only) in the README, setting `googlePlayServicesVersion` to your desired version and removing your additions in `build.gradle` ?

Something like: 

```groovy
ext {
  googlePlayServicesVersion = "12.0.1"
}
```
ADB logs are usually very verbose (not the one line you have provided) and can tell what is happening in the android not JS world. You can also run `adb logcat` on your terminal while your app is running.
Also, have you played with the [sample app](https://github.com/tolu360/TestRNGP) at all? Can you reproduce this issue on it?

In the absence of a detailed error log, I cannot help any further. Cheers

**Comment by VinceBT** [comment]
```06-01 19:47:39.952  4839 28283 W Places  : {"code":403,"errors":[{"reason":"forbidden","domain":"global","message":"The supplied API key is not configured for use from this client."}]}```
The API is enabled and the key is estricted to my package, which is working with react-naitve-maps currently
