### ISSUE TITLE
Wont work after './gradlew assembleRelease'

### ISSUE THREAD

**Issue by wmonecke** [tolu360/react-native-google-places#141]
Hi,

The component works great when I run it on the simulator or through `react-native run-android --variant=release`. However, once I assembled for release it wont look up places at all (no results / autocomplete). Anything I am missing here? I dont even know how to debug a production build.

Thank you!!

**Comment by tolu360** [comment]
Hey,

Do you have Android Studio running and have `Developer Options` & `USB Debugging` enabled on the device you are testing with? You may still be able to pick up on some logs in the console in Android Studio.

Also, it seems Google wants you to complete your billing account profile before going live these days.

Also if you have `Application Restrictions` on  your API credentials, please ensure you have added the right package name and release SHA-1 signing-certificate fingerprint to the credentials on the [Google Console](https://console.developers.google.com/apis/credentials).

In any case, this issue looks very API key-related, that's where I'd look first. Cheers

**Comment by wmonecke** [comment]
@tolu360 
Hey thanks for the answer! :) Google re-signs the application once you upload the app to the google playstore. I found the valid SHA-1 fingerprints in the Google Play Console.
