### ISSUE TITLE
Invalid Key error in ios

### ISSUE THREAD

**Issue by kapilkarda** [tolu360/react-native-google-places#146]
Hello,

I am trying to install google-place library with the method but I am always getting the invalid key error.

Can someone please help me with that ?

![screen shot 2018-06-08 at 7 37 17 pm](https://user-images.githubusercontent.com/4336836/41162434-7499bca0-6b53-11e8-8a93-773563bc9112.png)

**Comment by tolu360** [comment]
See how to set up keys in your `AppDelegate.m` in the README.
