### ISSUE TITLE
Get Error When Open SearchModal (Auto Close With Error)

### ISSUE THREAD

**Issue by vjijardar** [tolu360/react-native-google-places#148]
Hello,
I'm Got error when I'm click to open search modal the google search Modal is Open and Auto close within a sec. and in console get error is 

**Status{statusCode=ERROR, resolution=null}**

**Environment:
  OS: Windows 10
  Node: 8.9.4
  Yarn: 1.2.0
  npm: 6.0.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1**

**Comment by vjijardar** [comment]
Sorry I'm Issue

**Comment by harikanammi** [comment]
hi @vjijardar, how to fix this issue...I am also getting same error. Please give me answer for this issue.
