### ISSUE TITLE
Receive the full api response

### ISSUE THREAD

**Issue by ddeanto** [tolu360/react-native-google-places#15]
Is there a way to get the full response instead of a squashed version of it? For example, I need to parse out the street, city, zip, and country all separately. Thanks so much!

**Comment by ddeanto** [comment]
To be clearer, right now the response object is this:

```
{ 
    placeID: "ChIJZa6ezJa8j4AR1p1nTSaRtuQ", 
    website: "https://www.facebook.com/", 
    phoneNumber: "+1 650-543-4800", 
    address: "1 Hacker Way, Menlo Park, CA 94025, USA", 
    name: "Facebook HQ",
    latitude: 37.4843428,
    longitude: -122.14839939999999
}
```

But I also would like ADDITIONAL fields like this:

```
{
    position: {lat, lng},
    formattedAddress: String, // the full address 
    feature: String | null, // ex Yosemite Park, Eiffel Tower 
    streetNumber: String | null,
    streetName: String | null,
    postalCode: String | null,
    locality: String | null, // city name 
    country: String, 
    countryCode: String
    adminArea: String | null
    subAdminArea: String | null,
    subLocality: String | null
}
```

**Comment by ddeanto** [comment]
It looks like the fields I listed above are obtained through Google Maps Geocoding API. The only fields available for Google Places API is listed [here](https://developers.google.com/places/android-api/place-details)

**Comment by tolu360** [comment]
Spot on @ddeanto, but have you checked the other fields exposed via the `addressComponents` key on the iOS response? But that is exposed only on `iOS`, incase it helps. Cheers!

**Comment by ddeanto** [comment]
I haven't checked since I am working on a specifically Android project - but I am sure I will be doing an iOS project soon so good to know!

**Comment by tolu360** [comment]
Hi @ddeanto, I stumbled on this [feature request](https://code.google.com/p/gmaps-api-issues/issues/detail?id=10019), may be it can be implemented sometime soon. Cheers!
