### ISSUE TITLE
getCurrentPlace results in Api error Android (also in example)

### ISSUE THREAD

**Issue by svengiebel** [tolu360/react-native-google-places#151]
First of all, thanks for the package! ⭐️ 

Currently i get an error in my application and in your example app (**Only in Android**):  
When calling the `RNGooglePlaces.getCurrentLocationPlace()` method i get the following:

`{ [Error: Error making places detection api call: ERROR] framesToPop: 1, code: 'E_PLACE_DETECTION_API_ERROR' }`

Everything else is working without any problems. I also checked the permissions for my API Keys.

iOS is working great, so it has to be something with the keys?

**Comment by tolu360** [comment]
Try it an actual android device and let me know if the issue still persists.

**Comment by svengiebel** [comment]
I was testing on an actual android device. its a Samsung Galaxy 4 with **Android 7.0**. I also tested it quickly with a Pixel2 and latest firmware. But i dont have that one available at the moment.

**Comment by tolu360** [comment]
I see, would look further into this issue and get back to you, but in the meantime, I pulled in a PR so make sure you update to `v2.5.2`

**Comment by Transfusion** [comment]
Getting this error with `v2.5.2`, Xiaomi Mi 6, Android 8.0.0, react-native 0.55.4, `compileSdkVersion 23`, `buildToolsVersion "23.0.1"`, `com.android.support:appcompat-v7:23.0.1`, going into the catch block of the Promise returned by `RNGooglePlaces.getCurrentPlace()`; `Error: Error making places detection api call: ERROR`

**Comment by aayushiyadav007** [comment]
Please ensure your device GPS location is on and above Lollipop version ACCESS_FINE LOCATION permission should be enable, because it worked for me.

**Comment by abdullateef97** [comment]
@tolu360 I'm having the same issue, how do i fix this. Thanks

**Comment by tolu360** [comment]
Please consider the latest beta release that uses the new Google SDK on Android, please see #198
