### ISSUE TITLE
open place picker modal keep on closing after updating api key also

### ISSUE THREAD

**Issue by RameshkrishnanV** [tolu360/react-native-google-places#152]
Hi 

    RN 0.55
    google places:2.5.2
    google service : 11.+

    Open place picker modal keep on closing, so i changed the google api key and added restriction but still i'm facing this issue, no error i m getting

**Comment by irokhes** [comment]
@RameshkrishnanV any luck with that? I got the same error. the modal keep closing all the time

**Comment by RameshkrishnanV** [comment]
Yeah. I created new API key from Google maps. And I enabled all the
services so it started working.
