### ISSUE TITLE
Get Current Location suggest on Open Autocomplete Modal

### ISSUE THREAD

**Issue by jamesrod817** [tolu360/react-native-google-places#153]
Is there a way to enable a Current Location suggestion on the AutoComplete Modal? I don't see anything in the ReadMe that suggests we can do this? If not, it'd be helpful to have.

**Comment by rubaktechie** [comment]
Need Current location Suggestion in openAutocompleteModal

**Comment by tolu360** [comment]
Consider building own UIs - that allows for any number of customizations. See the README and the sample app!
