### ISSUE TITLE
undefined is not an object (evaluating 'RNGooglePlacesNative.openAutocompleteModal')

### ISSUE THREAD

**Issue by dillonfromdallas** [tolu360/react-native-google-places#155]
Hi all!

Went through the install process twice.

Once via `react-native link`, and the second following the install instructions manually.

In both instances, I would try to load the openSearchModal piece, just so I could see what it looked like integrated into my project. However, my test device (iOS) always showed the error above.

I've read through some previous issue tickets, but all seem to be related to Android fixes, and none for iOS - or perhaps I've misread them.

How can I get this back up and running?

Cheers!

Dillon

**Comment by tolu360** [comment]
Please re-install again, following the README more carefully. The error shows that installation was not completely done.
