### ISSUE TITLE
Cocoapods conflict with react-native-maps

### ISSUE THREAD

**Issue by simonbuerger** [tolu360/react-native-google-places#156]
Has anyone been able to get this to work alongside react-native-maps on the same project? I'm getting a version conflict on the GoogleMaps pod - GooglePlaces pod depends on 2.7.0 and react-native-maps depends on 2.5.0

**Comment by reepias** [comment]
I have this same issue.

If use GooglePlaces 2.5.0 it cannot read property, but android it work.

Demo
https://github.com/reepias/taxiguber

![simulator screen shot - iphone x - 2018-07-19 at 16 05 08](https://user-images.githubusercontent.com/35448088/42933411-ea7922b8-8b6e-11e8-8662-73d8f2c4a491.png)

**Comment by tolu360** [comment]
You can always ensure both libraries are using same versions as @reepias mentioned. However, only the latest version, 3.0.3+ are supported on the latest beta release of this package. See #198, if you wish to update - almost compulsory on Android anyway!
