### ISSUE TITLE
getAutocompletePredictions should return more than 5 places.

### ISSUE THREAD

**Issue by lunvjp** [tolu360/react-native-google-places#159]
So currently this plugin works well and you did a good job. However, I don't know it just displays 5 items after I search succesfully with this function.
I see in my Google Maps with the same "Search Input", there are more results than this API. Let me know if it's not clear enough for you guys. Thanks

**Comment by alexpchin** [comment]
I believe this is due to the Google Places API only returning 5 results... https://developers.google.com/places/web-service/autocomplete

**Comment by lunvjp** [comment]
Cool. It was a long time I was using this stuff with my Map app, will check it later. Thanks.

**Comment by tolu360** [comment]
It should and does return more than 5 results depending on the search query.
