### ISSUE TITLE
Request: Specify location when opening place picker modal

### ISSUE THREAD

**Issue by jamesholcomb** [tolu360/react-native-google-places#16]

**Comment by tolu360** [comment]
Hello @jamesholcomb, I may have misread your request here but I don't think it is a feature supported by the underlying SDKs. It also looks like that would be defeating the purpose of the `Google PlacePicker` in the first place - the picker defaults to the device's current location when you first launch it, I think this is a sensible default, and helps you to pick a place you know but whose `latlng` coordinates you don't necessarily know, right?

If you already know the `latlng` and the `physical address` of a place, there would be no need to use the picker, you'd only need to display a `map` with a `pin` at your place of interest.

Please let me know if have misread your request or point me to the feature on the underlying SDK docs. Cheers.

**Comment by jamesholcomb** [comment]
`GMSPlacePickerConfig` can specify a viewport.

https://developers.google.com/places/ios-api/placepicker

The use case relates to editing the location for an existing calendar event.  The picker always defaults to their location, but their location may be nowhere near the location of the event they are editing.

**Comment by tolu360** [comment]
Oh I see, so you are asking that I add `GMSCoordinateBounds` object defining the initial rectangular area that the place picker's map must show and centered on an initial `latlng` you'd specify? 

Whilst this, clearly, won't be the use case for most users, I think I can find a way to work this into the next release.

**Comment by jamesholcomb** [comment]
👍

**Comment by tolu360** [comment]
Hi @jamesholcomb - `RNGooglePlaces.openPlacePickerModal({latitude: 6.44301, longitude: 3.44661})` is now possible in `1.0.6` and `2.0.6`. Check the README for other changes. I would allow you close the issue when you've given it a spin.

Cheers!

**Comment by jamesholcomb** [comment]
I tested this today and it does indeed set the viewport centered on the lat/long.
