### ISSUE TITLE
Make it possible to specify fields when pick up a place from Autocomplete results because of the new Price System 

### ISSUE THREAD

**Issue by kidmysoul** [tolu360/react-native-google-places#160]
Hey , thank you for your awesome library.  I like it and used it in my app very well. 

But as Google has published the [new price system](https://cloud.google.com/maps-platform/pricing/sheet/)  of  Google Map Platform, to pick up a place from Autocomplete results, it will cost unnecessary money  for developers those don't want some especial information for a place like opening_hours, website, price_level, rating, review....

If i can  specify only basic fields for picking a place ,it will cost a little cheaper.

As described in the [google official article](https://developers.google.com/maps/billing/understanding-cost-of-use):

> SKU: Autocomplete (included with Places Details) – Per Session
An Autocomplete (included with Places Details) – Per Session SKU is charged for an Autocomplete session that includes a Places Details request. The autocomplete request is free, and the subsequent Places Details call gets charged based on regular Places Details pricing (described below).

> A Places Details request generates Data SKUs (Basic, Contact, and/or Atmosphere) – depending on the fields that are specified in the request. If you do not specify fields in the Place Details request, all Data SKUs are triggered (Basic, Contact, and Atmosphere). To avoid paying for data that you don't need, call Autocomplete.setFields() to specify only the place data that you will use.

and this is my app costs from June, 1 
<img width="969" alt="2018-07-20 16 18 16" src="https://user-images.githubusercontent.com/15664045/42990490-bdbfdd28-8c3d-11e8-8ba0-b72ca03fcdbb.png">

the Atmosphere Data and Contact Data which are unnecessary for me cost a lot which is so painful for a app that hasn't make money yet.

**Comment by tylercb** [comment]
It is in the documentation: 

https://developers.google.com/maps/documentation/javascript/places-autocomplete#add_autocomplete

**Comment by tylercb** [comment]
It is in the documentation and in the example, you have to use Autocomplete.setFields():

> autocomplete.setFields(['address_components', 'geometry', 'icon', 'name']);

https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete

> By default, when a user selects a place, autocomplete returns all of the available data fields for the selected place, and you will be billed accordingly. Use Autocomplete.setFields() to specify which place data fields to return. Read more about the PlaceResult object, including a list of place data fields that you can request.



https://developers.google.com/maps/documentation/javascript/places-autocomplete#get_place_information

This is the list of available fields: https://developers.google.com/maps/documentation/javascript/reference/3.exp/places-service#PlaceResult

**Comment by kidmysoul** [comment]
@tylercb So how to use setFields for this library? RNGooglePlaces.Autocomplete.setFields()?

**Comment by kidmysoul** [comment]
@kknd113 
Does RNGooglePlaces have an interface called "Autocomplete" ?
RNGooglePlaces Only have methods which almostly are all Promise.

<img width="660" alt="2019-01-14 18 43 42" src="https://user-images.githubusercontent.com/15664045/51105461-5bd7ae80-182c-11e9-80ef-68389ebb6a13.png">

**Comment by kidmysoul** [comment]
OK,　I reviewed my google api console again and found that Atmosphere Data and Contact Data Requests were not called by this library but a "javascript map http call"

and for native android sdk(just this library), it costs almost nothing(?).

**Comment by tolu360** [comment]
This has been added to the latest beta release, please see #198 to get started.
