### ISSUE TITLE
Google Play Services is not available

### ISSUE THREAD

**Issue by matthewbennett** [tolu360/react-native-google-places#161]
Everything works fine on IOS. On Android I get this error no matter what I do. I have tried using version 10 for gms and I have tried using '+'. Not sure if I'm missing something? 

dependencies {
    compile project(':react-native-google-places')
    compile project(':react-native-splash-screen')
    compile project(':react-native-autogrow-textinput')
    compile project(':react-native-image-picker')
    // compile project(':react-native-maps')
    compile(project(':react-native-maps')){
        exclude group: 'com.google.android.gms'
    }
    compile project(':react-native-linear-gradient')
    compile project(':react-native-vector-icons')
    compile project(':react-native-fbsdk')
    compile ('com.google.android.gms:play-services-base:11.8.0') {
         force = true;
    }
    compile ('com.google.android.gms:play-services-maps:11.8.0') {
         force = true;
    }
    compile ('com.google.android.gms:play-services-places:11.8.0') {
         force = true;
    }
    compile ('com.google.android.gms:play-services-location:11.8.0') {
        force = true;
    }
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:26.0.1'
    compile 'com.facebook.react:react-native:+'
    // From node_modules
}

**Comment by CodeReadyCode** [comment]
Check you Simulator configuration 
Should be like this

![image](https://user-images.githubusercontent.com/17796414/43527959-21a8c908-95a8-11e8-8f8c-c8f2c4334789.png)

**Comment by matthewbennett** [comment]
its not a device/emulator issue.

**Comment by nickmccomb** [comment]
Are you using a device or emulator?  Might not have Google Play Services installed on your emulator
https://stackoverflow.com/questions/29429727/android-google-play-services-not-working-on-the-emulator

**Comment by nickmccomb** [comment]
Are you using a device or emulator? Might not have Google Play Services installed on your emulator
https://stackoverflow.com/questions/29429727/android-google-play-services-not-working-on-the-emulator

**Comment by tolu360** [comment]
Consider getting on the latest beta release, Google Play Services is no longer an issue, see #198
