### ISSUE TITLE
Places photo request

### ISSUE THREAD

**Issue by nickmccomb** [tolu360/react-native-google-places#163]
Is there any way to use the Google Places Photos service for iOS yet?  I can't see any updates for iOS in the Places branch.  Any ETA?

**Comment by nickmccomb** [comment]
If not, i need it in my project so i'll figure it out for iOS and Android and do a PR in the next few weeks

**Comment by thomasw** [comment]
Place Photos support is discussed over in https://github.com/tolu360/react-native-google-places/issues/149. There hasn't yet been any work done towards supporting it from the iOS side (at least not that's currently public).

**Comment by nickmccomb** [comment]
@thomasw i read something about @tolu360 saying use the JS version of the Places API for now.  Have you tried this? Do you know if this is possible?

**Comment by thomasw** [comment]
You can use the Places web service API from an RN app, but you'd need some way of securing your API key. You'd typically use a referrer restriction on such keys, but you won't be able to do that in this context.

Unfortunately, even if you manage that somehow, photo API support is (essentially) free when using the Android SDK but it costs money when using the web service API. See https://developers.google.com/maps/billing/understanding-cost-of-use#places-photo

**Comment by nickmccomb** [comment]
Well i'm happy to add $100 for a bounty for this.  Unfortunately, I don't have time to figure it out myself.

**Comment by nickmccomb** [comment]
Probably best to setup Node.js on a server to do the Places / Photos API requests and pass it back to your app

**Comment by nickmccomb** [comment]
For anyone who needs Places Photos working on iOS and Android, here's my Node.js API code for getting places around a lat/lng and then adding a Places Photo to that location.  

Step 1:  Setup a server somewhere
Step 2:  Install Node.js on the server - Google can show you this
Step 3:  Get your Google Places API key (server key)
Step 4:  Add the code below to your Node code and restart Node (runs on port 3000)

Feel free to create a public Git repo for it so anyone can contribute to it. 

API code:  https://pastebin.com/71h2Xv9x
Request example:  https://ibb.co/egwmsp

**Comment by tolu360** [comment]
This is getting revisited sometime soon with the latest beta release, please see #198
