### ISSUE TITLE
The operation couldn’t be completed. The Places API could not find the user's location. This may be because the user has not allowed the application to access location information.

### ISSUE THREAD

**Issue by NickLatin0** [tolu360/react-native-google-places#165]
When calling RNGooglePlaces.getCurrentPlace() getting this error. 
react-native 0.56.0
react-native-google-places 2.5.2

deployed on actual iphone 6 device debugging

**Comment by nickmccomb** [comment]
You need to ask the user if it's okay to use location first.  Here's my Location.js file i use for iOS / Android which asks the user for location (by calling getLocation function), then gets the users current position, calls getCurrentPlace and returns the results to a callback function:

import { PermissionsAndroid, Platform } from 'react-native';
import RNGooglePlaces from 'react-native-google-places';

export const getLocation = (title, message, callback) =>{
    if(Platform.OS === 'ios'){
      this.getCurrentPosition(callback);
    }else{
      this.requestLocationPermission(title, message, callback);
    }
}

async function requestLocationPermission(title, message, callback){
  try {
    let _this = this;
    const granted = await PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION, {
        'title': title,
        'message': message
      }
    )
    if (granted === PermissionsAndroid.RESULTS.GRANTED) {
      _this.getCurrentPosition(callback);
    }
  } catch (err) {
    alert(err.message);
  }
}

getCurrentPosition = (callback) =>{
  let _this = this;
  navigator.geolocation.getCurrentPosition(
    (position) => {
      _this.getCurrentPlace(callback);
    },
    (error) => alert(error.message),
    { enableHighAccuracy: true, timeout: 20000, maximumAge: 1000 },
  );
}

getCurrentPlace = (callback) =>{
    RNGooglePlaces.getCurrentPlace()
    .then((results) => {
      callback(results);
    })
    .catch((error) => console.log(error.message));
}

**Comment by nickmccomb** [comment]
You need to ask the user if it's okay to use location first.  Here's my Location.js file i use for iOS / Android which asks the user for location (by calling getLocation function), then gets the users current position, calls getCurrentPlace and returns the results to a callback function:

`import { PermissionsAndroid, Platform } from 'react-native';
import RNGooglePlaces from 'react-native-google-places';

export const getLocation = (title, message, callback) =>{
    if(Platform.OS === 'ios'){
      this.getCurrentPosition(callback);
    }else{
      this.requestLocationPermission(title, message, callback);
    }
}

async function requestLocationPermission(title, message, callback){
  try {
    let _this = this;
    const granted = await PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION, {
        'title': title,
        'message': message
      }
    )
    if (granted === PermissionsAndroid.RESULTS.GRANTED) {
      _this.getCurrentPosition(callback);
    }
  } catch (err) {
    alert(err.message);
  }
}

getCurrentPosition = (callback) =>{
  let _this = this;
  navigator.geolocation.getCurrentPosition(
    (position) => {
      _this.getCurrentPlace(callback);
    },
    (error) => alert(error.message),
    { enableHighAccuracy: true, timeout: 20000, maximumAge: 1000 },
  );
}

getCurrentPlace = (callback) =>{
    RNGooglePlaces.getCurrentPlace()
    .then((results) => {
      callback(results);
    })
    .catch((error) => console.log(error.message));
}
`

**Comment by tolu360** [comment]
Please update to the latest release, see #198
