### ISSUE TITLE
How do I set the google api key from react native side?

### ISSUE THREAD

**Issue by anil1712** [tolu360/react-native-google-places#166]
Hi,

I don't want to set the default API key always in my app, it should be configurable. Is there any possibility of existing implementation?

The scenario will be something like this, 
- After launching the app there will be a login screen.
- In login success response, react native client will get the Google API key, so on that time, I want to set the API key.

So let me know if there any solution for this scenario.

Thanks,
Anil

**Comment by devlinb** [comment]
Google allows you to generate an API key that can only be used by a given app bundle. Use that, and the other security options offered by Google, to safeguard your API key.

What you are proposing won't help any, anyone who wants to take your key can do so once it is transferred to the phone. 

In regards to security, if it is on the device, the user has access to it, it is after all *their* device!

(DRM schemes for secure video playback aside)

**Comment by tolu360** [comment]
@anil1712  Please update to the latest release, comes with extra steps to protect your keys. @devlinb is right, what you propose would not be helpful in the light of new billing system by Google. Please see #198
