### ISSUE TITLE
Blank map show up

### ISSUE THREAD

**Issue by soicon** [tolu360/react-native-google-places#167]
![simulator screen shot - iphone 6 - 2018-08-09 at 02 00 37](https://user-images.githubusercontent.com/12295458/43858370-0d516980-9b78-11e8-962f-958c0de969a9.png)
How to fix it?

**Comment by nickmccomb** [comment]
Looks like your API key is incorrect for iOS, or you have it in the wrong place in XCode.  Make sure the correct API key is in your GoogleService-Info.plist file and that file is located in your project folder (App/ios folder) in Xcode

**Comment by soicon** [comment]
API key located in the body of Appdelegate.m according Instrucstion :D

**Comment by marshs2** [comment]
I am facing the same issue as well. What is the fix for this..

**Comment by abdallahnofal** [comment]
Please go to [google API dashboard](https://console.developers.google.com/apis/dashboard), select your project. You'll find a button called "Enable APIs and Services", It will open API library so search about map api, you'll find multiple APIs just select ios one and android one and enable both.

**Comment by kirtishjain9** [comment]
Hi,

How did you mange to show map with Search textIpnput using this library?

Please suggest with some code.

Thanks in advance

**Comment by harry503** [comment]
@tolu360 same as @kirtishjain9 how to get this screen (select a location) that display the map on IOS. Currently, the search place itself is working but no map
