### ISSUE TITLE
Return only one result for faster fetch

### ISSUE THREAD

**Issue by nickbyte** [tolu360/react-native-google-places#170]
RNGooglePlaces.getCurrentPlace() currently returns with 20 places, it takes a long time for fetching the result, can we have an option to return just return one result, so its faster? 

Example: RNGooglePlaces.getCurrentPlace({result:1});

**Comment by tolu360** [comment]
By its nature, it cannot return just one result - hence the `likelihood` value you get for each item in the results. Please do not confuse this feature with [getcurrentposition](https://facebook.github.io/react-native/docs/geolocation#getcurrentposition) from the react-native lib itself.
