### ISSUE TITLE
Trying to convert to Typescript

### ISSUE THREAD

**Issue by obarodi** [tolu360/react-native-google-places#171]
Hello, I am attempting to covert the **js** source code into a **.d.ts file**, but I am having trouble understanding what this means: 

	openAutocompleteModal(filterOptions = {}) {
		return RNGooglePlacesNative.openAutocompleteModal({
			...RNGooglePlaces.filterDefaults,
            ...RNGooglePlaces.boundsDefaults,
			...filterOptions
		})
	}

I notice the other functions within the code are similar. I am kind of newbie to both typescript and js. Can you explain to me what is happening here?

**Comment by tolu360** [comment]
We now have a PR for TS, that should get pulled in shortly. Thanks for your effort.
