### ISSUE TITLE
android not get postal code fields

### ISSUE THREAD

**Issue by onusgit** [tolu360/react-native-google-places#173]
>**IOS Platform work fine But Android Side Not working.**

**IOS Response**
![screen shot 2018-09-05 at 12 54 28 pm](https://user-images.githubusercontent.com/15248145/45077488-f00d6880-b10a-11e8-888a-1f278e876f99.png)

**Android Response**
![screen shot 2018-09-05 at 12 55 01 pm](https://user-images.githubusercontent.com/15248145/45077494-f3085900-b10a-11e8-9121-7d4b24d128b2.png)

**Comment by tolu360** [comment]
That field is not supported on Android, and also update to the latest release, see #198
