### ISSUE TITLE
Help getting RNGooglePlaces.getAutocompletePredictions to work with release schema

### ISSUE THREAD

**Issue by OlleMattsson** [tolu360/react-native-google-places#176]
This is not a bugreport! I'm mostly asking if anyone else has come across a similar situation and what can be done about it.

I have an implementation using getAutocompletepredictions and lookUpPlaceByID. This works flawlessy when building with a debug schema in xcode. However, when built for release, no autocomplete suggestions are shown.

Environment
```
RN 0.57
"react-native-google-places": "~2.5.2",
```

Adding googleapis.com to infoPlist didn't help:
```
<key>googleapis.com</key>
  <dict>
    <key>NSExceptionAllowsInsecureHTTPLoads</key>
    <true/>
    <key>NSIncludesSubdomains</key>
    <true/>
    <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
    <true/>
</dict>	
```

Anything obvious that I've missed in preparing this library for release?

Checking the logs in xcode there's nothing obvious that sticks out. No errors.

**Comment by OlleMattsson** [comment]
The cause seems to stem from the minifyer. 

Using `--dev true --minify false` creates working build.

Not sure if this is a problem in the dependency or in my implementation of it. Research continues :-)

**Comment by tolu360** [comment]
Please start by enabling billing on your Google account, it is the first thing that comes to mind here.
