### ISSUE TITLE
Hi can anyone tell me the procedure of Cocapods?

### ISSUE THREAD

**Issue by abdulateeq9** [tolu360/react-native-google-places#179]
_Originally posted by @brh55 in https://github.com/tolu360/react-native-google-places/issues/51#issuecomment-315158345_

**Comment by brh55** [comment]
@abdulateeq9 , https://github.com/tolu360/react-native-google-places#ios-requires-cocoapods

**Comment by traviisd** [comment]
I wasn't using CocoaPods until I found this component, but I followed the directions and everything worked perfectly, including the simple examples. Excellent job by the way!!!
