### ISSUE TITLE
working on hardware but not simulator

### ISSUE THREAD

**Issue by temitope** [tolu360/react-native-google-places#18]
Hi tolu! 

I went through all the build errors and setup (took a while but finally) and was able to get the module to actually work on my hardware device when i run it from Xcode directly onto my phone. However when trying to run on the simulator I am regularly getting this error (i have tried reboots and reinstalls of the server for simulator and the node_module folder and cache clearing, to no avail). Is it expected behavior to not work on a simulator because of non-device limitations?

---
![screenshot 2017-02-09 00 29 55](https://cloud.githubusercontent.com/assets/1159855/22775118/049f1fde-ee5f-11e6-95cf-0d6ea5af9cfe.png)

**Comment by tolu360** [comment]
Hello @temitope, something is missing in your setup, the package works in the simulator(iOS) and emulator(android), as it does on physical devices. 

Show me a code snippet of how you are importing `RNGooglePlaces`.

And what version of the package you are working it and the version of `react-native` in your project?

**Comment by temitope** [comment]
Sure!

Importing RNGooglePlaces (version **2.0.6**) and usage
react-native version **0.41.2**

```
import RNGooglePlaces from 'react-native-google-places'
class ClassesEdit extends Component {
 _showModal_location = () => {
    RNGooglePlaces.openAutocompleteModal()
    .then((place) => { 
        console.log(place);         
        // place represents user's selection from the
        // suggestions and it is a simplified Google Place object.
    })
    .catch(error => console.log(error.message));  // error is a Javascript Error object
  }
}

```

o se

**Comment by temitope** [comment]
additional errors from console when running **react-native run-ios**

> While building module 'GooglePlaces' imported from /code/DecoTestProj/node_modules/react-native-google-places/ios/RCTConvert+RNGPAutocompleteTypeFilter.m:2:
> In file included from <module-includes>:1:
> In file included from /code/DecoTestProj/node_modules/react-native-google-places/ios/../../../ios/Pods/GooglePlaces/Frameworks/GooglePlaces.framework/Headers/GooglePlaces.h:1:
> /code/DecoTestProj/node_modules/react-native-google-places/ios/../../../ios/Pods/GooglePlaces/Frameworks/GooglePlaces.framework/Headers/GMSAddressComponent.h:12:9: fatal error: module 'GoogleMapsBase' not found
> @import GoogleMapsBase;
>  ~~~~~~~^~~~~~~~~~~~~~
> 1 error generated.
> /code/DecoTestProj/node_modules/react-native-google-places/ios/RCTConvert+RNGPAutocompleteTypeFilter.m:2:9: fatal error: could not build module 'GooglePlaces'
> #import <GooglePlaces/GooglePlaces.h>
>  ~~~~~~~^
> 2 errors generated.
> 
> 
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
> 
> 	CompileC /code/DecoTestProj/ios/build/Build/Intermediates/RNGooglePlaces.build/Debug-iphonesimulator/RNGooglePlaces.build/Objects-normal/x86_64/RCTConvert+RNGPAutocompleteTypeFilter.o RCTConvert+RNGPAutocompleteTypeFilter.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
> (1 failure)
> 
> Installing build/Build/Products/Debug-iphonesimulator/Project.app
> An error was encountered processing the command (domain=MIInstallerErrorDomain, code=4):
> Failed to chmod /Library/Developer/CoreSimulator/Devices/C948F573-0D10-44DE-AC9E-521E1D04E740/data/Library/Caches/com.apple.containermanagerd/Bundle/Application/66249093-FBEC-4AC3-B5EF-5C171BD5ABBD/Project.app/Project : No such file or directory
> Launching org.reactjs.native.example.Project
> An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
> The request to open "org.reactjs.native.example.Project" failed.
> The request was denied by service delegate (SBMainWorkspace) for reason: NotFound ("Application "org.reactjs.native.example.Project" is unknown to FrontBoard").

**Comment by temitope** [comment]
and when trying to build the RNGooglePlaces project by itself from it's project file I noticed

1. The Products/libRNGooglePlaces.a file is highlighted in red (is it missing?)
and these errors

> 'React/TCTConvert.h' file not found
> Module 'GoogleMapsBase' not found

[https://www.dropbox.com/s/p548hwts2jgw0ov/Screenshot%202017-02-09%2022.38.52.png?dl=0](url)

**Comment by tolu360** [comment]
First off, please go over the `README` again. Did you install the dependencies with `Cocoapods` by running `cd ios && pod install` from the terminal? Did you pull the dependencies in by running `react-native link react-native-google-places`?

If you did those already, do them again and do share the whole content of your `Podfile`  and `AppDelegate.m` here. 

If you have done the installation correctly, close all terminal windows running the packager, open your project with the `YourProject.xcworkspace` file in `XCode`. Do a `clean` and `build` it again.

PS: Those missing files show your installation wasn't complete. Cheers

**Comment by temitope** [comment]
Thanks @tolu360 I did a full removal of the module and pods then did a reinstall by going through README step by step, but i am about to do it again and will put my file info here now in the meantime to make sure all my syntax is correct.

PODFILE
=========

> # Uncomment this line to define a global platform for your project
> # platform :ios, '9.0'
> source 'https://github.com/CocoaPods/Specs.git'
> 
> target 'Project' do
>   # Uncomment this line if you're using Swift or would like to use dynamic frameworks
>   # use_frameworks!
> 
>   # Pods for Project
>   pod 'GooglePlaces'
>   pod 'GoogleMaps'
>   pod 'GooglePlacePicker'
> 
>   #target 'ProjectTests' do
>   #  inherit! :search_paths
>     # Pods for testing
>   #end
> 
> end
> 

AppDelegate.m
=============

> #import "AppDelegate.h"
> 
> #import <React/RCTBundleURLProvider.h>
> #import <React/RCTRootView.h>
> 
> @import GooglePlaces;
> @import GoogleMaps;
> 
> @implementation AppDelegate
> 
> - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
> {
>   [GMSPlacesClient provideAPIKey:@"XXXXXXXXXXX"];
>   [GMSServices provideAPIKey:@"XXXXXXXXXXXX"];
>   
>   NSURL *jsCodeLocation;
> 
>   jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
> 
>   RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
>                                                       moduleName:@"Project"
>                                                initialProperties:nil
>                                                    launchOptions:launchOptions];
>   rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];
> 
>   self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
>   UIViewController *rootViewController = [UIViewController new];
>   rootViewController.view = rootView;
>   self.window.rootViewController = rootViewController;
>   [self.window makeKeyAndVisible];
>   return YES;
> }
> 
> @end

**Comment by tolu360** [comment]
Limit your Podfile to just your app target, remove the test target like so:

```rb
target 'YourProject' do

  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'GooglePlacePicker'

end
```

Open and run your app in XCode with the `YourProject.xcworkspace` file subsequently (not the `YourProject.xcodeproj`).

**Comment by temitope** [comment]
@tolu360  odd behavior i am noticing is that when i try to build after cleaning my project a packager terminal windo opens automatically...then the build continues and fails as described before...no simulator opens up though

**Comment by temitope** [comment]
latest result of attempting to build the project in case it helps. still will try to unlink and remove pods and start from scratch 
![screenshot 2017-02-10 13 43 24](https://cloud.githubusercontent.com/assets/1159855/22845336/0124fb10-ef97-11e6-9c90-42d34f2adc32.png)

**Comment by temitope** [comment]
and here is the output from running `pod install`

```
Analyzing dependencies
Downloading dependencies
Installing GoogleMaps (2.1.1)
Installing GooglePlacePicker (2.1.1)
Installing GooglePlaces (2.1.1)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `Project.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There are 3 dependencies from the Podfile and 3 total pods installed.
```

**Comment by temitope** [comment]
Just retried it with a brand new project using `react-native init` and ended up with the same errors...not sure how i ever had it working on the hardware now, but simply not building now...

**Comment by tolu360** [comment]
<img width="877" alt="screen shot 2017-02-11 at 12 24 25 am" src="https://cloud.githubusercontent.com/assets/3914854/22848158/afc2c17e-eff2-11e6-86ed-d5afc995d55a.png">

Just so you can compare, go to `Build Phases`, check under `Link Binary With Libraries`, do you have `libRNGooglePlaces.a` and `libPods-YourProject.a` listed?

Before you try to build in `XCode`, ensure `YourProject` is selected under `TARGETS`, wrong build schemes can prevent the simulator from starting.

At this rate, I am hoping someone else can reproduce your issues! Also try to review closed issues for similarities with yours.

**Comment by temitope** [comment]
thanks for this, removed pods and the project just to get back toa working build. will try again and look for this, also searching the web for similar issues. will report back and hope to close the issue

**Comment by tolu360** [comment]
Not a problem, just keep at it - these things happen. To completely remove pods, hope you are running `pod deintegrate` from the ios folder and not merely deleting the pods folder?

**Comment by temitope** [comment]
@tolu360 yes, the hallmarks of development ;). yeah i ran `deintegrate` here is a screenshot of that section in Build Phases.
![screenshot 2017-02-10 15 59 37](https://cloud.githubusercontent.com/assets/1159855/22848560/449e20de-efaa-11e6-89b7-7010f7085149.png)

**Comment by tolu360** [comment]
Looks good to me from here! I hope `Project` is not a reserved word, maybe call your project something else...

And how come you have multiple build targets?

**Comment by temitope** [comment]
@tolu360 good questions. i made a new project with a different name and still had identical errors. I think the project automatically creates a test target and a tvOS project/test as well (trying to push that heavy).

**Comment by temitope** [comment]
@tolu360 got it! ok so i checked out another project implementing [similar but more limited functionality](https://github.com/q6112345/react-native-google-place-picker) and saw that in the `Podfile` they used version **2.0.1** instead of **2.1.1** for the installs, so I tried it and it worked flawlessly for me on simulator and on hardware. Not sure why **2.1.1** is breaking for me _(i reinstalled pods with each version to test)_, but glad it is fixed. Maybe a footnote in the documentation will help if others end up running into this. for now i will close. o se pupo lopo lopo for your time and effort in helping. hope my pains help others. great project and super helpful. 

Pod file format with versions that worked for me:
```
  pod 'GooglePlacePicker', '= 2.0.1'
  pod 'GooglePlaces', '= 2.0.1'
  pod 'GoogleMaps', '= 2.0.1'
```

**Comment by tolu360** [comment]
Glad you were able to make it work for you @temitope. Do something for me, try to use version `2.1.0` (have used that with no issues in my test app), lets see if we can isolate your issues to just `2.1.1`. Once again, cheers!

**Comment by temitope** [comment]
Did you use the  the **@import** or **#import ** statement to bring in the
pod modules with 2.1.0 ?

**Comment by tolu360** [comment]
Have got `@import`

**Comment by temitope** [comment]
2.1.0 builds successfully 
2.0.1 builds successfully
2.1.1 does not build without error

was able to use the @import syntax on both 2.1.0 and 2.0.1 and i worked

**Comment by tolu360** [comment]
Thanks @temitope, that'd be really helpful!

**Comment by temitope** [comment]
@tolu360 have you been able to build with 2.1.1? Or have you confirmed anyone being able to build with that. Not sure if it is just me yet.

**Comment by temitope** [comment]
@tolu360 bump on prev question of your findings regarding 2.1.1

**Comment by tolu360** [comment]
@temitope I haven't had time to test it out, should get around to it this week

**Comment by tolu360** [comment]
Hi @temitope, heads-up - `1.0.9/2.0.9` should build with no issues on `GoogleMaps 2.1.1 +`. Pull in the latest version and update your `Podfile`, test and let me know. Cheers

**Comment by temitope** [comment]
@tolu360 thanks. before i test what version of react-native are you using? I ran into issues (not with your module) trying to bump up my version and just recovered. I am currently running `0.41.0`

**Comment by tolu360** [comment]
I was testing on `0.40` but I don't think there's been a breaking change since then.

**Comment by temitope** [comment]
updated to `2.0.9` first and everything worked fine without updating Podfile

then updated Podfile to use the Google* pods @ version `2.1.1` and all is running swimmingly without me having to re-update any files in the xcode project directly. Thank you!
