### ISSUE TITLE
Undefined is not an object(evaluating 'RNGooglePlacesNative.openAutocompleteModal')

### ISSUE THREAD

**Issue by harikanammi** [tolu360/react-native-google-places#180]
Hi, i am using this module for sample application. I follow manual installation which is mentioned in **README.md**. But i am getting error like this` Undefined is not an object(evaluating 'RNGooglePlacesNative.openAutocompleteModal')`. How to solve this error. Please give me any suggestions.
Versions:-
>   "react-native": "0.57.3",
>   "react-native-google-places": "^2.5.2",
>    "react-native-maps": "^0.19.0",

Here is my code:-
```
import React, { Component } from 'react';
import {
  View,
  Text,
  TouchableOpacity,
} from 'react-native';
import RNGooglePlaces from 'react-native-google-places';
class GPlacesDemo extends Component {
  openSearchModal() {
    RNGooglePlaces.openAutocompleteModal()
    .then((place) => {
		console.log(place);
		// place represents user's selection from the
		// suggestions and it is a simplified Google Place object.
    })
    .catch(error => console.log(error.message));  // error is a Javascript Error object
  }

  render() {
    return (
      <View style={styles.container}>
        <TouchableOpacity
          style={styles.button}
          onPress={() => this.openSearchModal()}
        >
          <Text>Search address</Text>
        </TouchableOpacity>
      </View>
    );
  }
}
```
Here is the error displaying screen.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/31063894/48044141-70565580-e1b0-11e8-9553-6d35d54a897b.gif)

**Comment by Harikasai999** [comment]
I fixed this issue...

Please Follow this:-
**Manual Linking With Your Project (iOS)**
In XCode, in the project navigator, right click Libraries ➜ Add Files to [your project's name].
Go to node_modules ➜ react-native-google-places and add RNGooglePlaces.xcodeproj.
In XCode, in the project navigator, select your project. Add libRNGooglePlaces.a to your project's Build Phases ➜ Link Binary With Libraries.

**Comment by harikanammi** [comment]
I fixed this issue,

Please follow this:-
**Manual Linking With Your Project (iOS)**
1. In XCode, in the project navigator, right click Libraries ➜ Add Files to [your project's name].
Go to node_modules ➜ react-native-google-places and add RNGooglePlaces.xcodeproj.
2. In XCode, in the project navigator, select your project. Add libRNGooglePlaces.a to your project's Build Phases ➜ Link Binary With Libraries.
