### ISSUE TITLE
react-native-google-places:compileReleaseJavaWithJavac FAILED when running `react-native run-android`

### ISSUE THREAD

**Issue by netEmmanuel** [tolu360/react-native-google-places#184]
This is the error i am getting when i try to compile my RN app 
```
TaxiApp/node_modules/react-native-google-places/android/src/main/java/com/arttitude360/reactnative/rngoogleplaces/RNGooglePlacesModule.java:321: error: cannot find symbol
        List<Object> placeIDsObjects = placeIDs.toArrayList();
                                               ^
  symbol:   method toArrayList()
  location: variable placeIDs of type ReadableArray
1 error
:react-native-google-places:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

```

my package.json
```
"dependencies": {
    "native-base": "^2.1.3",
    "react": "16.0.0-alpha.6",
    "react-addons-update": "^15.5.2",
    "react-native": "0.44.0",
    "react-native-google-places": "^2.1.0",
    "react-native-maps": "^0.15.0",
    "react-native-router-flux": "^3.39.1",
    "react-native-vector-icons": "^4.1.1",
    "react-redux": "^5.0.4",
    "redux": "^3.6.0",
    "redux-thunk": "^2.2.0"
  },
```

**Comment by tolu360** [comment]
Please get on the latest version to support changes from Google, please see #198 to get started.

**Comment by rn000** [comment]
same thing for me, I'm working on the same app and trying to build it in android studio 
/home/usr/TaxiApp/node_modules/react-native-google-places/android/src/main/java/com/arttitude360/reactnative/rngoogleplaces/RNGooglePlacesModule.java:321: error: cannot find symbol
        List<Object> placeIDsObjects = placeIDs.toArrayList();
                                               ^
  symbol:   method toArrayList()
  location: variable placeIDs of type ReadableArray
1 error
:react-native-google-places:compileReleaseJavaWithJavac FAILED

**Comment by aminebtk** [comment]
Hi, having the same problem, 
changed to "react-native-google-places": "3.1.1", but still facing the same problem
