### ISSUE TITLE
not working with expo-kit

### ISSUE THREAD

**Issue by shubhamdeol** [tolu360/react-native-google-places#185]
I am having this error message after following all the steps of integration with Android.

**expo-firebase-messaging. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project**

something is clashing expo-firebase-messaging and react-native-google-places, But, I have no idea what is it. Please help me out with this.

**Comment by tolu360** [comment]
Consider this new workflow - https://blog.expo.io/you-can-now-use-expo-apis-in-any-react-native-app-7c3a93041331
