### ISSUE TITLE
How do you check if error is cancellation of picking screen?

### ISSUE THREAD

**Issue by Zarkopafilis** [tolu360/react-native-google-places#189]
`    RNGooglePlaces.openAutocompleteModal()
      .then((place) => {
        //blabla
      })
      .catch(error => {
        //Find a better way to do this
        if(error.message.contains('cancel')){
          return;
        }
      });`

**Comment by tolu360** [comment]
It says "Selection Cancelled" in the error message, maybe check for that.

**Comment by Zarkopafilis** [comment]
@tolu360 heuristically parsing string is one of the worse practices out there
