### ISSUE TITLE
How get more information of the the result?

### ISSUE THREAD

**Issue by sonnguyenit** [tolu360/react-native-google-places#19]
The place result only information about: name, adress, lat, lng, place_id
If i want more information like result of google place api (includes photos.....):
`{
         "formatted_address" : "New York, NY, USA",
         "geometry" : {
            "location" : {
               "lat" : 40.7127837,
               "lng" : -74.0059413
            },
            "viewport" : {
               "northeast" : {
                  "lat" : 40.9152555,
                  "lng" : -73.70027209999999
               },
               "southwest" : {
                  "lat" : 40.4960439,
                  "lng" : -74.25573489999999
               }
            }
         },
         "icon" : "https://maps.gstatic.com/mapfiles/place_api/icons/geocode-71.png",
         "id" : "7eae6a016a9c6f58e2044573fb8f14227b6e1f96",
         "name" : "New York",
         "photos" : [
            {
               "height" : 2592,
               "html_attributions" : [
                  "\u003ca href=\"https://maps.google.com/maps/contrib/109675169087914453108/photos\"\u003eJernique Webb\u003c/a\u003e"
               ],
               "photo_reference" : "CoQBdwAAABvCjwlFI11PMTsyaKb3hl81StlK5z_nsziAovImoNzX-dxaEeQCiRasa6xb3ccYfZ6Lq5YP-m4A--6l8uyk8siTzhKHOBYdYwLwSt1eM3maNm_LulnbigPPyM1tuAdK9RIpAGKV1dimyereRGAcPZv4KMcD2lKHf-5m_LlegKIfEhCZkVL3One_8kaTYHU4zCVaGhRMs0ZzZWln8ZeT9qcERSSJ4rL_AA",
               "width" : 4608
            }
         ],
         "place_id" : "ChIJOwg_06VPwokRYv534QaPC8g",
         "reference" : "CmRbAAAA7X5dgQSwuttJRVnhq1rNDr-gvRCvx5a_R6UN2pTnKzAXPW1GdxJWCAZG1VvTD4hOmybnb8Xqn_yRwdjajZ7UDoZYIIFS6LkWIJmsxNUL7wN5T5Fj_XQ-1R0agJaa1gkWEhA9kCh6uanW_76pujFpJ5b8GhR-Nv3jt7RFXNVJmm408PWL6WxmtQ",
         "types" : [ "locality", "political" ]
      }`

**Comment by tolu360** [comment]
Hi @sonnguyenit, the native SDK does not necessarily provide all the fields you listed, you can use the `placeID` obtained to query the [web service](https://developers.google.com/places/web-service/) for other `place details`.

Cheers.

**Comment by sonnguyenit** [comment]
@tolu360 Ok. Thanks for your answer.

**Comment by ddeanto** [comment]
See https://github.com/tolu360/react-native-google-places/issues/15
