### ISSUE TITLE
how can i change the location of map to   the location i selected from search 

### ISSUE THREAD

**Issue by enanda** [tolu360/react-native-google-places#190]
when clicking on select : the map moves  to the selected location 

![capture _2019-01-07-16-21-56](https://user-images.githubusercontent.com/34969719/50777107-f23f2980-129a-11e9-8c5d-0a467c199eea.png)
![capture _2019-01-07-16-22-41](https://user-images.githubusercontent.com/34969719/50777116-f8cda100-129a-11e9-8396-3c771015a1ee.png)
![capture _2019-01-07-16-23-15](https://user-images.githubusercontent.com/34969719/50777120-fbc89180-129a-11e9-82bc-b3c6a95e9970.png)

**Comment by tolu360** [comment]
The map does not move to the place selected, it is simply selected and returned when you tap on 'Use Selected Place'. In any case, you may consider building your own UIs, as the PlacePicker has been deprecated by Google and also removed from the latest release of this package.

Please get on the latest version to support changes from Google, please see #198 to get started.
