### ISSUE TITLE
Unknown Named Module: Axios

### ISSUE THREAD

**Issue by BaderSerhan** [tolu360/react-native-google-places#191]
Every time I install this library in my react-native app, I am getting the following error when I run it. I am not finding any resources that may help me fix it up.

**Comment by BaderSerhan** [comment]
Hi @tolu360.
I accidentally submitted this issue here instead of another repository. In fact, I like your library and working on integrating it.
Excuse me for this dumb accident, can you please delete the issue?

**Comment by tolu360** [comment]
Not a problem @BaderSerhan, it happens to the best of us sometimes!
