### ISSUE TITLE
Maybe need to update to the newest SDK 

### ISSUE THREAD

**Issue by kidmysoul** [tolu360/react-native-google-places#193]
Google announced the new Places SDK 

>> Today we're launching upgraded Places SDKs for Android and iOS. They are pay-as-you-go and billed at the same rate as our Places API and Places Library in the Maps JavaScript API. You can visit the Android and iOS migration guides to install the new SDKs.

https://cloud.google.com/blog/products/maps-platform/introducing-new-improved-places-sdks

the old one will no longer work by July 29, 2019.
I think this library maybe affected ?

**Comment by nishantWM** [comment]
Yes the Places SDKs are deprecated
@tolu360
https://developers.google.com/maps/deprecations

**Comment by Mexxerio** [comment]
+1

I also got an email yesterday from google that the old places SDK will be replaces with the new ones on Jan. 29th and the old ones will stop working on July 29th.

**Comment by devlinb** [comment]
This removes the main advantage of this package, since relaying all requests through a web server now costs the same.

**Comment by tmjordan** [comment]
I think we won't be able to use place picker, because it will be drop.
I hope there will be a new version

**Comment by tolu360** [comment]
Updates are coming!

**Comment by sibigit** [comment]
waiting for the updated one

**Comment by jdegger** [comment]
@tolu360 Thanks for your work on this library. Do you have an estimate when the update can be expected? 

We of course don't want to pressure you but it would be highly appreciated to have an estimate so we can plan around this issue. It is not possible anymore to generate the old keys which work till July so it seems like the library is broken for new users.

Many thanks

**Comment by llama** [comment]
@tolu360 thanks for working on an update! The place picker UI (`openPlacePickerModal()`) has been permanently deprecated. Any plans to recreate a drop-in place picker in this library? Otherwise we'll import google maps and get started on our own place picker...

**Comment by shivanshrajpoot** [comment]
@tolu360  Thanks for your work on this library. Do you have an estimate when the update can be expected?

**Comment by tmjordan** [comment]
@llama i don't understand why google decided to deprecate such a useful tool. Even if we don't update the sdk, after july it will still stop working??

**Comment by adnaz** [comment]
we should make a clone using JS

**Comment by adnaz** [comment]
any updates ?

**Comment by tolu360** [comment]
Hi Everyone! New SDK has landed with a couple breaking changes for you to be aware of, first off, discard everything you knew about setting up on Android and continue to the [beta README](https://github.com/tolu360/react-native-google-places/blob/master/BETA_README.md)

**I added securing your keys and working with CI/CD tools** to boot - I hope you enjoy this one, a lot of sweat went into it.

Cheers,
Tolu

**Comment by cormander** [comment]
Thanks for the update! Using `3.0.0-beta.11` and it's working with no javascript changes.

Had to do some work to get it to build on both iOS and Android though, here are some notes for anyone who might have issues:

Remove the `ios/Podfile.lock`, do a `pod repo update`, and then do the `pod install`. This is to make sure you pick up the v3 of the google api.

If you use play services for other things, you'll need to update your `android/app/build.gradle` to the latest version of `com.google.android.gms:play-services-base` (and other related libraries if you use them).

And, regarding the `RNGP_ANDROID_API_KEY` -- this is quite the change. I use `react-native-config`, but that doesn't set environment variables during the build itself. I tried a few different things to no avail before my workaround in making gradle also read in the `.env` file and translate the variable I export to this. See this commit:

https://github.com/OurVoiceUSA/HelloVoter/commit/75ae7eded0b0cb70656ef837e04c58b85b89c299

My preference is to use strings set from the `AndroidManifest.xml` like this:

      <meta-data android:name="com.google.android.geo.API_KEY" android:value="@string/GOOGLE_API_KEY_ANDROID"/>

But don't know how to approach this from a dependency using these strings. Any thoughts? Would make it work as it was before in the previous version.

Thanks,
