### ISSUE TITLE
Why i always get undefined error while using react-native-google-places?

### ISSUE THREAD

**Issue by galuh1300d** [tolu360/react-native-google-places#195]
I'm using it in ios development. If i console.log RNGooglePlaces
it shows me all the functions
but if i using one of it's function
it gives me undefined

why this happened?

**Comment by novenix** [comment]
https://github.com/tolu360/react-native-google-places/issues/193 I think is because this

**Comment by tolu360** [comment]
Please get on the latest version to support changes from Google, please see #198 to get started.
