### ISSUE TITLE
Language setting?

### ISSUE THREAD

**Issue by danielweinmann** [tolu360/react-native-google-places#20]
Hi there! Thanks for the package :)

Is there a language setting? If not, can you give me guidelines so I can contribute with this feature?

**Comment by danielweinmann** [comment]
Just found out that it uses the device's language ;) thanks again!

**Comment by tolu360** [comment]
Hi @danielweinmann, I'm sorry I could not get back to you before now. You are right about how languages work with `Google Places` SDKs. 

Thank you.
