### ISSUE TITLE
Could not resolve com.google.code.findbugs:jsr305:3.0.1.

### ISSUE THREAD

**Issue by dileepbolisetti** [tolu360/react-native-google-places#205]
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve com.google.code.findbugs:jsr305:3.0.1.
`
![Screen Shot 2019-03-29 at 9 21 39 AM](https://user-images.githubusercontent.com/8918698/55208693-29bbd300-5205-11e9-8a90-e8b5c93099ef.png)
`

**// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "27.0.3"
        minSdkVersion = 21
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
    }
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        maven {
            url 'https://maven.fabric.io/public'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.2'
        classpath 'com.google.gms:google-services:4.0.1'
        classpath 'com.google.firebase:firebase-plugins:1.1.5'
        classpath 'io.fabric.tools:gradle:1.25.4'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        maven {
            url "https://maven.google.com"
        }
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}

subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex')) {
                details.useVersion "27.0.2"
            }
        }
    }
}
**

**Comment by OgieBen** [comment]
simply add this dependency to the module's build.gradle file

`  implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.2' `

As a reminder also add this to the file too to avoid other classpath errors:


` implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}" `


I hope this helps.

**Comment by Iamstanlee** [comment]
thanks OgieBen 
worked for me

**Comment by dileepbolisetti** [comment]
@OgieBen  no luck for me i think `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip` is the problem it seems but with newer versions of `react-native init App` Android set up by  default is set to   ` classpath 'com.android.tools.build:gradle:3.3.1',` `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip`.  `"react": "16.8.3"`,
    `"react-native": "0.59.3"`,  Am i correct can i get any help in this direction.

**Comment by OgieBen** [comment]
@dileepbolisetti could you paste your error here so that I can see the stack trace?

**Comment by dileepbolisetti** [comment]
is this ok `

../node_modules/react-native-google-places/android/build.gradle |  
-- | --
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve com.android.support:appcompat-v7:26.1.0. |  
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve com.android.support:support-annotations:26.1.0. |  
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve com.android.support:support-compat:26.1.0. |  
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve android.arch.lifecycle:runtime:1.0.0. |  
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve android.arch.lifecycle:common:1.0.0. |  
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve android.arch.core:common:1.0.0. |  
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve com.android.support:support-core-utils:26.1.0. |  
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve com.android.support:support-core-ui:26.1.0. |  
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve com.android.support:support-fragment:26.1.0. |  
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve com.android.support:support-vector-drawable:26.1.0. |  
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve com.android.support:animated-vector-drawable:26.1.0. |  
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve com.google.code.findbugs:jsr305:1.3.9. |  
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve com.android.support:appcompat-v7:28.0.0. |  
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve com.google.code.findbugs:jsr305:3.0.2. |  
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve com.android.support:appcompat-v7:26.1.0. |  
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve com.google.code.findbugs:jsr305:3.0.1. |  
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve com.android.support:support-annotations:28.0.0. |  
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve com.android.support:support-compat:28.0.0. |  
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve com.android.support:support-core-utils:28.0.0. |  
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve com.android.support:support-fragment:28.0.0. |  
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve com.android.support:support-vector-drawable:28.0.0. |  
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve com.android.support:animated-vector-drawable:28.0.0. |  
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve com.android.support:support-annotations:26.1.0. |  
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve com.android.support:support-compat:26.1.0. |  
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve com.android.support:support-core-ui:26.1.0. |  
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve com.android.support:support-core-utils:26.1.0. |  
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve com.android.support:support-fragment:26.1.0. |  
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve com.google.code.findbugs:jsr305:1.3.9. |  
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve android.arch.lifecycle:runtime:1.1.1. |  
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve com.android.support:support-core-ui:28.0.0. |  
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve com.android.support:support-annotations:26.0.2. |  
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve android.arch.lifecycle:common:1.1.1. |  
Unable to resolve dependency for ':react-native-google-places@debug/compileClasspath': Could not resolve android.arch.core:common:1.1.1. |  
Unable to resolve dependency for ':react-native-google-places@release/compileClasspath': Could not resolve com.android.support:appcompat-v7:26.1.0. |  
Unable to resolve dependency for ':react-native-google-places@release/compileClasspath': Could not resolve com.android.support:support-annotations:26.1.0. |  
Unable to resolve dependency for ':react-native-google-places@release/compileClasspath': Could not resolve com.android.support:support-compat:26.1.0. |  
Unable to resolve dependency for ':react-native-google-places@release/compileClasspath': Could not resolve android.arch.lifecycle:runtime:1.0.0. |  
Unable to resolve dependency for ':react-native-google-places@release/compileClasspath': Could not resolve android.arch.lifecycle:common:1.0.0. |  
Unable to resolve dependency for ':react-native-google-places@release/compileClasspath': Could not resolve android.arch.core:common:1.0.0. |  
Unable to resolve dependency for ':react-native-google-places@release/compileClasspath': Could not resolve com.android.support:support-core-utils:26.1.0. |  
Unable to resolve dependency for ':react-native-google-places@release/compileClasspath': Could not resolve com.android.support:support-core-ui:26.1.0. |  
Unable to resolve dependency for ':react-native-google-places@release/compileClasspath': Could not resolve com.android.support:support-fragment:26.1.0. |  
Unable to resolve dependency for ':react-native-google-places@release/compileClasspath': Could not resolve com.android.support:support-vector-drawable:26.1.0. |  
Unable to resolve dependency for ':react-native-google-places@release/compileClasspath': Could not resolve com.android.support:animated-vector-drawable:26.1.0. |  
Unable to resolve dependency for ':react-native-google-places@release/compileClasspath': Could not resolve com.google.code.findbugs:jsr305:1.3.9. |  
Unable to resolve dependency for ':react-native-google-places@release/compileClasspath': Could not resolve com.android.support:appcompat-v7:28.0.0. |  
Unable to resolve dependency for ':react-native-google-places@release/compileClasspath': Could not resolve com.google.code.findbugs:jsr305:3.0.2. |  
Unable to resolve dependency for ':react-native-google-places@release/compileClasspath': Could not resolve com.android.support:appcompat-v7:26.1.0. |  
Unable to resolve dependency for ':react-native-google-places@release/compileClasspath': Could not resolve com.google.code.findbugs:jsr305:3.0.1. |  
Unable to resolve dependency for ':react-native-google-places@release/compileClasspath': Could not resolve com.android.support:support-annotations:28.0.0. |  
Unable to resolve dependency for ':react-native-google-places@release/compileClasspath': Could not resolve com.android.support:support-compat:28.0.0. |  
Unable to resolve dependency for ':react-native-google-places@release/compileClasspath': Could not resolve com.android.support:support-core-utils:28.0.0. |  
Unable to resolve dependency for ':react-native-google-places@release/compileClasspath': Could not resolve com.android.support:support-fragment:28.0.0. |  
Unable to resolve dependency for ':react-native-google-places@release/compileClasspath': Could not resolve com.android.support:support-vector-drawable:28.0.0. |  
Unable to resolve dependency for ':react-native-google-places@release/compileClasspath': Could not resolve com.android.support:animated-vector-drawable:28.0.0. |  
Unable to resolve dependency for ':react-native-google-places@release/compileClasspath': Could not resolve com.android.support:support-annotations:26.1.0. |  
Unable to resolve dependency for ':react-native-google-places@release/compileClasspath': Could not resolve com.android.support:support-compat:26.1.0. |  
Unable to resolve dependency for ':react-native-google-places@release/compileClasspath': Could not resolve com.android.support:support-core-ui:26.1.0. |  
Unable to resolve dependency for ':react-native-google-places@release/compileClasspath': Could not resolve com.android.support:support-core-utils:26.1.0. |  
Unable to resolve dependency for ':react-native-google-places@release/compileClasspath': Could not resolve com.android.support:support-fragment:26.1.0. |  
Unable to resolve dependency for ':react-native-google-places@release/compileClasspath': Could not resolve com.google.code.findbugs:jsr305:1.3.9. |  
Unable to resolve dependency for ':react-native-google-places@release/compileClasspath': Could not resolve android.arch.lifecycle:runtime:1.1.1. |  
Unable to resolve dependency for ':react-native-google-places@release/compileClasspath': Could not resolve com.android.support:support-core-ui:28.0.0. |  
Unable to resolve dependency for ':react-native-google-places@release/compileClasspath': Could not resolve com.android.support:support-annotations:26.0.2. |  

`

**Comment by OgieBen** [comment]
Try to  add this dependency to the module's `node_modules/react-native-google-places/build.gradle` file

implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"

**Comment by dileepbolisetti** [comment]
my bad thanks, need to update **node_modules**
