### ISSUE TITLE
"The application's bundle identifier does not match one of the allowed iOS applications for the API key" - iOS

### ISSUE THREAD

**Issue by shamvilm** [tolu360/react-native-google-places#206]
Places API error: Error Domain=com.google.places.ErrorDomain Code=-10 "The application's bundle identifier does not match one of the allowed iOS applications for the API key. See the developer's guide (https://developers.google.com/places/ios-sdk/start) for how to configure bundle restrictions on API keys." 

There is a per-IP or per-Referer restriction configured on your API key and the request does not match these restrictions. Please use the Google Developers Console to update your API key configuration if request from this IP or referer should be allowed.

**The bundle identifier IS correct.**
And I enabled Places API.
Anything I missed??

![Screenshot 2019-04-01 at 3 25 13 PM](https://user-images.githubusercontent.com/20102262/55319400-6a7c4c00-5492-11e9-8a03-156cf058611f.png)

**Comment by tolu360** [comment]
I take it you fixed things, no? I would close this for now, reopen if you still need help with this issue!
