### ISSUE TITLE
Xcode 10.1 Fails to build: property 'plusCode' not found on object of type 'GMSPlace *'

### ISSUE THREAD

**Issue by levi-beers** [tolu360/react-native-google-places#207]
Hello, any help would be appreciated:

XCode 10.1 is failing to build, referencing an error in RNGooglePlaces. I'm using the latest 3.0 beta (looks like build 11). 

<img width="817" alt="Screen Shot 2019-04-02 at 1 30 18 AM" src="https://user-images.githubusercontent.com/16378407/55378543-6595b780-54e7-11e9-9a0c-1def93319fc3.png">

Anyone have any idea where to begin here?

```
    "react": "16.8.3",
    "react-native": "0.59.1",
```

**Comment by firehand33** [comment]
i'm having this issue on the latest 3.0 beta and RN 0.59.3...

**Comment by tolu360** [comment]
Hi, if you are upgrading from versions 2.*, check your `Podfile.lock` file, are you on versions 3.* of the native iOS SDKs? Ideally, your `Podfile.lock` should say, at least, `3.0.3` for both `GoogleMaps` and `GooglePlaces`, if it isn't, you may need to clean your project, update the pods and try to build again.

**Comment by kidmysoul** [comment]
Saddly I use react-native-maps too and it's cocoapod spec file(which need GoogleMaps = 2.5.0) get conflicted with this one(which need GoogleMaps = 3.0.3)


https://github.com/react-native-community/react-native-maps/issues/2748

**Comment by manishsoodz** [comment]
Directly changed GoogleMaps version in "**Application/node_modules/react-native-maps/react-native-google-maps.podspec**" from 2.5.0 to 3.0.1 Fix that issue.
Thanks @kidmysoul
