### ISSUE TITLE
Not Working in iOS

### ISSUE THREAD

**Issue by ydv0121** [tolu360/react-native-google-places#211]
not working in iOS..only work one time then it doesn't give me result 'Can't load search results. Try Again' 
my places API key is enabled.

see attachment
![Screenshot 2019-04-15 at 10 40 39 AM](https://user-images.githubusercontent.com/37238045/56108768-20ec3080-5f6b-11e9-8565-622cccf98cc7.png)

**Comment by ertyurk** [comment]
Same for me

**Comment by andyesp** [comment]
Are you using the beta version? It's working for me.

**Comment by ydv0121** [comment]
not i am not using beta version..what version you are using?

**Comment by tolu360** [comment]
Update your app to use `v3.0.1` of this package. Also, there are changes you should know about, please read the README again. Cheers!
