### ISSUE TITLE
GooglePlaces/GooglePlaces.h file not found

### ISSUE THREAD

**Issue by VitorBrangioni** [tolu360/react-native-google-places#212]
GooglePlaces/GooglePlaces.h file not found

How resolve this issue without cocoapods?

**Comment by christyharagan** [comment]
In Xcode, select Frameworks->RNGooglePlaces.xcodeproj, then go to "Build Settings", then find "Framework search paths". Add the following: "${SRCROOT}/../../../ios"

You can safely remove the other entries (although there's no harm in leaving them in either).

**Comment by VitorBrangioni** [comment]
I solved only with cocoapods. Thanks Christy Haragan

**Comment by luisorduz** [comment]
> In Xcode, select Frameworks->RNGooglePlaces.xcodeproj, then go to "Build Settings", then find "Framework search paths". Add the following: "${SRCROOT}/../../../ios"
> 
> You can safely remove the other entries (although there's no harm in leaving them in either).

You are the best, thank you! @christyharagan
