### ISSUE TITLE
Xcode - Property 'placeFields' not found on object of type 'GMSAutocompleteViewController *'

### ISSUE THREAD

**Issue by RecaMedia** [tolu360/react-native-google-places#215]
I'm running into this issue. Is there an update to the iOS code to correct this?

![Screen Shot 2019-04-26 at 4 33 59 PM](https://user-images.githubusercontent.com/4397817/56835225-a0b6ac80-6841-11e9-91e0-fdae3f7ca68f.png)

Here is what I have in my Pod file

![Screen Shot 2019-04-26 at 4 36 37 PM](https://user-images.githubusercontent.com/4397817/56835256-aad8ab00-6841-11e9-95e0-0d1665ebba30.png)

**Comment by RecaMedia** [comment]
Found sort of a similar issue here in this [stackoverflow post](https://stackoverflow.com/questions/49318352/gmsplace-error-with-expected-a-type).

**Comment by RecaMedia** [comment]
@tolu360 this error seem to be related to this [commit](https://github.com/tolu360/react-native-google-places/commit/daddfc28b0d9678dafb5d7e0358ee6ac4c37aedd#diff-96e11b9e5374b48a06897bd48233dd1f). Any possible solutions?

**Comment by WazzeZ** [comment]
Update `GoogleMap` and `GooglePlaces` to version `3.1` will solve this problem.

**Comment by tolu360** [comment]
> Update `GoogleMap` and `GooglePlaces` to version `3.1` will solve this problem.

The recommendation above would fix the Xcode error. Also update your app to use `v3.0.1` of this package.

**Comment by RecaMedia** [comment]
I forgot to respond to this, but I was able to resolve this issue with the update.
