### ISSUE TITLE
undefined - RNGooglePlaces.openPlacePickerModal(), is there any alternate way to use it?

### ISSUE THREAD

**Issue by usama23sep** [tolu360/react-native-google-places#216]

**Comment by usama23sep** [comment]
After i updated to V3, i'm unable to use RNGooglePlaces.openPlacePickerModal()

@tolu360 please help.

**Comment by tolu360** [comment]
Google has **deprecated** the Place Picker and would no longer support it, hence I would also **not** be supporting in this library moving forward (v3 and above). You should reproduce the functionality yourself, using react-native-maps and `getAutocompletePredictions()` or downgrade to v2 if you must continue to use the Place Picker modal (this is not recommended as I would not be supporting v2 any longer and I would move the current beta to a stable release in a few days).

Cheers!
