### ISSUE TITLE
Bumped to minSdkVersion 21 - couldn't find any reason as to why?

### ISSUE THREAD

**Issue by rodperottoni** [tolu360/react-native-google-places#220]
According to the new [Places SDK migration guide](https://developers.google.com/places/android-sdk/client-migration#compat), Android phones with SDKs as low as 16 are still supported.
This change will negatively impact apps used everywhere in the planet, but particularly in third-world countries where the purchase power is lower (meaning the percentage of users with outdated Android phones is significantly higher). In one of our apps available in Australia (one of the countries with the highest purchase power in the planet) we still have ~2k users on Android 16-21, so I imagine this figure would be even higher somewhere else.
I'm wondering if you'd be considering accepting a PR to lower the ```minSdkVersion``` back to 16?

Thank you.

**Comment by aforty** [comment]
Same, wondering why this is necessary. I prefer to keep the `minSdkVersion` as low as possible.

**Comment by tolu360** [comment]
So heads up, `minSdkVersion` is back to 16 or whatever a user sets for their project. I just tagged `3.0.1` release, ensure you pull that in and update your app. Cheers!

**Comment by rodperottoni** [comment]
Really appreciate your work @tolu360.
