### ISSUE TITLE
【IOS】Property 'types' not found on object of type 'GMSAddressComponent *';

### ISSUE THREAD

**Issue by kidmysoul** [tolu360/react-native-google-places#222]
my version:     "react-native-google-places": "^3.0.1",

the error:
![スクリーンショット 2019-05-18 23 13 05](https://user-images.githubusercontent.com/15664045/57970935-96ac4780-79c2-11e9-9d10-6fe50175c14d.png)

When i change types to type, the error disappeared.I wonder if it is correct?

**Comment by tolu360** [comment]
Currently in transit but that would work temporarily. The reason types is not available in your build is because your GooglePlaces library is below 3.1.0 - you can run pod update or manually set the version in your Podfile - also don't forget to change it back to types when you update your pods.

**Comment by tolu360** [comment]
If this is still an issue after updating your pods, you can open a new issue - closing this now. Cheers
