### ISSUE TITLE
openPlacePickerModal is removed ?

### ISSUE THREAD

**Issue by DodiOSE** [tolu360/react-native-google-places#223]

**Comment by tolu360** [comment]
**Notice from Google**: _The Place Picker (Android, iOS) is deprecated as of January 29, 2019. This feature will be turned off on July 29, 2019, and will no longer be available after that date_. 

If you must continue to use it, you would have to stay on v2 of this package as it has already been removed in v3+. Cheers

**Comment by DodiOSE** [comment]
But in v2 cannot connect to place api key. I already use the right api key and i was already enabled it. The api key worked in android native (java), but its not worked in react native iOS using react-native-google-places library.

I get response in console : 

The operation couldn’t be completed. The Places API for iOS is not enabled. See the developer's guide (https://developers.google.com/places/ios-sdk/start) for how to enable the Google Places API for iOS.

**Comment by tolu360** [comment]
Follow what the error is telling you, get another key for iOS and restrict that to just your iOS apps - keep using the one that currently works on Android, on Android and restrict that too to your Android apps. And follow the [README for v2](https://github.com/tolu360/react-native-google-places/blob/master/READMEV2.md), if that is the version you are on and ensure you have installed v2.5.2. **But please support is dropped for v2, kindly take note of that**.

**Comment by akiladevinda** [comment]
@tolu360  how to install v2.5.2 of this npm package ?

**Comment by DodiOSE** [comment]
I already do it, but always get same error. 

I use this : 
  pod 'GooglePlacePicker', '= 2.7.0'
  pod 'GooglePlaces', '= 2.7.0'
  pod 'GoogleMaps', '= 2.7.0'

it's wrong ? @tolu360

**Comment by DodiOSE** [comment]
up

**Comment by DodiOSE** [comment]
So i already found the problem here. The Place SDK for iOS cannot enable if we make new project now (2019 after Google Place v.2.7.0 deprecated). I have try to use my api key before the "Place SDK for iOS" removed from the list library Google Service. Maybe.
