### ISSUE TITLE
iOS build failed - please fix this line addressComponent[@"types"] = place.addressComponents[i].type;

### ISSUE THREAD

**Issue by bear-junior** [tolu360/react-native-google-places#225]
As is - BUILD FAILED:
 addressComponent[@"types"] = place.addressComponents[i].types;

Should be:
 addressComponent[@"types"] = place.addressComponents[i].type;

in NSMutableDictionary+GMSPlace.m

**Comment by tolu360** [comment]
I answered this in a [closed issue](https://github.com/tolu360/react-native-google-places/issues/222#issuecomment-493682293) which I have just pinned - please take a look there. Would leave this open for others to see. Cheers!

**Comment by bear-junior** [comment]
@tolu360 still visible after pod update...

**Comment by tolu360** [comment]
Can you check the version you are currently on in your `Podfile.lock` file? If you are on 3.1.0 or above, clean and rebuild your project, you should be fine - I ran into same issue while reviewing and testing PRs.

**Comment by bear-junior** [comment]
if I try to set version in Podfile to 3.1.0, after pod update I have this error -  

CocoaPods could not find compatible versions for pod "GoogleMaps":
  In Podfile:
    GoogleMaps

    react-native-google-maps (from `../node_modules/react-native-maps`) was resolved to 0.24.0, which depends on
      GoogleMaps (= 3.0.3)

CocoaPods could not find compatible versions for pod "GoogleMaps/Base":
  In Podfile:
    GooglePlaces (= 3.1.0) was resolved to 3.1.0, which depends on
      GoogleMaps/Base (= 3.1.0)

    react-native-google-maps (from `../node_modules/react-native-maps`) was resolved to 0.24.0, which depends on
      GoogleMaps (= 3.0.3) was resolved to 3.0.3, which depends on
        GoogleMaps/Maps (= 3.0.3) was resolved to 3.0.3, which depends on
          GoogleMaps/Base (= 3.0.3)

**Comment by bear-junior** [comment]
So I'm on 3.0.3 version

**Comment by tolu360** [comment]
So there goes your error - your pods were not updated to 3.1.0 the first time either and that was because `react-native-google-maps` was depending on 3.0.3. Just so you can continue with your development, you can temporarily leave in the `_types_ to _type_` correction you made earlier - your project would build with that in place but you would not have consistent response format with Android (if your project is cross-platform), as only _types_ is available on Android.

**Comment by bear-junior** [comment]
yup, I can change types to type locally, but still - without patch it won't work on CI

**Comment by tolu360** [comment]
So running a [patch](https://github.com/ds300/patch-package) is easy, or force both `react-native-google-maps` and `react-native-google-places` to use `3.1.0` - either would make your CI build happy!
