### ISSUE TITLE
Place Picker disabled ?

### ISSUE THREAD

**Issue by DodiOSE** [tolu360/react-native-google-places#228]
Before, version 2.5 cannot connect to place api key. Then this version (3.01) cannot access (open modal) place picker ? why ?

**Comment by tolu360** [comment]
Hi @DodiOSE, I already answered [your question here](https://github.com/tolu360/react-native-google-places/issues/223#issuecomment-493971703), please can you stop raising the same answered issue over and over again? Thank you.
