### ISSUE TITLE
getCurrentPlace works in 3.0.0-beta.11 but not on 3.0.3 in Android

### ISSUE THREAD

**Issue by Mexxerio** [tolu360/react-native-google-places#230]
I tried using the current version on master (3.0.2) but when I try to call `getCurrentPlace` I get the error: 
`Operation failed due to an invalid request sent to Places API.`

I downgraded to the library `3.0.0-beta.11` and used the pod version `3.0.3` for GooglePlaces and GoogleMaps.
After that everything works as expected.

Tested in iOS

**Comment by tolu360** [comment]
I think this is now fixed in `3.0.3`, you may wish to update to that. Also you would need, at least, pod version `3.1.0` or higher for both `GooglePlaces` and `GoogleMaps` on `react-native-google-places 3.0.1 and above`. Let me know if and when updating fixes this issue for you.

**Comment by Mexxerio** [comment]
That fixed it! 
Thanks a lot!

**Comment by Mexxerio** [comment]
@tolu360 I just tried it out in Android and there I'm getting again: `9012: Error while parsing 'fields' parameter: Unsupported field name 'address_components'. `

**Comment by tolu360** [comment]
So it is the same error as you earlier reported on iOS, guessed I missed it on Android with the 3.0.3 release. Now we have `3.0.4`, so pull in and test again. I am hoping this is the last release today! 😉

**Comment by Mexxerio** [comment]
When I try to compile it I'm getting the errors:

```
> Task :react-native-google-places:compileDebugJavaWithJavac FAILED
.../node_modules/react-native-google-places/android/src/main/java/com/arttitude360/reactnative/rngoogleplaces/RNGooglePlacesModule.java:551: error: ';' expected
            allPlaceFields.removeAll(Arrays.asList(Place.Field.OPENING_HOURS, Place.Field.PHONE_NUMBER, Place.Field.WEBSITE_URI, Place.Field.ADDRESS_COMPONENTS)));
                                                                                                                                                                 ^
.../node_modules/react-native-google-places/android/src/main/java/com/arttitude360/reactnative/rngoogleplaces/RNGooglePlacesModule.java:563: error: ';' expected
            selectedFields.removeAll(Arrays.asList(Place.Field.OPENING_HOURS, Place.Field.PHONE_NUMBER, Place.Field.WEBSITE_URI, Place.Field.ADDRESS_COMPONENTS)));
                                                                                                                                                                 ^
2 errors
```

**Comment by Mexxerio** [comment]
https://github.com/tolu360/react-native-google-places/commit/8b98363fab595de7de34a729ffd3bdd69e453a26

You added a unnecessary parentheses after `Place.Field.ADDRESS_COMPONENTS`

**Comment by tolu360** [comment]
You are right, weird editor addition - please can you try out at `commit 8a2c0127b5151571b2dae5a08366e42a04b4f10b` or `branch v3` before I tag 3.0.5?

**Comment by Mexxerio** [comment]
Yes that commit works 👍

**Comment by tolu360** [comment]
So `3.0.5` is tagged and released - my bad on all the broken releases! Cheers!

**Comment by Mexxerio** [comment]
Thx for your fast help 👍
