### ISSUE TITLE
Stuck after choose location (IOS)

### ISSUE THREAD

**Issue by alyuid** [tolu360/react-native-google-places#231]
Firstly I was not able to manually link on IOS until I solved this thanks to https://github.com/tolu360/react-native-google-places/issues/203#issuecomment-491138896

Now I have a problem that if I open the modal (RNGooglePlaces.openAutocompleteModal) and choose a place, it is closing the modal, updating the location text on the screen and the application is getting stuck after that. It is not reacting to my actions after that. Sometimes it manages to keep working but not many times. There is no error code on xcode or warning on the screen. I tried to upgrade to version 3 but not worked.

Edit: I tested the app on a real device and there is no problem. This situation is only for emulators I guess. I don't know what causes this.

**Comment by aliakgul** [comment]
`WARNING: Unable to find and load 'GoogleMaps.bundle' for Google Maps SDK for iOS. This may be a sign that you've forgotten to include a resources bundle in your 'Copy Bundle Resources' build phase.`
I get the same error after version update. This time it did not work on device either. This time I used autolinking, not manual linking.
Thanks to schtipoun [solution is here](https://stackoverflow.com/a/47528898/9485345)
