### ISSUE TITLE
Is there a replacement for the Place Picker ?

### ISSUE THREAD

**Issue by pleportz** [tolu360/react-native-google-places#234]
Hi @tolu360 
Thank you very much for this great lib :)

From what I read here https://developers.google.com/places/android-sdk/client-migration, it seems that the Place Picker will be plainly removed starting July 29, 2019 but I'm not sure.
Do you know if Google has scheduled a replacement for the Place Picker?

If not, do you know if there is any alternative to display a place picker with a map in a react-native app ? 

Thanks !

**Comment by tolu360** [comment]
Hi @pleportz, I'd say I think the Place Picker is gone for good but the functionalities are not so hard to replicate with your own UIs - that may entail using `react-native-google-places` in combination with the `react-native-maps` library. A quick [design hint](https://github.com/tolu360/react-native-google-places#design-hint) has always been included in the README the whole time. Hope this is helpful?

**Comment by pleportz** [comment]
Yes thank you :)

**Comment by craig0990** [comment]
Can I just clarify: I'm using the `openAutocompleteModal` method, not the `openPlacePickerModal` method.

So...this will continue to work, beyond July 29th? If I understand correctly, only the Place Picker is deprecated, not the Autocomplete UI widgets: https://developers.google.com/places/android-sdk/client-migration#place_picker_and_autocomplete_updates

**Comment by tolu360** [comment]
Yes, `openAutocompleteModal` would continue to work! You are welcome, @craig0990
