### ISSUE TITLE
Operation failed due to an invalid (malformed or missing) API key

### ISSUE THREAD

**Issue by Ilario17** [tolu360/react-native-google-places#236]
I updated the app today to "react-native-google-places": "^ 3.0.5", and I started experiencing this error.

I created new Api keys and checked billing (I already had a linked account)

I left the provideAPIKey in didFinishLaunchingWithOptions:

![Schermata 2019-06-10 alle 15 32 10](https://user-images.githubusercontent.com/33326791/59198834-ef6f9a00-8b94-11e9-8166-7eb1a8d2a67d.png)

Reading the other bug reports, it seems as if the library no longer sends the API_KEY if you add it in didFinish ..

**Comment by PavelKoyushev** [comment]
Same problem! Changing the key didn't help. How did you solved it?

**Comment by NewDestinyWay** [comment]
Yeah, how you are solved it?
