### ISSUE TITLE
This IP, site or mobile application is not authorized to use this API key. Request received from IP address , with empty referer

### ISSUE THREAD

**Issue by janet-rivas** [tolu360/react-native-google-places#238]
"react-native": "^0.59.8",
"react-native-google-places": "^3.1.0",
I set my Api -key with Android apps restriction but I'm getting 
    authorized to use this API key. Request received from IP address , with empty referer
**referer** is used for HTTP referres 
I used keytool in Android studio  terminal to get a release certificate fingerprint.
keytool -list -v -keystore your_keystore_name -alias your_alias_name 
No sure why I'm getting this error

**Comment by tolu360** [comment]
Hello @janet-rivas, you may be missing the debug certificate fingerprint on the Google console and so when you tested on a debug build, your app id was not granted permissions to use the key.
I would suggest you add your app id twice on the console but with one having the debug fingerprint and the other, the release fingerprint. Clean and build your app again and let me know if it works for you.

**Comment by janet-rivas** [comment]
Thank you so much that fix my issue :)
