### ISSUE TITLE
Could not load search Results And Illegal Callback Invocation

### ISSUE THREAD

**Issue by eman1000** [tolu360/react-native-google-places#24]
Hi thanks for the google places package.

I am having problems with RNGooglePlaces.openAutocompleteModal from the example you gave. When I click pick a place, the modal shows up and disappears almost immediately with an error message "Could not load search results". When I try to input some values in the search field I get an error "Illegal callback invocation from native module. This callback type only permits a single invocation from native code."

![screen shot 2017-02-27 at 10 35 28 pm](https://cloud.githubusercontent.com/assets/16818188/23365215/3040bcc8-fd3d-11e6-919f-450ab84d73c3.png)

**Comment by tolu360** [comment]
@eman1000, please share your code snippets here, it seems you are somehow invoking the response callback twice.

Also state which version of the package you are using and which on which version of `react-native` you are. Cheers!

**Comment by eman1000** [comment]
@tolu360 Thanks for the response. I managed to fix the problem. I needed to enable Google Places API for iOS on google developer's console.

**Comment by Slavezax** [comment]
Google now needs billing information, too. Or this error appears. FYI.
