### ISSUE TITLE
'React/RCTConvert.h' file not found

### ISSUE THREAD

**Issue by wmonecke** [tolu360/react-native-google-places#241]
I cant seem to install the lib on iOS

Is this needed inside your Podfile?

````
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-places'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end
````

My Podfile looks like this:

````
platform :ios, '9.0'

target 'moodPixel' do

  pod 'Firebase/AdMob', '~> 5.15.0'
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Auth', '~> 5.15.0'
  pod 'Firebase/Firestore', '~> 5.15.0'
  pod 'Firebase/Messaging', '~> 5.15.0'
  pod 'GoogleSignIn', '~> 4.4.0'
  pod 'react-native-google-places', :path => '../node_modules/react-native-google-places'

end
````
I am getting the following error: `'React/RCTConvert.h' file not found`

Thanks for the package it has saved my life in other projects :)

**Comment by tolu360** [comment]
That could be because you may have pulled in a very old version of `React` through `Cocoapods` - in addition to having the block you referenced in your `Podfile`, you should also ensure `Cocoapods` look for `React` in your `node_modules` directory by including the following in your target block as in the docs:

```ruby
pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTSettings',
    'RCTAnimation',
    'RCTLinkingIOS'
  ]

  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'react-native-google-places', :path => '../node_modules/react-native-google-places'
```
Exit `Xcode`, reinstall your dependencies by running `pod deintegrate` followed by `pod install`, rebuild your app. Let me know if doing this fixes things for you.

**Comment by wmonecke** [comment]
@tolu360 Hi! Thanks for coming to the rescue. It seems its working now :) I just found it a bit werid to add React as a pod and thought you only needed the `'react-native-google-places'` pod. 

Thanks for the great package again! And for your help!

**Comment by tolu360** [comment]
You are welcome @wmonecke, so the `react-native-google-places` pod lists `React` as one of its dependencies but I notice `Cocoapods` pulls in an older version (0.11.0 or so) and that messes things up as it is so outdated. And the other lines added help to clean up duplicate modules. I would like to explore how to further clean up the installations while using a `podspec`.

**Comment by wmonecke** [comment]
@tolu360 What about manual Linking? The usual adding to `Library`  and `Link Binary with Libraries`?

**Comment by tolu360** [comment]
I got several feature requests and even PRs to favor automatic flow via `Cocoapods` over manual linking and that also seem to be the most consistent across other libraries, so I thought it makes sense to support the flow here too. Doing this would mean, you don't have to worry about manual linking at all.
