### ISSUE TITLE
RNGooglePlaces.getAutocompletePredictions latitude and longitude 

### ISSUE THREAD

**Issue by eman1000** [tolu360/react-native-google-places#25]
Hie I have another question this function does not return latitude and longitude values?
RNGooglePlaces.getAutocompletePredictions()

**Comment by tolu360** [comment]
Hi @eman1000, `getAutocompletePredictions()` should be used with `lookUpPlaceById()` in most cases (* please read the README for more info *). `getAutocompletePredictions()` returns an array of suggestions of the form:

```javascript
[ { primaryText: 'Facebook HQ',
    placeID: 'ChIJZa6ezJa8j4AR1p1nTSaRtuQ',
    secondaryText: 'Hacker Way, Menlo Park, CA, United States',
    fullText: 'Facebook HQ, Hacker Way, Menlo Park, CA, United States' },
    types: [ 'street_address', 'geocode' ],
    ...
]
```

Call `lookUpPlaceById('ChIJZa6ezJa8j4AR1p1nTSaRtuQ')` - (* notice I passed in the `placeID` from above *) to get the place details.

**Comment by eman1000** [comment]
Ow okk thanks, let me try it out.

**Comment by mbbarry91** [comment]
does this lookPlaceById works with android

**Comment by vietmobilefolk** [comment]
@tolu360 I think you should include lat, lng info on getAutocompletePredictions api. Because app usually show list of places and distance to current location. Better just calculate distance from 
first result than make another api call and calculate it.
