### ISSUE TITLE
Set location on maps after selecting autocomplete place or suggestion place

### ISSUE THREAD

**Issue by agungjk** [tolu360/react-native-google-places#26]
How to set location on maps after selecting autocomplete place or suggestion place? 
So my user can repositioning location in maps?
Thank you

**Comment by tolu360** [comment]
Hi @agungjk, I don't quite understand your question. Which of the widgets are you using in your project? Each of the widgets would return `longitude` and `latitude` as part of the response, you can use that to set the location on a map.

If you think I have misread your question, please make the question clearer.
