### ISSUE TITLE
[Solved] react-native-google-places:compileReleaseJavaWithJavac FAILED assembling release

### ISSUE THREAD

**Issue by brownieboy** [tolu360/react-native-google-places#266]
Building a release Android version of my app by running `./gradlew assembleRelease` choked on this line for me:

> Task :react-native-google-places:compileReleaseJavaWithJavac FAILED
> /Users/michaelbrown/Development/manlyhappyhour/apps/manly-happy-hour/node_modules/react-native-google-places/android/src/main/java/com/arttitude360/reactnative/rngoogleplaces/RNGooglePlacesPlaceFieldEnum.java:4: error: package android.support.annotation does not exist
> import android.support.annotation.Nullable;

**Comment by brownieboy** [comment]
This is an AndroidX issue.   The quick fix was to run `react-native run-android` immediately _before_ trying to assemble a release version.

You don't need to let `react-native run-android` run to finish either.   As soon as you see a line like this:

> Jetifier found 2667 file(s) to forward-jetify. Using 4 workers...

you can `ctrl->c` out of the `react-native` command and then try `/gradlew assembleRelease` again.

**Comment by NathHorrigan** [comment]
It's easier to just run: `npx jetify`
