### ISSUE TITLE
Place Picker doesn't prioritize by location when searching

### ISSUE THREAD

**Issue by smakazmidd** [tolu360/react-native-google-places#27]
When using the AutocompleteModal, things work as expected but when searching in the Place Picker Modal, results are not sorted by distance to current location.

**Comment by tolu360** [comment]
Hi @smakazmidd, first off, please note that **none** of the widgets does allow for results `sorting`, only `filtering` by `place type`, `geo-bounds (latlng & radius)`, `country` - this is everything the underlying `SDKs` support as of now.

You can call `openPlacePickerModal()` with no `arguments` to base off suggestions to places `nearest` to the device's current location (`latlng`). Hope this helps.

**Comment by smakazmidd** [comment]
Hi @tolu360 ,
What you're saying is partially correct. PlaceAutocomplete indeed sorts results nearest to the supplied location if all parameters are provided. However, the autocomplete search inside the PlacePicker doesn't exhibit the same behavior. 

Because of this I had to combine PlaceAutocomplete from this package with Maps from Airbnb to create my own PlacePicker.

**Comment by tolu360** [comment]
Nice. Good combination!

`getAutocompletePredictions()` was, indeed, provided to make it easy to build out custom search UIs and views.
