### ISSUE TITLE
[QUESTION] Is this repo still being maintained?

### ISSUE THREAD

**Issue by robertqin86** [tolu360/react-native-google-places#277]
@tolu360 is no longer responding to PRs or issues or creating releases. I thank him very much for this repo and the earlier help it has given me. But I think its good to give an update to the community on whether there are plans to maintain this repo moving forward and whether we should consider alternatives or forks instead.

**Comment by tolu360** [comment]
Hi Qin Zhengquan, @robertqin86, I am not convinced this is warranted just yet! While I understand your seeming frustration, this action reeks of blackmail in my book and it's particularly unfair to anyone sharing their work, free of charge, with the world! You could have shown more understanding and restraint - no new releases, not merging in PRs and all, are **not signs** a library is no longer maintained - all of the above could mean everything works or that the author or maintainer got really swamped with work in the meantime. The only way to know that a library is no longer maintained is the author putting up a notice to that effect!

As grown-ups that we are, we can all do what's best for our projects or work - you could already do either or all of your options **without a community survey or approval** - you could already consider alternatives or forks, or even install from a PR branch! Seeing as you know what goes into offering any LOCs for free and supporting other people using it, then you already know it goes beyond the click of a button. So **this is still maintained** and if you wish to stick to using it, I can enlist your help - if you'd oblige, you can **review and test** all recently created PRs, merge them, re-submit a single PR containing all.   
I would be waiting for that combined PR from you, and please submit such against the V4 branch (would be creating that shortly). Hope this clears the air enough for you and anybody else who shares your concerns. I would be closing this too.
Cheers!!

**Comment by robertqin86** [comment]
Hi @tolu360, sorry for the misunderstanding. I'm not frustrated at all and I did thank you for your contributions and acknowledged how you have helped me. I just wanted clarity on whether there are plans to maintain this repo moving forward, and whether there are alternatives we should use instead. You are obviously not obligated to maintain this repo at all, and I apologise if my question came across as being rude or gave you the impression I was black mailing you.  Thank you very much for your clarifications as well.

**Comment by tolu360** [comment]
All is fine now @robertqin86, I am glad we got this out of the way - let's get to work and keep helping the next guy! You are very welcome too. Would you like to help with the combined PR to the new v4 branch though?

**Comment by jdegger** [comment]
@tolu360 is it time to reopen this discussion?

**Comment by Dag0n** [comment]
@tolu360 anything on this? It’s been 7 months and pull requests waiting for over a year now.
