### ISSUE TITLE
is possibile to style the navigation bar?

### ISSUE THREAD

**Issue by scerelli** [tolu360/react-native-google-places#3]
Is possibile to style the navigation bar inside the modal opened when you `openPlacePickerModal`

**Comment by tolu360** [comment]
Hi @scerelli, I have not come across customization docs for the underlying SDKs and I doubt that exists. Would close this now, it can, and would be re-opened if and when I get more facts about customizing the UI.

**Comment by temitope** [comment]
@scerelli  @tolu360  note: only seeing the possibility [on android](https://developers.google.com/places/android-api/placepicker#custom-theme) so far
