### ISSUE TITLE
'GooglePlaces/GooglePlaces.h' file not found

### ISSUE THREAD

**Issue by toystars** [tolu360/react-native-google-places#30]
After installing the package and manually adding `Google Places` sdk (without pod), running the app throws an error. Below is a screenshot of the error. The `GooglePlaces` header file can be accessed from my appDelegate.m file.

RN version: 0.36.1
react-native-google-places version: 0.8.8
Google Places sdk version: 2.2

<img width="843" alt="screen shot 2017-03-22 at 6 30 27 pm" src="https://cloud.githubusercontent.com/assets/16062709/24211875/ae947090-0f2d-11e7-83f3-4d0fa2d4d1ba.png">

**Comment by tolu360** [comment]
For `RN <= 0.40`, upgrade `react-native-google-places` to `1.0.9`, clean and build again.

**Comment by toystars** [comment]
@tolu360 thanks for the prompt response. But I already used that version and I got same error. Could it be because I added `Google Places` sdk manually?

**Comment by tolu360** [comment]
Yes @toystars, that must be why. The library knows how to look for the header paths to the Pod files but that would break since you pulled it in manually. Why not try the pod approach?

**Comment by toystars** [comment]
@tolu360 so i ended up using Pod and it works as expected. Thanks a lot

**Comment by tolu360** [comment]
You are welcome Tunde, am happy you got it working! Cheers!

**Comment by NorbertCU** [comment]
I'm having the same issue. The problem is that I'm having troubles using Pod because it conflicts with other libraries in the project. Is there any way to use it without Pod?
