### ISSUE TITLE
Execution failed for task ':app:transformClassesWithDexForDebug'.

### ISSUE THREAD

**Issue by manhhp** [tolu360/react-native-google-places#31]
When i'm building my app for debug, i got this type of error, please give some solution

Running dex in-process requires build tools 23.0.2.
For faster builds update this project to use the latest build tools.
Dex: Error converting bytecode to dex:WithDexForDebug
Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/location/places/zzl;
    UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/location/places/zzl;
    at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
   at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
   at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
       at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
    at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
     at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
 at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
       at com.android.dx.command.Main.main(Main.java:106)

:app:transformClassesWithDexForDebug FAILED

**Comment by tolu360** [comment]
@manhhp, are you using any other library which pulls in `Google Play Services` in your project? This look like a version conflict to me. 

Try to run a project clean up:
```gradle
cd android && ./gradlew clean
```
I would be pushing some updates to the android dependencies shortly though.

**Comment by manhhp** [comment]
@tolu360, i'm using your libary with airbnb/react-native-maps. I have tried to run a project clean up, but i still got error

**Comment by rnaffer** [comment]
@manhhp I was facing the same issue. Looking in the troubleshooting section of docs, i notice that the play-services-location and play-services-palces dependencies must be in the build.gradle file, and it's working now.

Hope it works for you.

**Comment by tolu360** [comment]
@manhhp, I just published `react-native-google-places@2.1.0` to npm - upgrade your dependencies. Things should work just fine with `react-native-maps`.

Cheers

**Comment by manhhp** [comment]
@tolu360, thank you so much, your works is amazing!

Cheers

**Comment by DarkLicornor** [comment]
Hi, i currently have the same problem, despite having updated to 2.1.0 .
Here is a part of my build.gradle : 
`compile(project(':react-native-maps')){
       exclude group: 'com.google.android.gms', module: 'play-services-base'
       exclude group: 'com.google.android.gms', module: 'play-services-maps'
       exclude group: 'com.google.android.gms', module: 'play-services-places'
       exclude group: 'com.google.android.gms', module: 'play-services-location'
    }

    compile(project(':react-native-google-places')){
       exclude group: 'com.google.android.gms', module: 'play-services-base'
       exclude group: 'com.google.android.gms', module: 'play-services-maps'
       exclude group: 'com.google.android.gms', module: 'play-services-places'
       exclude group: 'com.google.android.gms', module: 'play-services-location'
    }
    compile 'com.google.android.gms:play-services-base:10.0.1'
    compile 'com.google.android.gms:play-services-maps:10.0.1'
    compile 'com.google.android.gms:play-services-auth:10.0.1'
    
    // Used by react-native-google-places
    compile 'com.google.android.gms:play-services-location:10.0.1'
    compile 'com.google.android.gms:play-services-places:10.0.1'`

I also tried : 

`compile(project(':react-native-maps')){
       exclude group: 'com.google.android.gms', module: 'play-services-base'
       exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }

compile(project(':react-native-google-places')){
    exclude group: 'com.google.android.gms', module: 'play-services-base'
    exclude group: 'com.google.android.gms', module: 'play-services-places'
    exclude group: 'com.google.android.gms', module: 'play-services-location'
 }

   compile 'com.google.android.gms:play-services-base:10.0.1'
    compile 'com.google.android.gms:play-services-maps:10.0.1'
    compile 'com.google.android.gms:play-services-auth:10.0.1'

    // Used by react-native-google-places
    compile 'com.google.android.gms:play-services-location:10.0.1'
    compile 'com.google.android.gms:play-services-places:10.0.1'
`

Thanks for any help.

**Comment by tolu360** [comment]
Hello @DarkLicornor, provided you are using the newest versions of both `react-native-maps` and `react-native-google-places`; clear out any specific api versioning from your `build.gradle` leaving just the `compile` lines like so:

```gradle
dependencies {
    compile project(':react-native-google-places')
    / ...other dependencies here.../
}
```

**Comment by DarkLicornor** [comment]
Thanks a lot !

**Comment by hoainamcr** [comment]
Hi guys,

I have same issue, I can't build when add `react-native-google-places`  I don't know what to do, though I did `cd android && ./gradlew clean` please help me how to fix it.
Error

```
Note: D:\project\xxx\xxx\android\app\src\main\java\com\app\MainApplication.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources
:app:transformClassesWithDexForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/firebase/iid/zzb;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4 mins 19.887 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
```

Config files

**package.json**

```
"@mapbox/polyline": "^0.2.0",
    "firebase": "^4.6.0",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.47.2",
    "react-native-google-places": "^2.4.2",
    "react-native-google-signin": "^0.12.0",
    "react-native-maps": "^0.17.1",
```

**setting.gradle**

```
rootProject.name = 'app'
include ':react-native-google-signin'
project(':react-native-google-signin').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-google-signin/android')
include ':react-native-google-places'
project(':react-native-google-places').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-google-places/android')
include ':react-native-maps'
project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/lib/android')

include ':app'
```

**build.gradle**


```
dependencies {
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"
    compile project(':react-native-google-places')
    compile(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    compile(project(":react-native-google-signin")){
        exclude group: "com.google.android.gms"
    }
    // Map
    compile 'com.google.android.gms:play-services-base:10.2.0'
    compile 'com.google.android.gms:play-services-maps:10.2.0'
    // Google sign in
    compile 'com.google.android.gms:play-services-auth:10.2.0'
    compile(project(':react-native-fbsdk')) {
        exclude(group: 'com.facebook.android', module: 'facebook-android-sdk')
    }
    compile('com.facebook.android:facebook-android-sdk:4.22.1')
}
apply plugin: 'com.google.gms.google-services'
```


and foloww tutorial add mainapplication.java

```
import com.arttitude360.reactnative.rngoogleplaces.RNGooglePlacesPackage;

@Override
protected List<ReactPackage> getPackages() {
  return Arrays.<ReactPackage>asList(
      new MainReactPackage(),
      ...
      new RNGooglePlacesPackage() //<-- Add line
  );
}
```

Please help me how to fix it. thanks all so much.

**Comment by hoainamcr** [comment]
I builded by
```
dependencies {
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"
    compile project(':react-native-linear-gradient')
    compile project(':react-native-blur')
    compile project(':react-native-vector-icons')
    compile project(':react-native-image-picker')
    compile(project(':react-native-google-places')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-places'
        exclude group: 'com.google.android.gms', module: 'play-services-location'
    }
    compile(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    compile(project(":react-native-google-signin")){
        exclude group: "com.google.android.gms"
    }
    // Map
    compile 'com.google.android.gms:play-services-base:11.+'
    compile 'com.google.android.gms:play-services-maps:11.+'
    // Google sign in
    compile 'com.google.android.gms:play-services-auth:11.+'
    // Places
    compile 'com.google.android.gms:play-services-location:11.+'
    compile 'com.google.android.gms:play-services-places:11.+'
    compile(project(':react-native-fbsdk')) {
        exclude(group: 'com.facebook.android', module: 'facebook-android-sdk')
    }
    compile('com.facebook.android:facebook-android-sdk:4.22.1')
}
apply plugin: 'com.google.gms.google-services'
```

**Comment by moseslucas** [comment]
running 
`cd android && ./gradlew clean` did the trick for having the 
`Error: com.google.common.util.concurrent.UncheckedExecutionException` Error

Thanks !

**Comment by sarmad1995** [comment]
I added this in `android/app/build.gradle`
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.getRequested().getGroup() == 'com.google.android.gms') {
            details.useVersion('9.8.0')
        }
    }
}
