### ISSUE TITLE
Execution failed for task ':react-native-google-places:compileReleaseJavaWithJavac'.

### ISSUE THREAD

**Issue by amlcodes** [tolu360/react-native-google-places#33]
while running react-native run-android

```:react-native-google-places:generateReleaseSources UP-TO-DATE
:react-native-google-places:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:react-native-google-places:compileReleaseJavaWithJavac
:react-native-google-places:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
C:\Users\alex\Desktop\chat-mobile\node_modules\react-native-google-places\android\src\main\java\com\arttitude360\reactnative\rngoogleplaces\RNGooglePlacesModule.java:42: error: RNGooglePlacesModule is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener
public class RNGooglePlacesModule extends ReactContextBaseJavaModule implements ActivityEventListener, GoogleApiClient.ConnectionCallbacks, GoogleApiClient.OnConnectionFailedListener {
       ^
C:\Users\alex\Desktop\chat-mobile\node_modules\react-native-google-places\android\src\main\java\com\arttitude360\reactnative\rngoogleplaces\RNGooglePlacesModule.java:82: error: method does not override or implement a method from a supertype
    @Override
    ^
C:\Users\alex\Desktop\chat-mobile\node_modules\react-native-google-places\android\src\main\java\com\arttitude360\reactnative\rngoogleplaces\RNGooglePlacesModule.java:448: error: method does not override or implement a method from a supertype
    @Override
    ^
3 errors
:react-native-google-places:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-google-places:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 19.835 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html```

**Comment by tolu360** [comment]
@amlcodes, what versions of `RN` and `react-native-google-places` are you working on at the moment?

**Comment by amlcodes** [comment]
```  "dependencies": {
    "@expo/ex-navigation": "~2.9.2",
    "@expo/samples": "~1.0.3",
    "axios": "^0.15.3",
    "expo": "^15.0.2",
    "moment": "^2.18.1",
    "react": "~15.4.0",
    "react-native": "https://github.com/exponent/react-native/archive/sdk-15.0.0.tar.gz",
    "react-native-elements": "^0.10.2",
    "react-native-extended-stylesheet": "^0.3.2",
    "react-native-google-places": "^2.0.9",
    "react-native-modal-datetime-picker": "^4.1.0",
    "redux-form": "^6.5.0",
    "redux-promise-middleware": "^4.2.0"
  },
  "devDependencies": {
    "jest-expo": "~0.3.0",
    "redux-logger": "^2.8.2"
  }
}```

**Comment by tolu360** [comment]
Not so easy to tell the version of `RN` in your version of `exponent`. I have some updates lined up on my end though, things were pretty much in order till `RN 0.41+` - would check and get back to you.

**Comment by amlcodes** [comment]
@tolu360 so wait for your update? and its version 0.42

**Comment by tolu360** [comment]
Alright @amlcodes, wait a day or two. Would try and test against 0.42 and 0.43

**Comment by amlcodes** [comment]
this is an error while working with expo, i will close this for now

**Comment by tolu360** [comment]
Thanks for the feedback

**Comment by r3nya** [comment]
Hey @tolu360!

I have this problems again. :(

```
"react": "16.0.0-alpha.6",
"react-native": "0.44.0",
"react-native-google-places": "2.1.0",
```

**Comment by artps** [comment]
Same problem here.

Look at the error: `error: RNGooglePlacesModule is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener`

> `onActivityResult(int,int,Intent)`

But [here](https://github.com/tolu360/react-native-google-places/blob/master/android/src/main/java/com/arttitude360/reactnative/rngoogleplaces/RNGooglePlacesModule.java#L83) is: `onActivityResult(Activity, int, int, Intent)` which is correct for 0.40+.

I'm not really aware of android builds, but look what I've found in logs:

```
Download https://jcenter.bintray.com/com/facebook/react/react-native/0.20.1/react-native-0.20.1.pom
```

And RN 0.20.1. [has correct method signature](https://github.com/facebook/react-native/blob/0.20-stable/ReactAndroid/src/main/java/com/facebook/react/bridge/ActivityEventListener.java#L15).

What am I missing? [Could it be problem?](https://github.com/tolu360/react-native-google-places/blob/master/android/build.gradle#L22)

```
dependencies {
    compile 'com.facebook.react:react-native:+'
    compile 'com.google.android.gms:play-services-base:10.2.0'
    compile 'com.google.android.gms:play-services-places:10.2.0'
    compile 'com.google.android.gms:play-services-location:10.2.0'
    compile 'com.google.maps.android:android-maps-utils:0.3.4'
}
```

Best,
Art

**Comment by r3nya** [comment]
Oh … @tolu360 I fixed this problem. It was my mistake. :)
Everything is ok.

**Comment by tolu360** [comment]
Alright @r3nya and @artps, thanks for the feedback guys!

**Comment by RameshkrishnanV** [comment]
I m also facing this issue.

**Comment by gangashripatil** [comment]
Hi all am getting error while running react-native run-android - :
react-native-google-places:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
\node_modules\react-native-google-places\android\src\main\java\com\arttitude360\reactnative\rngoogleplaces\RNGooglePlacesModule.java:321: error: cannot find symbol
        List<Object> placeIDsObjects = placeIDs.toArrayList();
                                               ^
  symbol:   method toArrayList()
  location: variable placeIDs of type ReadableArray
1 error
:react-native-google-places:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-google-places:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by suulola** [comment]
Had this error as well but running `npx jetify` at the root of the project file

or adding 
```
script {
"postinstall": "jetify",
...
}
```
to my package.json resolved the error for me
