### ISSUE TITLE
Input and result list style

### ISSUE THREAD

**Issue by brascene** [tolu360/react-native-google-places#34]
Hi and thank you very much for this repo. Is there an option to modify styles of rendered list, like with renderRow or similar? Thanks!

**Comment by tolu360** [comment]
@brascene, unfortunately the default Google styles cannot really be so customized. You can build your own result list and search input though, see Using [Your Own UI](https://github.com/tolu360/react-native-google-places#using-your-own-custom-uiviews) in the README with `RNGooglePlaces.getAutocompletePredictions()`

**Comment by brascene** [comment]
I see.. I've been using another wrapper for google places api, the one from Farid Safi, but that one does not separate the usage of google apis for android and ios apps, instead, it's using google web api and serves back the data which is then used in listviews with custom properties. However, I found your library better since it allows to use restricted google apis.

**Comment by tolu360** [comment]
Hi @brascene, you still get to use your restricted API keys while calling `RNGooglePlaces.getAutocompletePredictions()` and then you get to use your own custom UI elements. I'd close this now, feel free to re-open if you have other concerns.

Cheers.
