### ISSUE TITLE
Filter Multiple Countries

### ISSUE THREAD

**Issue by BlueBeetle13** [tolu360/react-native-google-places#36]
Can you allow us to enter an array to filter my multiple countries such as:

```
RNGooglePlaces.getAutocompletePredictions(text, { type: 'cities', country: ['ca', 'us'] })...
```

**Comment by tolu360** [comment]
@BlueBeetle13 - Unfortunately, the underlying native APIs on [android](https://developers.google.com/android/reference/com/google/android/gms/location/places/AutocompleteFilter.Builder#setCountry(java.lang.String)) and [ios](https://developers.google.com/places/ios-api/reference/interface_g_m_s_autocomplete_filter), do not allow for an `array` to be passed as the country filter - both only take `strings`. You can only confine your searches to a country at a time.

Cheers!
