### ISSUE TITLE
the map appears empty on ios

### ISSUE THREAD

**Issue by HananeAlSamrout** [tolu360/react-native-google-places#37]
the map appears empty on ios
i can see the marker and the pinned places but without route

**Comment by vbaranov** [comment]
I am facing with the same issue.
iOS 9.x, 10.x.

**Comment by tolu360** [comment]
So @HananeAlSamrout and @vbaranov - only one thing comes to mind, your API key being passed to the setup methods in your `AppDelegate.m` needs to have `Google Map` permissions. Please review your API permissions in the developer console, and then rebuild.

```Objective-C
[GMSPlacesClient provideAPIKey:@"YOUR_IOS_API_KEY_HERE"];
[GMSServices provideAPIKey:@"YOUR_IOS_API_KEY_HERE"];
```

**Comment by tolu360** [comment]
I'd take it that solved the issues for you @vbaranov? As soon as @HananeAlSamrout also confirms, we can close this.

Cheers, guys!

**Comment by vbaranov** [comment]
Yes, this is permissions only problem. It is solved for me. Thanks, @tolu360!
