### ISSUE TITLE
Could not Invoke RNGooglePlaces.openplacePickerModal

### ISSUE THREAD

**Issue by scerelli** [tolu360/react-native-google-places#4]
Hi @tolu360 ! and thanks for this component, is quite useful. 
The only problem I've using it is that while on IOS everything works fine on android when i try to invoke `openPlacePickerModal` on `RNGooglePlaces` `react-native` returns an error.

Here is the error:
![screenshot](https://cloud.githubusercontent.com/assets/4821190/20224440/c4f4392a-a83e-11e6-8f12-163d67408bc4.png)

I tried to inspect your java module but didn't find anything yet.

What i did so far:
- created api keys
- placed keys in meta inside xml
- added permission for fine location
- did `react-native link your-package-name`
- double checked that everythings was imported (in `build.gradle`, `MainApplication.java` etc. etc.)
-  i even tried to ask permission before invoke `openPlacePickerModal`becuase i tought was a permission problem.

so this is my code so far:
```
async openSearchModal() {
    if(Platform.OS === 'android') {
      try {
        let granted = await PermissionsAndroid.requestPermission(PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION)
        if (!granted) {
          return false
        }
      } catch (err) {
        console.warn(err)
        return false
      }
    }

    RNGooglePlaces.openPlacePickerModal()
    .then((place) => {
        console.log(place)
        // place represents user's selection from the
        // suggestions and it is a simplified Google Place object.
    })
    .catch(error => console.log(error.message))  // error is a Javascript Error object
  }
```

removing the permission related code doesn't resolve the error.
Everything is being tested on real device.

One Plus One,
Android 6.0

**Comment by tolu360** [comment]
Hello @scerelli, I'd try and look things over this weekend, first to see if I can reproduce your issue and then to see if newer versions of RN may have introduced any breaking changes.

To start with, ensure you are running, at least `RN 0.33`, and moving forward, I'd only try to make the package work with only the latest version of RN, owing to the rapid way the core APIs for RN seem to change. As such, I suggest you should be on the very latest stable version of RN.

In any case, expect an update soon, thanks.

**Comment by tolu360** [comment]
So @scerelli, just to update you. I have just pushed a minor update to the package. Start by updating to `0.8.2`, doing so would bring your app build to a more recent version of the `Google Play Services`. Also ensure you update your `android` build environment via the `Android SDK Manager`. Get at least `Google Play Services rev. 37`. See below:

<img width="692" alt="screen shot 2016-11-12 at 3 43 22 pm" src="https://cloud.githubusercontent.com/assets/3914854/20238601/6c80921e-a8ef-11e6-89e9-e659714e8bd1.png">

That should be all the 'house keeping' you may need to do to make things work on android. I have tested this new release in `RN versions 0.33 and 0.37` and on the `Android Emulator` and on a physical `Samsung Galaxy S6 edge` and everything works as expected. See below:

Emulator: 

![screenshot_1478959269](https://cloud.githubusercontent.com/assets/3914854/20238627/1dab683e-a8f0-11e6-9f2a-0361e3ae2c5f.png)

Physical Samsung...

![screenshot_20161112-151804](https://cloud.githubusercontent.com/assets/3914854/20238631/2e3b590c-a8f0-11e6-894f-71b8666add9a.png)

PS: Unlink the package (`react-native unlink react-native-google-places`). Update the package (`npm install --save react-native-google-places@0.8.2`) and relink with your app (`react-native link react-native-google-places). Build and run your app (`react-native run-android`). Cheers.

**Comment by ganjarsetia** [comment]
@tolu360 I have the same problem `could not invoke...` everytime I use with this module [https://github.com/rebeccahughes/react-native-device-info](https://github.com/rebeccahughes/react-native-device-info) I think its conflict. If I remove react-native-device-info the module is working again.

Also, your plugin is crash when run in Xiaomi redmi note 3.
I'm using react native 0.34 & this latest plugin (v0.8.2)

**Comment by tolu360** [comment]
Hi @ganjarsetia, your conflict might be that of Google Play Services but I'm not so sure right now. Lets do a quick debugging together:

* Open up `node_modules/react-native-device-info/android/build.gradle` and change the last line to `compile `'com.google.android.gms:play-services-gcm:9.6.0'`.
* Run `react-native run-android` to rebuild and recompile your app. Try to use both packages together after the changes.

**Comment by scerelli** [comment]
The problem is related to the Google Play Services version. I updated it on my fork and everything works smoothly now.

**Comment by tiarachmad** [comment]
I have the same problem as @ganjarsetia . I'm using xiaomi redmi note 3 (snapdragon version). When I use openPlacePickerModal() method my apps is force closing without leaving any error message. I'm using RN 0.34.0, your latest plugin version (0.8.2) and installed latest Google Play Service on my Android SDK.
Sorry for the bad english.

**Comment by ganjarsetia** [comment]
@tolu360 Sorry for late reply. I already follow your instruction. Still same error.
Your module is crash on xiaomi redmi note 3. Should I create new issue?

**Comment by jsonmurphy** [comment]
I was able to solve this problem by explicitly adding a dependency on `com.google.android.gms:play-services-places:9.8.0`. it seems the `PlacePicker` class is no longer a part of the `com.google.android.gms:play-services-location` package.

Source: http://stackoverflow.com/questions/38063648/cannot-import-google-places-placepicker-into-android-project

**Comment by tolu360** [comment]
Hi @jsonmurphy, thank you for sharing that, I'd update the package shortly.
