### ISSUE TITLE
react-native-google-places clinching with react-native-fcm

### ISSUE THREAD

**Issue by rasmniel** [tolu360/react-native-google-places#45]
Hello @tolu360 

We are currently building an application, which uses your `react-native-google-places` library. We have only been using the `getAutocompletePredictions` function to produce our own in-app dropdown with suggestions. So far everything has been running smoothly.

We then decided to use push notifications with Firebase using the `react-native-fcm` library, which has also gained huge traction of late. This has resulted in an error, which breaks the functionality we use from `react-native-google-places`.

The error is vaguely described as "Could not invoke RNGooglePlaces.getAutocompletePredictions" on the infamous red background.

![screenshot_20170518-193619](https://cloud.githubusercontent.com/assets/11680653/26215658/879fdf32-3c01-11e7-919c-6e53cd38f93e.png)

What we have tried so far:
- Uninstalled `react-native-fcm` library, which solved the `getAutocompletePredictions` problem, but leaves us back at square one regarding push notifications, so that's not really a viable fix.
- Tried calling other functions in your library; `openPlacePickerModal`, `openAutocompleteModal` - which all behave as expected, but their usage is not what we are looking for, so those functions are not preferred solutions either.
- Messed around with build configurations; reordering import, compile, and dependency lines, and tried different makeshift solutions we could track down with google. All to no avail.
- Read through issue #4, which looks fairly similar to our problem, but the suggested fixes in that thread either doesn't work or are not applicable to our project.

The project has only been run on Android, on both Nexus 5x and Samsung Galaxy 7 Edge. Neither of the phones produce the result we want. We have yet to run anything on iOS, but we need it to run on Android regardless.

Do you have any knowledge about this bug, or are you able to take a look and give us a hint?
Thank you very much in advance.

Let me know, if you need any further information regarding the bug.

**Comment by tolu360** [comment]
Hey @rasmniel, so if I gather correctly, the error is only thrown when you call `getAutocompletePredictions ()`? All other APIs work just fine?

The first place I would look would be the versions of `Google PlayServices` being pulled in by `react-native-fcm` and `react-native-google-places` (10.2.0). This bug may well be a conflict in `GPS` versions from the two packages.

First ensure you are on the very latest release of this package (2.1.0) and try to lock the `gcm` requirement for `react-native-fcm` to the same 10.2.0 in your `android/app/build.gradle` by adding the force flag:

```groovy
dependencies {
     // other packages here
     compile ('com.google.android.gms:play-services-gcm:10.2.0') {
        force = true;
     }
}
```
Clean your project and try to build and run again:

```bash
cd android && ./gradlew clean
```
Lets start here and see if anything changes. Cheers!

**Comment by rasmniel** [comment]
I have the latest version (2.1.0) of the `react-native-google-places` package. The dependency line you suggested wasn't even in our `android/app/build.gradle` - let alone the `force = true` flag, albeit both packages still worked fine when installed separately.

In this configuration `gradlew assembleDebug` ends abruptly with
`
:app:processDebugGoogleServices
Found com.google.android.gms:play-services-gcm:10.2.0, but version 10.0.1 is needed for the google-s
ervices plugin.
:app:processDebugGoogleServices FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (info
rmation about the latest version is available at https://bintray.com/android/android-tools/com.googl
e.gms.google-services/) or updating the version of com.google.android.gms to 10.0.1.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more l
og output.

BUILD FAILED
`

It seems that some Google Services dependency is certainly the culprit here. The odd thing is that the version required is lower than the forced one. Perhaps either of the packages are attempting to lock the version internally?

This is the `android/app/build.gradle` dependency list:
`
dependencies {
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.facebook.react:react-native:+"
    compile "com.android.support:appcompat-v7:23.0.1"
    compile 'com.google.firebase:firebase-core:10.0.1'
    compile project(':react-native-google-places')
    compile project(':react-native-fcm')
    compile ('com.google.android.gms:play-services-gcm:10.2.0') {
        force = true;
    }
}
`

I'm hoping I'm shedding a bit more light on the issue. Thanks for the snappy response!

**Comment by tolu360** [comment]
So it is most likely Play Services version conflict, but if we are trying to lock down versions to 10.2.0, you can't pull in `firebase-core@10.0.1` at the same time. Try instead:

```groovy
dependencies {
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.facebook.react:react-native:+"
    compile "com.android.support:appcompat-v7:23.0.1"
    compile 'com.google.firebase:firebase-core:10.2.0'
    compile project(':react-native-google-places')
    compile project(':react-native-fcm')
    compile ('com.google.android.gms:play-services-gcm:10.2.0') {
        force = true;
    }
}
```
Once again, clean and try to build again.

**Comment by rasmniel** [comment]
I didn't even consider the `firebase-core` version to be incorrect here. I'm assuming it was just installed automatically with `react-native-fcm`, so I didn't consider the `10.0.1` version to be anything but coincidental.

I've updated the `firebase` version to `10.2.0`, cleaned and built from scratch. This time there are no error messages in the build process and the app runs smoothly, but the same `RNGooglePlaces.getAutocompletePredictions` error still persists, when attempting to invoke the function.

I apologize for being unable to produce any more helpful error messages.

**Comment by tolu360** [comment]
Hey @rasmniel, is this still an issue? Perhaps we should re-visit it.

Can you get `stack trace` for the crash from `Android Studio` or from your terminal? To copy logs from the terminal, build and run your app normally, then run on your terminal the command below just before you invoke `getAutocompletePredictions()` or do your autocomplete search :

```bash
adb logcat
```
As soon as the crash occurs, you can `Ctrl  + C` to stop the logs and look for lines starting from the crash to the reported causes (may report more than one) e.g.

```
Fatal Exception: java.lang.RuntimeException: Could not invoke RNGooglePlaces.getAutocompletePredictions ......

Caused by ....

Caused by .....
```
Getting the monitor logs would help us unravel this. Cheers.

**Comment by rasmniel** [comment]
Hello @tolu360
It is indeed still an issue for us.
As I have little to no experience using `logcat`, I will just send you the bulk of it. I tried to cut the most relevant part from the point you mentioned, but notice that the error does in fact not start with words `Fatal Exception`.

```
...
05-23 20:16:40.989  3544  3873 E unknown:React: Exception in native call
05-23 20:16:40.989  3544  3873 E unknown:React: java.lang.RuntimeException: Could not invoke RNGooglePlaces.getAutocompletePredictions
05-23 20:16:40.989  3544  3873 E unknown:React:         at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:359)
05-23 20:16:40.989  3544  3873 E unknown:React:         at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:141)
05-23 20:16:40.989  3544  3873 E unknown:React:         at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
05-23 20:16:40.989  3544  3873 E unknown:React:         at android.os.Handler.handleCallback(Handler.java:751)
05-23 20:16:40.989  3544  3873 E unknown:React:         at android.os.Handler.dispatchMessage(Handler.java:95)
05-23 20:16:40.989  3544  3873 E unknown:React:         at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
05-23 20:16:40.989  3544  3873 E unknown:React:         at android.os.Looper.loop(Looper.java:154)
05-23 20:16:40.989  3544  3873 E unknown:React:         at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
05-23 20:16:40.989  3544  3873 E unknown:React:         at java.lang.Thread.run(Thread.java:761)
05-23 20:16:40.989  3544  3873 E unknown:React: Caused by: java.lang.reflect.InvocationTargetException
05-23 20:16:40.989  3544  3873 E unknown:React:         at java.lang.reflect.Method.invoke(Native Method)
05-23 20:16:40.989  3544  3873 E unknown:React:         at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:345)
05-23 20:16:40.989  3544  3873 E unknown:React:         ... 8 more
05-23 20:16:40.989  3544  3873 E unknown:React: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzbxn;
05-23 20:16:40.989  3544  3873 E unknown:React:         at com.google.android.gms.location.places.AutocompletePredictionBuffer.get(Unknown Source)
05-23 20:16:40.989  3544  3873 E unknown:React:         at com.google.android.gms.location.places.AutocompletePredictionBuffer.get(Unknown Source)
05-23 20:16:40.989  3544  3873 E unknown:React:         at com.google.android.gms.common.data.zzb.next(Unknown Source)
05-23 20:16:40.989  3544  3873 E unknown:React:         at com.arttitude360.reactnative.rngoogleplaces.RNGooglePlacesModule.getAutocompletePredictions(RNGooglePlacesModule.java:291)
05-23 20:16:40.989  3544  3873 E unknown:React:         ... 10 more
05-23 20:16:40.989  3544  3873 E unknown:React: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.internal.zzbxn" on path: DexPathList[[zip file "/data/app/com.eventapp-2/base.apk"],nativeLibraryDirectories=[/data/app/com.eventapp-2/lib/arm, /system/fake-libs, /data/app/com.eventapp-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
05-23 20:16:40.989  3544  3873 E unknown:React:         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05-23 20:16:40.989  3544  3873 E unknown:React:         at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
05-23 20:16:40.989  3544  3873 E unknown:React:         at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
05-23 20:16:40.989  3544  3873 E unknown:React:         ... 14 more
05-23 20:16:41.071  1183  1208 I PlayCommon: [2527] PlayEventLogger.uploadEventsImpl: Preparing logs for uploading
05-23 20:16:41.072  1183  1208 I PlayCommon: [2527] PlayEventLogger.uploadEventsImpl: No file ready to send
05-23 20:16:41.078  3544  3544 W unknown:React: Calling JS function after bridge has been destroyed.
...
```

There's plenty of output above this part, which also mentions `RNGooglePlaces` in it, but I will omit it for now for the sake of brevity. If you need more output or more details, let me know.

Thanks for your continued assistance. Cheers!

**Comment by tolu360** [comment]
Hey @rasmniel, so this issue has been a very tricky one to debug remotely even with the stack trace, I have had to set up a sample app to reproduce your issues - and, yes I was able to reproduce it. And yes, it was just a case of Google API versions clashing all over the place.

My fix should work as long as you keep watching the libraries you are using in your project for updates and changes and acting accordingly.

`TL:DR` - Every Google API you use must pull in the same version of `Google Play Services`. 

To fix things now, simply update your `./android/app/build.gradle` to match mine as shown below:

```groovy
android {
    ------
    buildToolsVersion "25.0.1"
    -----
    -----
}

dependencies {
    compile project(':react-native-google-places')
    compile project(':react-native-fcm')
    compile ('com.google.firebase:firebase-messaging:10.2.0') {
        force = true;
    }
    compile ('com.google.firebase:firebase-core:10.2.0') {
        force = true;
    }
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:25.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
}
```
Don't forget to slot in other  `dependencies` unique to your project!

Do a `cd android && ./gradlew clean`, rebuild your project and profit!

Cheers!

**Comment by heckchuckman** [comment]
Hi @tolu360 

Fantastic work! I can confirm that going through all of the dependencies that reference `com.google.android.gms:play-services-base` need to me the same version. After that all methods seem to be working!

Thanks!

**Comment by tolu360** [comment]
@rasmniel - Feel free to re-open this if you still can't make it work. Cheers!

**Comment by rasmniel** [comment]
Hello @tolu360 
Thanks for the effort and apologies for the lack of response.
Your solution has indeed fixed the problem by forcing the dependencies to the appropriate version.

Thanks again for solving our problem and keep up the good work - Cheers!
