### ISSUE TITLE
IOS: undefined is not an object (evaluating 'RNGooglePlacesNative.openAutocompleteModal')

### ISSUE THREAD

**Issue by jdwillemse** [tolu360/react-native-google-places#46]
I created an app using `react-native init AwesomeProject`. I installed react-native-google-places as per the readme and google dev instructions. Upon running the app I get this error when I hit the modal trigger:

<img width="373" alt="screen shot 2017-06-01 at 11 27 38" src="https://cloud.githubusercontent.com/assets/1798297/26673737/3be74d38-46be-11e7-802e-379514982006.png">

Any idea what could be going wrong?

**Comment by jdwillemse** [comment]
I've written a step-by-step to reproduce this issue: https://stackoverflow.com/questions/44329264/react-native-package-return-undefined

**Comment by tolu360** [comment]
Hey @jdwillemse, those steps would have been better stated here or, in the least, copied here for easy access. Did you link the package with your project [manually](https://github.com/tolu360/react-native-google-places#manual-linking-with-your-project-ios) or [automatically](https://github.com/tolu360/react-native-google-places#auto-linking-with-your-project-ios--android)? I didn't see that anywhere? Please do that if you haven't.

Cheers!

**Comment by jdwillemse** [comment]
I didn't know if I was going to get a reaction here which is why I went to Stackoverflow. Soz for being impatient.

step 3 was linking `react-native link react-native-google-places`

When this didn't work I also tried doing this manually with no better results

**Comment by tolu360** [comment]
Move it out of your main render method, there's a very high chance your native modules may be `undefined` when your component first renders.

Call `RNGooglePlaces.openAutocompleteModal();` from a class method.

**Comment by tolu360** [comment]
Any luck?

**Comment by jdwillemse** [comment]
No I couldn't solve the problem so I rolled my own using JS only
