### ISSUE TITLE
GooglePlacePicker.h file not found when not using GooglePlacePicker

### ISSUE THREAD

**Issue by SuhairZain** [tolu360/react-native-google-places#49]
Hi, I was trying to install this library and I plan on using only the API, not the picker. So as per the docs, I didn't include the GooglePlacePicker pod in my podfile. But when I build the project, I get a not found error. When I list GooglePlacePicker in my pods, the issue goes away. Is there a way to use this library without the picker?

P.S: I do not mind having GooglePlacePicker among my pods. It's just that the README states that it's optional. That's all. 😄 

```
/Volumes/Data/QPlay/PharmaTruck/app/node_modules/react-native-google-places/ios/RNGooglePlacesViewController.m:4:9: 'GooglePlacePicker/GooglePlacePicker.h' file not found
```

**Comment by tolu360** [comment]
Hey @SuhairZain, I see your point, the README is older than some of the features offered by the package - please keep the `GooglePlacePicker` in your list of `pods`. I would update the README.
