### ISSUE TITLE
when running RNGooglePlaces.openPlacePickerModal() or RNGooglePlaces.openAutocompleteModal() app crashes

### ISSUE THREAD

**Issue by KamWis** [tolu360/react-native-google-places#5]
Hello!

First of all: thank you for awesome module! Gr8 job!
To the topic: I've implemented your's module but faced fallowing problem when invoked onPress `openSearchModal()` function (from example) - app crashes but google places is running:

![image](https://cloud.githubusercontent.com/assets/19514441/20859094/054373f2-b955-11e6-8e17-a02ed03cc15b.png)

got no errors in launchPacker.command:

![image](https://cloud.githubusercontent.com/assets/19514441/20859100/31114626-b955-11e6-8e60-5a0534d0dd3c.png)

neither in console.log.  This happens with or without debugger on.

Any Ideas? :)

**Comment by KamWis** [comment]
Adding logs from Android Monitor - sry for not including this ealier:

![image](https://cloud.githubusercontent.com/assets/19514441/21022823/44cbfd46-bd7e-11e6-9151-06a433b68e17.png)

**Comment by tolu360** [comment]
Hello @KamWis, please what version of `RN` are you running on? This error may have nothing to do with this package, it looks like a `RN` error that was fixed after version `0.35.0` as contained [here](https://github.com/facebook/react-native/issues/10080). Make sure you are not running `RN` below version `0.36.0` or upgrade your version of `RN` if necessary.

**Comment by KamWis** [comment]
Hi!

Thanks for your answer @tolu360. 

Yes, yesterday i've found that `RN 0.36.0` fixed the issue - forgot to mention it (night time work - sry).
