### ISSUE TITLE
GooglePlaces.h file not found

### ISSUE THREAD

**Issue by YY030913** [tolu360/react-native-google-places#51]
#import <GooglePlaces/GooglePlaces.h>

i follow this https://developers.google.com/places/ios-api/start#-2--api but get error, when import

**Comment by Deevent** [comment]
+1 Same issue. Did you find a solution ?

**Comment by brh55** [comment]
I had to go with the CocoaPods route.

**Comment by gomitaana** [comment]
I have the same problem, it isnt working with #import or cocoa route.
Any solution?

**Comment by tolu360** [comment]
Guys, try this number right [here](https://github.com/tolu360/react-native-google-places/issues/53#issuecomment-311424840) - would look at the changes in the Header Search Paths much later. And only `CocoaPods` route is supported.

Let me know if stuff works

**Comment by gomitaana** [comment]
I already get a solution, I download all the framework of Google and install it manually, then I link manually the react component as tolu said in README document. Thanks! 
If I can help anyone let me now.

**Comment by NorbertCU** [comment]
@gomitaana I'm trying to do the same you did, but I haven't succeeded. I'm still having "GooglePlaces.h file not found" issue. Did you change any Header Search Path or something else?

**Comment by brickolicious** [comment]
Try 
cd ios
pod install

**Comment by NorbertCU** [comment]
@brickolicious Thank you! I had issues with pods because it had conflicts with another library I was using. I finally made it downloading and installing the framework from Google. It works great now.

**Comment by abansal77** [comment]
Same issue. I do not want to use cocoapods. Any other way this can work. I changed .h file names to RNxxx. Now I am getting following errors

/Users/user/code/app/user-app/node_modules/react-native-google-places/ios/RNGooglePlaces.h:11:4: Expected a type
/Users/user/code/app/user-app/node_modules/react-native-google-places/ios/NSMutableDictionary+GMSPlace.m:1:9: In file included from /Users/user/code/app/user-app/node_modules/react-native-google-places/ios/NSMutableDictionary+GMSPlace.m:1:
/Users/user/code/app/user-app/node_modules/react-native-google-places/ios/NSMutableDictionary+GMSPlace.h:2:9: In file included from /Users/user/code/app/user-app/node_modules/react-native-google-places/ios/NSMutableDictionary+GMSPlace.h:2:
/Users/user/code/app/user-app/node_modules/react-native-google-places/ios/NSMutableDictionary+GMSPlace.h:6:41: Expected a type
/Users/user/code/app/user-app/node_modules/react-native-google-places/ios/NSMutableDictionary+GMSPlace.m:1:9: In file included from /Users/user/code/app/user-app/node_modules/react-native-google-places/ios/NSMutableDictionary+GMSPlace.m:1:
/Users/user/code/app/user-app/node_modules/react-native-google-places/ios/NSMutableDictionary+GMSPlace.m:5:41: Expected a type

**Comment by alpamys-qanybet** [comment]
@abansal77 , what are your search paths, I added manually frameworks to Libraries directory but could not set search path.

**Comment by abdulateeq9** [comment]
> I had to go with the CocoaPods route.
Hi, can you tell me the procedure Cocoapods

**Comment by liuqiiiiiii** [comment]
I‘m getting confuse.
error: 'GooglePlaces/GooglePlaces.h' file not found
#import <GooglePlaces/GooglePlaces.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
** BUILD FAILED **



The following build commands failed:

	CompileC /Users/a11/Componey/javashop-react_native/ios/build/Build/Intermediates.noindex/RNGooglePlaces.build/Debug-iphonesimulator/RNGooglePlaces.build/Objects-normal/x86_64/NSMutableDictionary+GMSPlace.o /Users/a11/Componey/javashop-react_native/node_modules/react-native-google-places/ios/NSMutableDictionary+GMSPlace.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/NeeHow.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/NeeHow.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by liuqiiiiiii** [comment]
fatal error: 'GooglePlaces/GooglePlaces.h' file not found
#import <GooglePlaces/GooglePlaces.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.


** BUILD FAILED **



The following build commands failed:
	CompileC /Users/a11/Componey/javashop-react_native/ios/build/Build/Intermediates.noindex/RNGooglePlaces.build/Debug-iphonesimulator/RNGooglePlaces.build/Objects-normal/x86_64/NSMutableDictionary+GMSPlace.o /Users/a11/Componey/javashop-react_native/node_modules/react-native-google-places/ios/NSMutableDictionary+GMSPlace.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/NeeHow.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/NeeHow.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

now i really can't solve it.

**Comment by SilajitBukaiSil** [comment]
I also face the same issue .How to solve the above issue?

**Comment by VitorBrangioni** [comment]
Same probleam, any solution?

**Comment by VitorBrangioni** [comment]
Same issue, any solution?
