### ISSUE TITLE
Module 'GoogleMaps' not found

### ISSUE THREAD

**Issue by bidfor** [tolu360/react-native-google-places#53]
Fresh install
I get this error. 

`While building module 'GooglePlacePicker' imported from /Users/coding/Documents/react/test/node_modules/react-native-google-places/ios/RNGooglePlacesViewController.m:4:
In file included from <module-includes>:1:
In file included from /Users/coding/Documents/react/test/node_modules/react-native-google-places/ios/../../../ios/Pods/GooglePlacePicker/Frameworks/GooglePlacePicker.framework/Headers/GooglePlacePicker.h:1:
/Users/coding/Documents/react/test/node_modules/react-native-google-places/ios/../../../ios/Pods/GooglePlacePicker/Frameworks/GooglePlacePicker.framework/Headers/GMSPlacePicker.h:12:9: fatal error: module 'GoogleMaps' not found
@import GoogleMaps;
 ~~~~~~~^~~~~~~~~~
1 error generated.`

**Comment by tigo0** [comment]
Any solutions to this?

**Comment by tolu360** [comment]
Hello @bidfor & @tigo0, I am on a short vacation at the moment - would check this asap. In the meantime, can you downgrade the dependencies in your `Podfile` if stuff had worked for you before, I'm guessing there may have been a breaking change in the dependencies. Try to do:

```ruby
  pod 'GooglePlaces', '2.2.0'
  pod 'GoogleMaps', '2.2.0'
  pod 'GooglePlacePicker', '2.2.0'
```

Run `cd ios && pod install` again, then build your project again. Let me know if doing this helps at all.

**Comment by bidfor** [comment]
@tolu360 Yes it works! Thank you !

**Comment by tolu360** [comment]
Just a temporary fix though, something has changed about the `Header Paths` in the newer versions of the `Google Libraries`, would sort things out as soon as my little vacation is over.

Cheers!

**Comment by brycepavey** [comment]
I had `module 'GooglePlaces' not found`, the issue for me was pod install was throwing warnings including
`[!] The `MyProject [Debug]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-MyProject/Pods-MyProject.debug.xcconfig'. This can lead to problems with the CocoaPods installation`
and was solved by adding `$(inherited)` to Project > Build Settings > Header Search Paths

**Comment by leoabacade** [comment]
adding $(inherited) to Project > Build Settings > Header Search Paths solved the issue for me

**Comment by alpamys-qanybet** [comment]
I have problems with cocoapods on archive in xCode. here is manual installation https://developers.google.com/places/ios-api/start if someone needs.
