### ISSUE TITLE
 UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by sandropoluan** [tolu360/react-native-google-places#54]
An error when run **_npm i react-native-google-places --save_**

> +-- UNMET PEER DEPENDENCY react@16.0.0-alpha.6
> `-- react-native-google-places@2.1.0
> 
> npm WARN react-native-google-places@2.1.0 requires a peer of react@>=15.4.0 but
> none was installed.

I use  react 16.0.0-alpha.6 on react-native 0.44.0

**Comment by tolu360** [comment]
This warning would go away when react v16 final build is released.
