### ISSUE TITLE
Could not invoke RNGooglePlaces.getAutocompletePredictions (Android)

### ISSUE THREAD

**Issue by sandropoluan** [tolu360/react-native-google-places#55]
![capture](https://user-images.githubusercontent.com/11922251/27766705-2a41906e-5f0c-11e7-91c6-5e75eb17ecc4.PNG)

React 16.0.0-alpha.6
RN 0.44.0
Same error on emulator and real device.

Maybe because #54 ?

**Comment by sandropoluan** [comment]
Just solved the problem..,

there is a conflict with com.google.android.gms:play-services-base from react-native-maps.
Force them to use same version solved the problem.

**Comment by tolu360** [comment]
You are right, this has been addressed in a couple of issues in the past, one of which can be found [here](https://github.com/tolu360/react-native-google-places/issues/48#issuecomment-307122694).

Cheers!
