### ISSUE TITLE
Change the results language

### ISSUE THREAD

**Issue by sandropoluan** [tolu360/react-native-google-places#56]
For now all results is in English, 
Is there any way to change it to specific language?
Already pass the 'country' option, but all result still in English.

Thank you in advance.

**Comment by chrusart** [comment]
@sandropoluan 'cauntry' option only sets a results filter to this country and It uses current device or application locale i guess. Does changing device or application locale works?

**Comment by tolu360** [comment]
@sandropoluan Google APIs usually default to the system language (device language in this case) - try what @chrusart suggested above.

**Comment by chrusart** [comment]
I found that REST requests can have language parameter, not sure what about Android API yet.
