### ISSUE TITLE
addressComponents in Android

### ISSUE THREAD

**Issue by renatomota** [tolu360/react-native-google-places#57]
Hello !
The addressComponents field is not returned in Android, how do I fix it?
![captura de tela 2017-07-06 as 19 20 16](https://user-images.githubusercontent.com/26210308/27935268-68e830ee-6280-11e7-9024-df61f1e6cbcb.png)

**Comment by tolu360** [comment]
This is not a bug. As far as I know, the addressComponents is not returned in the android implementation (SDK) - if that has changed, please send a PR.
