### ISSUE TITLE
How can i get photos for places?

### ISSUE THREAD

**Issue by TimurAsayonok** [tolu360/react-native-google-places#60]
@tolu360 Mb You know, How can i get photos for places using `RNGooglePlaces.getAutocompletePredictions` method?

And Mb You know, How can i get latitude and longitude in `RNGooglePlaces.getAutocompletePredictions` for places?

**Comment by tolu360** [comment]
@TimurAsayonok, the native SDKs don't return place photos - you can use the web service for that or just combine both.

To obtain place details using `RNGooglePlaces.getAutocompletePredictions()` is covered in the [readme](https://github.com/tolu360/react-native-google-places#look-up-a-place-by-id) - `RNGooglePlaces.getAutocompletePredictions()` returns `placeID` for each suggested place, pass the `placeID` value to `RNGooglePlaces.lookUpPlaceByID()` to get the place object for your selected place.

**Comment by ramneekhanda** [comment]
@tolu360 i dont think the lookupplacebyid returns more fields either after looking at the sources.

**Comment by TimurAsayonok** [comment]
@ramneekhanda yes, the lookUpPlaceById doesn't return more fields. So, i've solved this problem for my project. I've used Api for web, and used fetching methods for this. It's the best way for my task, i think.

**Comment by tolu360** [comment]
@ramneekhanda, I wrote the source so I know what each method/API returns but if by *more fields* you mean photos, no, this library does not return photos - try the web API like @TimurAsayonok did.

I have summaries of sample responses for each method detailed in the readme - you can look at [sample for RNGooglePlaces.getAutocompletePredictions(](https://github.com/tolu360/react-native-google-places#example-response-from-calling-getautocompletepredictions)) and [sample for RNGooglePlaces.lookUpPlaceByID()](https://github.com/tolu360/react-native-google-places#example-response-from-calling-lookupplacebyid) etc. OR just try each method out in your project and inspect responses.

Guys, I'd close this now, feel free to re-open if necessary. Cheers!
