### ISSUE TITLE
An error occurred while executing doInBackground

### ISSUE THREAD

**Issue by panhna** [tolu360/react-native-google-places#61]
hi i got error after install react-native-google-places. without react-native-google-places map is working fine. any idea? thx

"react": "16.0.0-alpha.6",
"react-native": "0.44.2",
"react-native-maps": "^0.15.0",
"react-native-google-places": "^2.1.0",

![screen shot 2017-07-17 at 4 49 01 pm](https://user-images.githubusercontent.com/5246440/28263155-fae838b2-6b0f-11e7-91c8-7f8c2c9c4fc3.png)

**Comment by tolu360** [comment]
Try what I did [here](https://github.com/tolu360/react-native-google-places/issues/48#issuecomment-307122694) first and lets see how that goes! You may also review other similar closed issues.

**Comment by panhna** [comment]
@tolu360 thx you so much. i already fixed. it's really similar the issues you tell me.

i change something like this:

    compile(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }

    compile(project(':react-native-google-places')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-places'
        exclude group: 'com.google.android.gms', module: 'play-services-location'
    }

    compile 'com.google.android.gms:play-services-base:+'
    compile 'com.google.android.gms:play-services-places:+'
    compile 'com.google.android.gms:play-services-maps:+'
    compile 'com.google.android.gms:play-services-location:+'

**Comment by tolu360** [comment]
@panhna - you have a similar approach here, the only difference is, with your changes you won't be able to tell the exact versions of these dependencies you are using in your project at any given instance. This may make it harder to trace and debug issues in the future.
