### ISSUE TITLE
Problem with NSDictionary+GMSPlace.m

### ISSUE THREAD

**Issue by gomitaana** [tolu360/react-native-google-places#64]
no such file or directory: '.../app/node_modules/react-native-google-places/ios/NSDictionary+GMSPlace.m

I install by CocoaPods and I present the problem above.

**Comment by arabscimitar** [comment]
+1

**Comment by arabscimitar** [comment]
I fixed this by removing NSDictionary+GMSPlace.m and NSDictionary+GMSPlace.h files from RNGooglePlaces.xcodeproj and added NSMutableDictionary+GMSPlace.h and NSMutableDictionary+GMSPlace.m to the linked RNGooglePlaces.xcodeproj

**Comment by tolu360** [comment]
Hi @gomitaana  and @arabscimitar - you are spot on with the changes you made. I just published `react-native-google-places@2.4.1` to correct the wrong import in `Compile Sources`. You can just pull in the latest version. Would close this now, feel free to reopen if you still have the issue with `2.4.1`

Cheers!

**Comment by gomitaana** [comment]
Hi @tolu360, i encountered a new error in this new version:
'@import GooglePlaces' module not found

already tried the RNlinking and manual linking but still gives the error

**Comment by temitope** [comment]
@gomitaana i ran into this same error. upgrading to `2.4.1` didnt help, but upgrading to`2.4.2` did
