### ISSUE TITLE
Crash soon as the app is launched.

### ISSUE THREAD

**Issue by ramneekhanda** [tolu360/react-native-google-places#66]
I get the error pasted below in logcat and my application stops immediately after the launch.

```
dependencies {
    compile(project(':react-native-google-places')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-places'
        exclude group: 'com.google.android.gms', module: 'play-services-location'
    }
    compile 'com.google.android.gms:play-services-base:10.2.0'
    compile 'com.google.android.gms:play-services-places:10.2.0'
    compile 'com.google.android.gms:play-services-location:10.2.0'  

    compile project(':react-native-device-info')
    compile project(':react-native-image-picker')
    compile project(':react-native-interactable')
    compile "com.google.android.gms:play-services-base:10.2.0"
    compile "com.google.android.gms:play-services-maps:10.2.0"
    
    compile project(':react-native-firebase-analytics')
    compile (project(':react-native-maps')) {
        exclude group: 'com.google.android.gms', module: 'play-services-base' 
        exclude group: 'com.google.android.gms', module: 'play-services-maps' 
    }
    compile project(':react-native-vector-icons')
    compile project(':react-native-navigation')
    compile fileTree(dir: "libs", include: ["*.jar"])
    
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile ('com.google.firebase:firebase-core:10.2.0') {
        force = true;
    }

}
```
```
07-21 15:01:08.853 31139 31172 E AndroidRuntime: java.lang.AbstractMethodError: abstract method "com.google.android.gms.common.api.Api$zze com.google.android.gms.common.api.Api$zza.zza(android.content.Context, android.os.Looper, com.google.android.gms.common.internal.zzq, java.lang.Object, com.google.android.gms.common.api.GoogleApiClient$ConnectionCallbacks, com.google.android.gms.common.api.GoogleApiClient$OnConnectionFailedListener)"
07-21 15:01:08.853 31139 31172 E AndroidRuntime: 	at com.google.android.gms.common.api.GoogleApiClient$Builder.build(Unknown Source)
07-21 15:01:08.853 31139 31172 E AndroidRuntime: 	at com.arttitude360.reactnative.rngoogleplaces.RNGooglePlacesModule.buildGoogleApiClient(RNGooglePlacesModule.java:76)
07-21 15:01:08.853 31139 31172 E AndroidRuntime: 	at com.arttitude360.reactnative.rngoogleplaces.RNGooglePlacesModule.<init>(RNGooglePlacesModule.java:59)
07-21 15:01:08.853 31139 31172 E AndroidRuntime: 	at com.arttitude360.reactnative.rngoogleplaces.RNGooglePlacesPackage.createNativeModules(RNGooglePlacesPackage.java:29)
07-21 15:01:08.853 31139 31172 E AndroidRuntime: 	at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
07-21 15:01:08.853 31139 31172 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1009)
07-21 15:01:08.853 31139 31172 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:944)
07-21 15:01:08.853 31139 31172 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:109)
07-21 15:01:08.853 31139 31172 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:746)
07-21 15:01:08.853 31139 31172 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by ramneekhanda** [comment]
Resolved using 
`compile(project(':react-native-google-places')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-places'
        exclude group: 'com.google.android.gms', module: 'play-services-location'
    }
    compile 'com.google.android.gms:play-services-base:11.+'
    compile 'com.google.android.gms:play-services-places:11.+'
    compile 'com.google.android.gms:play-services-location:11.+'   
    compile project(':react-native-device-info')
    compile project(':react-native-maps')
    compile project(':react-native-image-picker')
    compile project(':react-native-interactable')
    compile "com.google.android.gms:play-services-base:11.+"
    compile "com.google.android.gms:play-services-maps:11.+"
    
    compile project(':react-native-firebase-analytics')
    compile (project(':react-native-maps')) {
        exclude group: 'com.google.android.gms', module: 'play-services-base' 
        exclude group: 'com.google.android.gms', module: 'play-services-maps' 
    }
    compile project(':react-native-vector-icons')
    compile project(':react-native-navigation')
    compile fileTree(dir: "libs", include: ["*.jar"])
    
    compile "com.android.support:appcompat-v7:25.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile 'com.google.firebase:firebase-core:10.2.6'`

**Comment by mtx62** [comment]
to be more specific, Adding 
` compile 'com.google.android.gms:play-services-places:11.8.0'
 compile 'com.google.android.gms:play-services-location:11.8.0' 
`

And
`
compile(project(':react-native-google-places')){
exclude group: 'com.google.android.gms', module: 'play-services-base'
exclude group: 'com.google.android.gms', module: 'play-services-places'
exclude group: 'com.google.android.gms', module: 'play-services-location'
}
`

Solve my issue too,
Thank you @ramneekhanda
