### ISSUE TITLE
RCTConvert+MapKit.h not found

### ISSUE THREAD

**Issue by nloui** [tolu360/react-native-google-places#67]
Hi there,

I'm getting this error when running the project.  Anyone else get something similar?  

Thanks for the great repo!

.../node_modules/react-native-maps/ios/AirMaps/AIRMapUrlTile.h:13:9: 'React/RCTConvert+MapKit.h' file not found
.../node_modules/react-native-maps/ios/AirMaps/AIRMapUrlTile.m:9:9: In file included from .../node_modules/react-native-maps/ios/AirMaps/AIRMapUrlTile.m:9:

**Comment by tolu360** [comment]
Hi, please raise this issue on the `react-native-maps` repo, looks totally unrelated to this package.
