### ISSUE TITLE
Getting undefined on RNGooglePlaces (Android)

### ISSUE THREAD

**Issue by heliojuniorkroger** [tolu360/react-native-google-places#69]
Import as:
import RNGooglePlaces from 'react-native-google-places'
got undefined. Already configured AndroidManifest.xml...
Help please :(

**Comment by tolu360** [comment]
Hey, try to clone and run [this sample](https://github.com/tolu360/trial) on your emulator and see if you can reproduce your issues or spot what your own setup is lacking. Don't forget to replace the Google API key with your own in `AndroidManifest`.
