### ISSUE TITLE
Android simulator error: undefined is not an object (evaluating '_reactNativeGooglePlaces.RNGooglePlaces.openPlacePickerModal')

### ISSUE THREAD

**Issue by she-dev** [tolu360/react-native-google-places#7]
Hello! I've done the setup and I'm getting this error:
```
undefined is not an object (evaluating '_reactNativeGooglePlaces.RNGooglePlaces.openPlacePickerModal')
openSearchModal
    PlacePicker.js:7
onPress
    PlacePicker.js:20
```

I created a component based on the example code:

PlacePicker.js
```js
import React, { Component } from 'react';
import { Text, TouchableOpacity, View } from 'react-native';
import { RNGooglePlaces } from 'react-native-google-places';

class PlacePicker extends Component {
  openSearchModal() {
    RNGooglePlaces.openPlacePickerModal()
    .then((place) => { 
        console.log(place);         
    })
    .catch(error => console.log(error.message));
  }

  render() {
    return (
      <View style={{ width: 100, height: 20 }}>
        <TouchableOpacity
          onPress={() => this.openSearchModal()}
        >
          <Text>Open Place Picker</Text>
        </TouchableOpacity>
      </View>
    );
  }
}

export default PlacePicker;
```

Then I'm using it wrapped in a View-like component
```js
        <CardSection>
          <PlacePicker />
        </CardSection>
```

Any ideas on how to solve this?
Thanks in advance, I really like this project.

**Comment by tolu360** [comment]
Hi @she-dev, just change the line `import { RNGooglePlaces } from 'react-native-google-places'` to `import RNGooglePlaces from 'react-native-google-places'` and it should work just fine.

**Comment by she-dev** [comment]
@tolu360 Thanks, that stopped the error 👍 
The thing now is that nothing happens when I click it.
I'll unlink it and reinstall everything.

**Comment by she-dev** [comment]
It works perfectly on iOS simulator now but on Android I get this message:

**Comment by tolu360** [comment]
Do you have your API key set up in `AndroidManifest.xml` ?

```xml
<application
      android:name=".MainApplication"
      ...>
    <meta-data
        android:name="com.google.android.geo.API_KEY"
        android:value="YOUR_ANDROID_API_KEY_HERE"/>
    ...
</application>
```

And are you running in an Android emulator with `Google APIs`? See below:

<img width="1198" alt="screen shot 2016-12-14 at 8 13 34 pm" src="https://cloud.githubusercontent.com/assets/3914854/21196948/eea1b54e-c239-11e6-99d0-14fb7dd3d845.png">

**Comment by she-dev** [comment]
API key shortened for the screenshot
![](http://i.imgur.com/UI6SUbd.png)

I was using the one without Google API, then created a new device and ran on it.
![](http://i.imgur.com/etJuCdW.png)

Packages on Android SDK Manager are installed and updated.

**Comment by tolu360** [comment]
Hi @she-dev, are you still getting the error after taking those steps?

**Comment by she-dev** [comment]
Now it opens but when I start typing it closes the search and returns to the map.
And as you can see, it doesn't suggest nearby places.
![Imgur](http://i.imgur.com/DtQgCvxl.png)

Then if I just leave the marker where it is, as there are no suggestions, I didn't select a place but _SELECT_ this location is grayed out.
![Imgur](http://i.imgur.com/Uvib9WSl.png)

**Comment by tolu360** [comment]
You may need to look in the android monitor for the stack-trace when that happens - an error may be getting logged. You may also just input a custom `lat` and `lng` coordinates into the emulator so the picker can instantiate at your custom position On a physical device, the picker would always launch at your current coordinates.

**Comment by she-dev** [comment]
The weird thing is that I don't see any errors on the browser remote debugger.
I'll try to run it on Android 7.1 like you did and double-check the setup to see if I missed something.
Thanks for your help!

Current state:
![](http://i.imgur.com/riNN9Fi.gif)

**Comment by tolu360** [comment]
You are welcome. Another debugging you can employ is run `adb logcat` to log the stack-trace to your terminal while the app is running and try to filter to entries containing 'RNGooglePlaces` - see if anything shows up. From your screencast, it's not acting as expected yet.

**Comment by she-dev** [comment]
Apparently it started to work correctly. Now I can type and the search suggests places.
What I did:

- Put `<meta-data>` tag with API key right after opening `<application>` tag on AndroidManifest.xml, before `<activity>` tags.
- Used the key named as **Server key (auto created by Google Service)**. Restricted it to Android Apps and added configuration for my app and used it. I had created many keys and none appeared to work, so I decided to use that one. Not sure if I should reserve this "server key". It was suggested to me after clicking Create credentials -> Help me choose -> Google Places API for Android -> Which credentials do I need?
- Made sure to go through the same step above (Create credentials -> ...) for the Google Maps Android API. It asked me if I wanted to enable it. The first time I clicked nothing changed. Then when I used the server key I saw it working.

Do you think it's bad to use the server key in this way?
Thanks for joining me in this saga :)

**Comment by tolu360** [comment]
Hi @she-dev, glad you finally got it to work perfectly! Using the `Help me choose` option under `Create credentials` look totally fine to me, once the key has been created, you can stack on other permissions you may want the key to have. I have 2 keys, one restricted to `Android` apps and the other to `iOS` apps. I just add bundle identifiers and app IDs to these keys as needed, to support new apps I create.

Cheers!

**Comment by she-dev** [comment]
Yesterday I had trouble selecting places again and then I remembered I had used the release certificate fingerprint to generate the SHA-1 fingerprint... and I'm not sure if I had previously done a release build, ha!
So I went back to the [docs](https://developers.google.com/places/android-api/signup) and repeated the process using the debug certificate and then restricted the API key using the new SHA-1 fingerprint.

> Only use this certificate with apps that you're testing. Do not attempt to publish an app that's signed with a debug certificate. 

As noted you may need to do this again with the release certificate when publishing the app.

Just a tip in case anyone has problems with this.

**Comment by tolu360** [comment]
Thank you for the insights @she-dev, I should probably find somewhere to include this in the README rather than assume it is somewhat implied.

**Comment by she-dev** [comment]
Thank **you** for developing this :)
It's complicated because it really is implied as it's just indirectly related to your project.
But the problem is that the steps are not as clear as they should be and there are little details that can lead to problems.
I went through the default Android setup and never saw most of the stuff you helped me with.
