### ISSUE TITLE
Android crashes on launch with v2.4.1 + react-native-44. 

### ISSUE THREAD

**Issue by tastycode** [tolu360/react-native-google-places#70]
Followed the instructions in README.md for

1. Obtaining an API key with android certificate fingerprint matching
2. Automatically then manually linking android
3. Verified all bullet points in https://github.com/tolu360/react-native-google-places#on-android

```
07-31 17:18:52.180  4960  4973 E AndroidRuntime: Caused by: java.lang.AbstractMethodError: abstract method "com.google.android.gms.common.api.Api$zze com.google.android.gms.common.api.Api$zza.zza(android.content.Context, android.os.Looper, com.google.android.gms.common.internal.zzq, java.lang.Object, com.google.android.gms.common.api.GoogleApiClient$ConnectionCallbacks, com.google.android.gms.common.api.GoogleApiClient$OnConnectionFailedListener)"
```

It turns out that if you install the newest version of google play services (54 right now), then you'll have to update `build.gradle` inside `react-native-google-maps` 

```
    compile 'com.google.android.gms:play-services-base:11.0.4'
    compile 'com.google.android.gms:play-services-places:11.0.4'
    compile 'com.google.android.gms:play-services-location:11.0.4'
```

Previously these were all listed as `10.2.4`

**Comment by tolu360** [comment]
Hi @tastycode,

I am not familiar with the library - `react-native-google-maps` to start with (that's not `react-native-maps`, is it?), but do something like this in your ./android/app/build.gradle: (or replace 11.0.4 with any other version you want to use)

dependencies {
    compile project(':react-native-google-places')
    compile project(':react-native-google-maps')
    compile ('com.google.android.gms:play-services-base:11.0.4') {
         force = true;
    }
    compile ('com.google.android.gms:play-services-maps:11.0.4') {
         force = true;
    }
    compile ('com.google.android.gms:play-services-places:11.0.4') {
         force = true;
    }
    compile ('com.google.android.gms:play-services-location:11.0.4') {
        force = true;
    }
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:25.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
}
Don't forget to slot in other dependencies unique to your project!

Do a cd android && ./gradlew clean, rebuild your project and let me know if that works for you!

**Comment by tastycode** [comment]
> I am not familiar with the library - react-native-google-maps

Sorry about that, i meant `react-native-google-places` 

Thanks for offering a solution, my solution worked for me, I was just documenting it for others running into crashes when integrating react-native-google-places in android upon launch showing a stacktrace indicating a failed API handshake with google services.

**Comment by chrusart** [comment]
I use such code in gradle for all libraries and sub-modules (dependencies) to use the same version of google services:
```
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def group = details.getRequested().getGroup()

        if (group == 'com.google.android.gms') {
            // If different projects require different versions of
            // Google Play Services it causes a crash on run.
            // Fix by overriding version for all projects.
            details.useVersion(GOOGLE_SERVICES_VER)
        }
        if (group == 'com.google.firebase') {
            // similar issue with firebase
            details.useVersion(GOOGLE_SERVICES_VER)
        }
        if (group == 'com.android.support') {
            if (!details.getRequested().getName().startsWith("multidex")) {
                details.useVersion(ANDROID_SUPPORT_VER)
            }
        }
    }
}
```
