### ISSUE TITLE
NSDictionary+GMSPlace.m missing

### ISSUE THREAD

**Issue by geeknam** [tolu360/react-native-google-places#71]
XCode complains about not being able to find `NSDictionary+GMSPlace.m`.

I had to:
- `cd node_modules/react-native-google-places/ios`
- `cp NSMutableDictionary+GMSPlace.m NSDictionary+GMSPlace.m`
- `cp NSMutableDictionary+GMSPlace.h NSDictionary+GMSPlace.h`

That sorted the problem.

More info about the environment setup:
- Version 8.2.1 (8C1002)
- React Native v0.46 (stable)
- react-native-google-places v2.4.0

**Comment by tolu360** [comment]
Hi @geeknam, that had already been fixed in `v2.4.1` - your quick fix is fine but just update to the latest version.

Cheers!
