### ISSUE TITLE
Map background not showing

### ISSUE THREAD

**Issue by NhatMai** [tolu360/react-native-google-places#72]
Pls help me fix this issue
![img_2242](https://user-images.githubusercontent.com/30771211/29002658-f12d9ab8-7ad9-11e7-9011-b388b3455a34.PNG)

**Comment by masoapps** [comment]
You need to add the Google Maps SDK permission from the google developer console:

![screen shot 2017-08-06 at 14 26 18](https://user-images.githubusercontent.com/12562266/29003719-b684c0ce-7ab3-11e7-8aae-5e4caed72ec0.png)

**Comment by NhatMai** [comment]
Thanks masapp

**Comment by kdela** [comment]
I think it should be somewhere in README (at least simple annotation)
