### ISSUE TITLE
undefined is not an object inside of RNGooglePlacesNative.openPlacePickerModal

### ISSUE THREAD

**Issue by rivertam** [tolu360/react-native-google-places#76]
Hi there,

I just started a new app by ejecting create-react-native-app to an expo project and followed the instructions in this project's README (I believe).

My react-native package is specified in my package.json as `https://github.com/expo/react-native/archive/sdk-20.0.0.tar.gz`. My react-native-google-places version is 2.4.2.

I'm trying to use the library as such:

```javascript
import React from 'react';
import {
  StyleSheet,
  Text,
  View,
  ListView,
  Button,
  Platform,
  ToastAndroid,
} from 'react-native';
import Places from 'react-native-google-places';

export default class LocationFormScreen extends React.Component {
  state = {
    location: null,
  };

  setLocation = async () => {
    try {
      const location = await Places.openPlacePickerModal();
      this.setState(() => ({ location }));
    } catch (e) {
      console.error(e.stack);
    }
  };

  render() {
    console.log(this.state.location)
    return (
      <View>
        <Button
          onPress={this.setLocation}
          title="Pick location"
        />
      </View>
    );
  }
}
```

Nothing too unreasonable, I don't think. I'm pretty sure this is how you're supposed to do it.

I'm getting an error whenever I click that button. It's just "undefined is not an object" coming from inside the `RNGooglePlacesNative.openPlacePickerModal` method. At first I thought it was the object spread operator being used on an undefined value, but it's actually coming from within that native method. I don't even know how "undefined is not an object" could occur inside a native module? But I'm very new to RN.

Any advice would be very welcome.

Thank you!

**Comment by jurStv** [comment]
Same error for me.
Any updates on this one?

**Comment by wmonecke** [comment]
I got the same but for `Cannot read property 'openAutocompleteModal' of undefined` from `RNGooglePlacesNative.openAutocompleteModal`

**Comment by rivertam** [comment]
I'm not still working on this (I abandoned the project), but I was working in Android, so I don't think the pod tip is relevant.

**Comment by tolu360** [comment]
Hello Guys! Please note that only projects started with the react-native cli (via `react-native init Project`) are supported at the moment. Expo and the other variants aren't supported yet and stuff may not always work as expected.

PRs are always welcome!

**Comment by mubashiralisiddiqui** [comment]
@tolu360  i am using this by ract native init but i have the same issue as above  cannot read property 'opentAutocompleteModal of udefine'

**Comment by pilot4u** [comment]
Hello, I I'm facing the same issue.
did you found solution for this?

**Comment by RameshkrishnanV** [comment]
i created the app with react native init only, but i'm also facing the same issue. please help us with this issue

**Comment by tolu360** [comment]
If anyone still has this issue, try to build and run the [sample app](https://github.com/tolu360/TestRNGP) on your machine, see if you can reproduce the issue on it.

**Comment by amit2908** [comment]
After a lot of mess up, I finally able to solve the issue, removed node_modules, removed pod, updated pod file by following:

```
    pod 'react-native-maps', path: '../node_modules/react-native-maps/'
    pod 'react-native-google-maps', path: '../node_modules/react-native-maps/'
    pod 'GooglePlacePicker'
    pod 'GooglePlaces'
```
and package.js by following:

```
"dependencies": {
    "react": "16.6.1",
    "react-geocode": "^0.1.2",
    "react-native": "0.57.7",
    "react-native-google-places": "^2.5.2",
    "react-native-maps": "^0.22.1"
  }

```
npm i
pod install
react-native link react-native-google-places

make sure in Xcode Project Navigator -> Libraries -> RNGooglePlaces.xcodeproj -> Products ->
libRNGooglePlaces.a  file does not show red. It was the main issue which was solved by following above steps.

Hope it helps someone :)
