### ISSUE TITLE
Get images when select location by function lookUpPlaceByID()

### ISSUE THREAD

**Issue by hoainamcr** [tolu360/react-native-google-places#77]
Hi guys,

I i'm a newbie reactNative. a need get images when pick a location, i don't know how to get it when call funtion lookUpPlaceByID()

please help me how to get images. 

Thanks all

**Comment by chrusart** [comment]
This is not supported yet, look into documentation or source code, but u can create a PR, getting place photos will be the same as ```lookPlaceByID``` method but u invoke:
```Places.GeoDataApi.getPlacePhotos(place ID)``` instead.

**Comment by hoainamcr** [comment]
Hi @chrusart  :(
react-native-google-places-autocomplete do it console to see detail : http://prntscr.com/gba3bu , but i'm not flexible for customize list layout or control in this PR. Hope you are supportive in your PR and very thankful :+1: :+1:

**Comment by chrusart** [comment]
react-native-google-places-autocomplete is a different package, please ask there for it then. Everybody can create a code and make a pull request with new functionality.
If u ask me to do this feature, then sorry but it's not how it works, i just wanna be helpful in your problem but ppl can't make work for somebody else. U wanna this feature, be supportive in community and implement it.

**Comment by hoainamcr** [comment]
yes, thank you so much :+1:
