### ISSUE TITLE
IOS build error: cannot build module 'GooglePlaces' , module 'GoogleMapsBase' not found

### ISSUE THREAD

**Issue by ymekuria** [tolu360/react-native-google-places#8]
Hi @tolu360. Thanks for building this module. After following the setup on the readme, and running react-native run-ios, I got the build errors copied below.

/node_modules/react-native-google-places/ios/../../../ios/Pods/GooglePlaces/Frameworks/GooglePlaces.framework/Headers/GMSAddressComponent.h:12:9: fatal error: 
      module 'GoogleMapsBase' not found
@import GoogleMapsBase;

node_modules/react-native-google-places/ios/RNGooglePlacesViewController.h:2:9: fatal error: 
      could not build module 'GooglePlaces'
#import <GooglePlaces/GooglePlaces.h>

/node_modules/react-native-google-places/ios/../../../ios/Pods/GooglePlacePicker/Frameworks/GooglePlacePicker.framework/Headers/GMSPlacePickerConfig.h:12:9: fatal error: 
      module 'GoogleMapsBase' not found
@import GoogleMapsBase;

Below is the Podfile.lock file.

PODS:
  - GoogleMaps (2.1.1):
    - GoogleMaps/Maps (= 2.1.1)
  - GoogleMaps/Base (2.1.1)
  - GoogleMaps/Maps (2.1.1):
    - GoogleMaps/Base
  - GooglePlacePicker (2.1.1):
    - GoogleMaps (= 2.1.1)
    - GooglePlaces (= 2.1.1)
  - GooglePlaces (2.1.1):
    - GoogleMaps/Base (= 2.1.1)

DEPENDENCIES:
  - GoogleMaps
  - GooglePlacePicker
  - GooglePlaces

SPEC CHECKSUMS:
  GoogleMaps: a5b5bbe47734e2443bde781a6aa64e69fdb6d785
  GooglePlacePicker: 665f39f931f2df32f9dd3fcc45f7e8abf71e535c
  GooglePlaces: 35636d86e5020cba3856eb988c09a5491de0a65a

PODFILE CHECKSUM: 9e1e9b87ca813feb8ea6f289cc25daf3e325cac6

COCOAPODS: 1.1.1

The pods appeared to be installed successfully, and I double checked the AppleDelegate.m file. I have v 0.35.0 of react-native installed. I copied my AppDelegate.m file below as well. Any ideas on how to fix this?

@import GooglePlaces;
@import GoogleMaps;

#import "AppDelegate.h"

#import "RCTBundleURLProvider.h"
#import "RCTRootView.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;

  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];

  [GMSPlacesClient provideAPIKey:@"AIzaSyxxxxxxxx"];
  [GMSServices provideAPIKey:@"AIzaSyxxxxxxxxxx"];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"thriftRide"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

@end

**Comment by tolu360** [comment]
Hello @ymekuria, downgrade your dependencies and see if that fixes stuff for you - replace your `Podfile` content with:

```
target 'YourApp' do

  pod 'GooglePlaces', '2.1'
  pod 'GoogleMaps', '2.1'
  pod 'GooglePlacePicker', '2.1'

end
```

Exit `XCode` if you have it running, also exit any running instance of the node packager. Run `pod install` again. This time, open your app with the `YourApp.xcworkspace` file and use the play button in `XCode` to build and run your app.

**Comment by ymekuria** [comment]
Thanks for the reply @tolu360. This helped, but I still had some build errors. I also tried to build via the terminal using react-native run-ios, and was able to get the module working on the iPhone simulator despite the build errors. I received the following errors:

Apple Mach-O Linker error

symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

The screenshot of the errors on xcode is below.

![screen shot 2016-12-14 at 5 27 38 pm](https://cloud.githubusercontent.com/assets/2808242/21208422/be93b67a-c222-11e6-9d21-3bd7adaa45a2.png)

Any idea whats going on? 

What I tried:
unlinked and linked the module
I cleaned the build using cmd + shift + k and cmd + shift + option + k
I deleted the contents of the DerivedData Folder

**Comment by tolu360** [comment]
Hello @ymekuria, the build errors may have nothing to do with this package - looks to me like you've altered some default build settings for `react-native`.

Try the following: select your '`App` under `Targets`, go to `Build Settings` and set these values or ensure they are correct:

1. Architectures > Valid Architectures: `arm64 armv7 armv7s`.
2. Linking > Other Linker Flags: Ensure you have entries for `$(inherited)`, `ObjC`, and `-lc++`, each on separate lines.

Build and run again.

**Comment by ymekuria** [comment]
Hi @tolu360. I tried your suggestions and many other things to try resolve this issue. I was finally able to successfully build the app after deleting the following lines from the podfile.

  target 'myApp' do
    inherit! :search_paths
    # Pods for testing
  end

Thanks for all your help.

**Comment by brascene** [comment]
Hi, I have similar issue today: as soon I start typing, modal closes down, no errors no nothing, build succeeded correctly. What can cause this?
