### ISSUE TITLE
react-native-fcm:compileReleaseJavaWithJavac FAILED 

### ISSUE THREAD

**Issue by piyush2468** [tolu360/react-native-google-places#81]
![error](https://user-images.githubusercontent.com/18625797/29923821-6a8de974-8e78-11e7-81a0-15bb2c943d3c.png)
Hello 
Could you please fix this problem ?
it keeps happening with me whether i do gradlew assemblerelease or try running it through cli.
![error1](https://user-images.githubusercontent.com/18625797/29923802-62f690c6-8e78-11e7-8845-69c2a48f7eb0.png)

**Comment by chrusart** [comment]
Use latest version, it was fixed in 2.4.2.

**Comment by tolu360** [comment]
Feel free to re-open if you still have issues
