### ISSUE TITLE
Pre-populate the openAutocompleteModal() input with last search?

### ISSUE THREAD

**Issue by chapeljuice** [tolu360/react-native-google-places#82]
Is there a way to fill in the `openAutocompleteModal()` input with the last search the user entered? I know how to store and access the data, but I don't see any way to tell the module what it is.

So, to reiterate: the user would open the auto-complete modal, search for something, and then want to open the auto-complete modal back up and edit their previous search.

I'm running `"react-native-google-places": "^2.1.0",`

Thanks!

**Comment by tolu360** [comment]
You'd have to manage data persistence on your own - I'd use `getAutocompletePredictions()` for this. You can always use own UIs and achieve something close to what you described above. [See README for more](https://github.com/tolu360/react-native-google-places#using-your-own-custom-uiviews)
