### ISSUE TITLE
Error making places detection api call: ERROR

### ISSUE THREAD

**Issue by anuragprajapat** [tolu360/react-native-google-places#83]
On getCurrentPlace() getting this error.

**Comment by tolu360** [comment]
Please try on a physical device, not sure this works on the emulator.

**Comment by simonbuerger** [comment]
I'm getting this error on a real device

**Comment by andela-cofor** [comment]
If you don't have google play store update your android studio to 3.3
then create and emulator with 5X
Try updating google play services from the play store on emulator.
clean- build-run did the trick for me

**Comment by nickmccomb** [comment]
Was getting the same issue on a physical device and emulator.  You need to enable Places API, as well as Places API for Android & Places API for iOS

**Comment by aayushiyadav007** [comment]
Please ensure your device GPS location is on and above Lollipop version ACCESS_FINE LOCATION permission should be enable, because it worked for me.

**Comment by lordmaul** [comment]
Mine was working fine until I did ./gradlew assembleRelease
Platform details
OS: Mac OS Sierra 10.12.6
Node: 10.15.1
npm: 6.7.0
react-native: 0.58.4 

And since then, even react-native run-android is now throwing that error. There was no single change to my code.
