### ISSUE TITLE
Is there any way to get city name & state code from the auto complete search?

### ISSUE THREAD

**Issue by CrazzzyDev** [tolu360/react-native-google-places#84]
I need to show city name and state code only on autocomplete search. 
like  "Williamsburg, VA"

**Comment by tolu360** [comment]
I'm afraid the underlying Google SDKs do not allow for extreme levels of customisation. You can certainly build out your own UIs using the `getAutocompletePredictions()` method but you are still limited in the amount of customisations you can hope for!

Cheers!
