### ISSUE TITLE
Autocomplete giving error

### ISSUE THREAD

**Issue by shaikhussian** [tolu360/react-native-google-places#85]
Error Domain=com.google.places.ErrorDomain Code=-3 "An internal error occurred in the Places API library. If you believe this error represents a bug, please file a report using the instructions on our community and support page (https://developers.google.com/places/support)." UserInfo={NSLocalizedFailureReason=An internal error occurred in the Places API library. If you believe this error represents a bug, please file a report using the instructions on our community and support page (https://developers.google.com/places/support)., NSUnderlyingError=0x600000858510 {Error Domain=com.google.places.server.ErrorDomain Code=-1 "(null)" UserInfo={NSUnderlyingError=0x600000858420 {Error Domain=com.google.GTLRErrorObjectDomain Code=400 "Bad Request" UserInfo={GTLRStructuredError=GMSx_GTLRErrorObject 0x6000008577f0: {message:"Bad Request" errors:[1] code:400}, NSLocalizedDescription=Bad Request}}}}}

**Comment by tolu360** [comment]
If this happens intermittently, it is usually API errors from Google servers. The errors go away, usually after a few re-tries.

Please re-open if you are still having issues.
