### ISSUE TITLE
android 6.0 flash back 

### ISSUE THREAD

**Issue by learnmove** [tolu360/react-native-google-places#86]
when I link react-native place and run-android
will flash back 
my version
{
  "name": "linug",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "jest-expo": "~20.0.0",
    "react-native-scripts": "1.3.1",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "expo": "^20.0.0",
    "native-base": "^2.3.1",
    "react": "16.0.0-alpha.12",
    "react-addons-update": "^15.6.0",
    "react-native": "^0.47.0",
    "react-native-google-places": "^2.4.2",
    "react-native-maps": "^0.16.3",
    "react-native-router-flux": "^4.0.0-beta.21",
    "react-native-vector-icons": "^4.3.0",
    "react-navigation": "^1.0.0-beta.11",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.2.0"
  }
}

**Comment by tolu360** [comment]
Projects being bootstrapped by expo are not currently supported, try to see if the errors go away if you start your project with the react-native cli running `react-native innit Project` and following the build setup in the README.
