### ISSUE TITLE
How does get Country Name / Country Code from a lat/lng or placeId ?

### ISSUE THREAD

**Issue by sonnguyenit** [tolu360/react-native-google-places#89]
How does get Country Name / Country Code from a lat/lng or placeId ?
I see the API:
`RNGooglePlaces.lookUpPlaceByID('ChIJZa6ezJa8j4AR1p1nTSaRtuQ')` with result:
```
{ name: 'Facebook HQ',
  website: 'https://www.facebook.com/',
  longitude: -122.14835169999999,
  address: '1 Hacker Way, Menlo Park, CA 94025, USA',
  latitude: 37.48485,
  placeID: 'ChIJZa6ezJa8j4AR1p1nTSaRtuQ',
  types: [ 'street_address', 'geocode' ],
  phoneNumber: '+1 650-543-4800',
}
```
I need a field name: countryName and countryCode

**Comment by tolu360** [comment]
There are other RN libraries providing geo-coding features, may not want to bloat up this package. I may consider a neat PR though. Cheers!

**Comment by alpamys-qanybet** [comment]
@tolu360, Hi there, in my application I do not know the place ID of the selected position in a map, but I need to fetch its address. I use your repo for autocomplete and select place, but I also change position on a map by gestures. So I will be grateful if there is an opportunity for method like this.

`RNGooglePlaces.lookUpPlaceByLatLng(lat, lng)` that returns the same result as
`lookUpPlaceByID`.

**Comment by tolu360** [comment]
Hi @alpamys-qanybet, take a look at https://github.com/devfd/react-native-geocoder for your needs.

**Comment by alpamys-qanybet** [comment]
@tolu360, thnx. already realized, but anyway.
