### ISSUE TITLE
I can't generate ipa file. 

### ISSUE THREAD

**Issue by starcraft0429** [tolu360/react-native-google-places#9]
Thanks for making this component.
I like this component to use in my app, very useful.

But I can't generate ipa file.
/////////////////////////////////////////////////////////////////////
In xcode, I can build successfully, but I can't build in terminal,
this error occurs.
****************************************************
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/_my_project_/ios/build/Build/Intermediates/RCTSettings.build/Debug-iphonesimulator/RCTSettings.build/Objects-normal/x86_64/RCTSettingsManager.o RCTSettingsManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/_my_project_/ios/build/Build/Intermediates/RCTAnimation.build/Debug-iphonesimulator/RCTAnimation.build/Objects-normal/x86_64/RCTFrameAnimation.o Drivers/RCTFrameAnimation.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

**Comment by temitope** [comment]
@starcraft0429 see #18 as I was having build issues. it may be related to the versioning of the Google library dependencies imported with CocoaPods

**Comment by starcraft0429** [comment]
Thanks @temitope +1

**Comment by tolu360** [comment]
@starcraft0429, hope you managed to make things work just fine? I'd close this now, please, feel free to re-open if necessary.

Cheers!
