### ISSUE TITLE
Placepicker modal close immediately on Android

### ISSUE THREAD

**Issue by kevindavee** [tolu360/react-native-google-places#93]
Hello @tolu360 ,

I have some problem. In the android version, the place picker modal close immediately.
The modal popped up, and the place list showed a spinner. But not more than 1 second, the modal close by itself

the code only looks like this:

```
buttonPress() {
RNGooglePlaces.openPlacePickerModal()
      .then((place) => {
        const province = place.addressComponents.administrative_area_level_1
        const isJakarta = province === 'Daerah Khusus Ibukota Jakarta' || place.address.indexOf('Jakarta') > -1
        if (!isJakarta) {
          Alert.alert(
            '',
            `Sorry, we're currently only serving delivery for Jakarta`,
            [
              {text: 'OK', onPress: () => console.log('OK Pressed')}
            ],
            { cancelable: false }
          )
        }
      })
}
```

But in iphone, it works very well. Please help me. Thanks

**Comment by kevindavee** [comment]
I have resolved the issues. The problem is from my Google Places API Key. Nothing to do with the code. Thanks

**Comment by ebouJ** [comment]
Please, I am currently facing the same issue on android it works perfectly on ios. I created a new key but still facing the same issue

**Comment by RameshkrishnanV** [comment]
i'm also facing this issue can you tel me how to fix this issue.

**Comment by Sofianne8** [comment]
I'm facing the same problem, if someones got any solution, that would be awesome.

**Comment by sanazkh** [comment]
I am facing the same issue. I checked my API key and could not find anything wrong with it.

**Comment by akiladevinda** [comment]
@kevindavee  i have this issue too.. How to solve this ?

**Comment by MariamMobeen** [comment]
Same issue. Generated a new api key with all the maps and places apis being enabled but the modal closes immediately.
