### ISSUE TITLE
"applications bundle identifier does not match one fo the allowed ios applications for the api key"

### ISSUE THREAD

**Issue by poyannabati** [tolu360/react-native-google-places#95]
```The operation couldn’t be completed. The application's bundle identifier does not match one of the allowed iOS applications for the API key. See the developer's guide (https://developers.google.com/places/ios/start) for how to configure bundle restrictions on API keys.```

The bundle identifier IS correct. 

Listed under that specific key I have

![image](https://user-images.githubusercontent.com/1499050/32955815-f6016562-cbae-11e7-902d-5d088b35c8bc.png)

and I'm only developing for iOS. 

Removing the API-restrictions, but keeping the application restriction, with the iOS bundle identifier in place removes the error. 

Any idea what it could be? 

I'm thinking the lib might use some other api that needs to be included in the list of allowed apis?

**Comment by Tohix** [comment]
i have the same problem

**Comment by tolu360** [comment]
Hi @poyannabati, it may be safer to generally just restrict your keys to the application (via the bundle identifier) unless you have other reasons to do API restrictions. Let me know your views or if there's something I'm missing here.
