### ISSUE TITLE
Cannot read property 'getAutocompletePredictions' of undefined

### ISSUE THREAD

**Issue by Aqueelmiq** [tolu360/react-native-google-places#96]
Version:
React Native 0.51
react native google places: 2.4.2

I followed the instructions on setting up API credentials, did linking and installed cocoapods. I also put the API key and imports in AppDelegate. Then I tried doing:

`
import GPlaces from 'react-native-google-places';
        GPlaces.getAutocompletePredictions('facebook')
            .then((place) => {
                console.log(place);
            })
            .catch(error => console.log(error.message));
`

It gave me this error: Cannot read property 'getAutocompletePredictions' of undefined

![image](https://user-images.githubusercontent.com/6711678/32989740-27996854-ccd1-11e7-8314-7c54e317a1c8.png)

**Comment by tolu360** [comment]
Hello @Aqueelmiq, how did you setup your project? Did you use the RN CLI? Please note that Expo is not supported at the moment.

If you initiated your project with the CLI, please do share your `podfile`, lets see if anything is amiss. A run-through the readme too may help to make sure you did not miss out on anything. Cheers

**Comment by Aqueelmiq** [comment]
Hey @tolu360, I set up using create-react-native-app and then ejected. It's not connected to expo in any way. I did recheck the readme and made sure I have followed the instructions in correct order. Here is my podfile dump

`# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'chicken65App' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for chicken65App
  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'GooglePlacePicker'

  target 'chicken65AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'chicken65App-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for chicken65App-tvOS

  target 'chicken65App-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
`

**Comment by cristianonescu** [comment]
i have the exact same issue on ios. but android works.
not working with `openAutocompleteModal` or `openPlacePickerModal`

any solutions? I double checked the installation. I tried also setting this manually. Can't make it work on ios.

**Comment by tolu360** [comment]
@Aqueelmiq, try to keep your Podfile as simple as possible, remove the references to `**tvOS**` and `**tests**` - something like:

```rb
target 'YourAppName' do
pod 'GooglePlaces'
pod 'GoogleMaps'
pod 'GooglePlacePicker'
end
```
Run `cd ios && pod deintegrate`. Then `pod install`. Clean and rebuild your project.

**Comment by rahulkant13may** [comment]
@cristianonescu how you solved this issue for Android ? Can you help me, I have created an issue for it as well ?

https://github.com/tolu360/react-native-google-places/issues/100

**Comment by chapeljuice** [comment]
Anyone solve this for iOS yet?!

**Comment by tolu360** [comment]
Guys, try the [sample app](https://github.com/tolu360/TestRNGP) if anyone is still having this issue. See if you can reproduce the issue with it. Cheers!
