### ISSUE TITLE
Insert nil object from objects[4]

### ISSUE THREAD

**Issue by vvkaghera** [tolu360/react-native-google-places#97]
I am getting error while using below code...

```
RNGooglePlaces.openPlacePickerModal({
      radius: 0.01
    })
```
 
**Error:**

>  Exception '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[4]' was thrown while invoking openPlacePickerModal on target RNGooglePlaces with params (
> 	        {
> 	        latitude = 0;
> 	        longitude = 0;
> 	        radius = "0.01";
> 	    },
> 	    5896,
> 	    5897
> 	)

**Comment by tolu360** [comment]
Please pass in a radius only if you are also setting a latitude and a longitude, otherwise just call `openPlacePickerModal() with no parameters. Please go through the [readme](https://github.com/tolu360/react-native-google-places#open-placepicker-modal) again. Cheers!
