### ISSUE TITLE
Android and AppState

### ISSUE THREAD

**Issue by jamesholcomb** [tolu360/react-native-google-places#98]
Calling openAutocompleteModal or openPlacePickerModal on Android causes AppState to go to background, but this does not occur on iOS.  My top level App component utilizes AppState changes for various socket housekeeping.

Is this a behavior that is specific to the way Android shows intents/modals?  Curious if it is possible to override.

**Comment by tolu360** [comment]
Not so sure you can work around this though - an Android, both the autocomplete and placepicker modals launch new activities, hence your main activity getting temporarily put in the background each time.
