### ISSUE TITLE
Error making autocomplete prediction API call

### ISSUE THREAD

**Issue by damathryx** [tolu360/react-native-google-places#99]
> Error making autocomplete prediction API call: Status{statusCode=ERROR, resolution=null}

getting this error using 

```
RNGooglePlaces.getAutocompletePredictions('facebook')
    .then((results) => console.log({ predictions: results }))
    .catch((error) => console.log(error.message));
```

can also see 403 error on console

![screen shot 2017-11-26 at 1 04 20 am](https://user-images.githubusercontent.com/14576761/33232721-c932ce3e-d245-11e7-952a-ab602b8af8a5.png)

but I'm not getting anymore of the stats.
I tried many things on setting up the API key not sure what triggered.

also added client id for it linking to the keystore sha1.
![screen shot 2017-11-26 at 1 08 47 am](https://user-images.githubusercontent.com/14576761/33232752-631b2f64-d246-11e7-81b6-d3f4ee22a3c3.png)

also, maps works. it is only places that doesnt

**Comment by tolu360** [comment]
Did you remember to add Google Places permissions to your API key? Please check again.

**Comment by adamwan92** [comment]
I'm also facing this issue. How do we add Google Places permission to our API Key?

**Comment by Jun711** [comment]
@adamwan92 
1) Go to Google Api dashboard
2) Select your project
3) Go to library and search for places
4) You will see Google Places API for Android / iOS 
5) Choose the one you want and enable it

**Comment by OlleMattsson** [comment]
I had managed to add restrictions to the API key. Once removed, things started working!
